// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2021-06-10
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include <ap_int.h>
#include <hls_stream.h>
#include "riscv_3stage.hpp"

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_instr_mem_struct;

typedef struct {
	ap_uint<1> instr_req_done;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_IFETCH_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	ap_uint<1> irq_recv;
	ap_uint<8> irq_mcause;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_EXEC_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_data_mem_struct;

typedef struct {
	ap_uint<1> rd_req;
	ap_uint<5> rd_addr;
	ap_uint<1> jump_req;
	ap_uint<32> jump_vector;
	ap_uint<1> mem_req;
	ap_uint<32> mem_addr;
	ap_uint<4> mem_be;
	ap_uint<32> mem_wdata;
	ap_uint<1> mem_cmd;
	ap_uint<1> load_signext;
	ap_uint<3> rd_source;
	ap_uint<32> rd_wdata;
	ap_uint<1> data_req_done;
	genmcopipe_handle_data_mem_struct genmcopipe_handle_data_mem;
} genpstage_MEMWB_TRX_BUF_STRUCT;

ap_uint<32> genpsticky_glbl_pc;
ap_uint<32> genpsticky_glbl_regfile [32];
ap_uint<1> genpsticky_glbl_jump_req_cmd;
ap_uint<32> genpsticky_glbl_jump_vector_cmd;
ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
ap_uint<1> genpsticky_glbl_MIRQEN;
ap_uint<32> genpsticky_glbl_MRETADDR;
ap_uint<1> genmcopipe_instr_mem_wr_done;
ap_uint<1> genmcopipe_instr_mem_rd_done;
ap_uint<1> genmcopipe_instr_mem_full_flag;
ap_uint<1> genmcopipe_instr_mem_empty_flag;
ap_uint<1> genmcopipe_instr_mem_wr_ptr;
ap_uint<1> genmcopipe_instr_mem_rd_ptr;
ap_uint<1> genmcopipe_data_mem_wr_done;
ap_uint<1> genmcopipe_data_mem_rd_done;
ap_uint<1> genmcopipe_data_mem_full_flag;
ap_uint<1> genmcopipe_data_mem_empty_flag;
ap_uint<1> genmcopipe_data_mem_wr_ptr;
ap_uint<1> genmcopipe_data_mem_rd_ptr;
genpstage_IFETCH_TRX_BUF_STRUCT genpstage_IFETCH_TRX_BUF [0:0];
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_IFETCH_genctrl_stalled_glbl;
genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_BUF [0:0];
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_EXEC_genctrl_stalled_glbl;
genpstage_MEMWB_TRX_BUF_STRUCT genpstage_MEMWB_TRX_BUF [0:0];
ap_uint<1> genpstage_MEMWB_TRX_BUF_COUNTER;
ap_uint<1> genpstage_MEMWB_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_MEMWB_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_MEMWB_genctrl_stalled_glbl;

void riscv_3stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<genpmodule_riscv_3stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_3stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req) {


	ap_uint<32> genpsticky_glbl_pc_buf;
	ap_uint<32> genpsticky_glbl_regfile_buf [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd_buf;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd_buf;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE_buf;
	ap_uint<1> genpsticky_glbl_MIRQEN_buf;
	ap_uint<32> genpsticky_glbl_MRETADDR_buf;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<1> genpstage_IFETCH_genpctrl_flushreq;
	ap_uint<1> genpstage_IFETCH_genctrl_active;
	ap_uint<1> genpstage_IFETCH_genctrl_working;
	ap_uint<1> genpstage_IFETCH_genctrl_succ;
	ap_uint<1> genpstage_IFETCH_genctrl_occupied;
	ap_uint<1> genpstage_IFETCH_genctrl_rdy;
	ap_uint<1> genpstage_IFETCH_genctrl_new;
	ap_uint<1> genpstage_IFETCH_genctrl_finish;
	ap_uint<1> gen148_pipex_succreq;
	ap_uint<1> gen149_pipex_succbuf;
	ap_uint<1> gen150_pipex_succreq;
	ap_uint<32> gen151_pipex_succbuf;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	ap_uint<1> genpstage_EXEC_genctrl_active;
	ap_uint<1> genpstage_EXEC_genctrl_working;
	ap_uint<1> genpstage_EXEC_genctrl_succ;
	ap_uint<1> genpstage_EXEC_genctrl_occupied;
	ap_uint<1> genpstage_EXEC_genctrl_rdy;
	ap_uint<1> genpstage_EXEC_genctrl_new;
	ap_uint<1> genpstage_EXEC_genctrl_finish;
	ap_uint<1> genpstage_MEMWB_genpctrl_flushreq;
	ap_uint<1> genpstage_MEMWB_genctrl_active;
	ap_uint<1> genpstage_MEMWB_genctrl_working;
	ap_uint<1> genpstage_MEMWB_genctrl_succ;
	ap_uint<1> genpstage_MEMWB_genctrl_occupied;
	ap_uint<1> genpstage_MEMWB_genctrl_rdy;
	ap_uint<1> genpstage_MEMWB_genctrl_new;
	ap_uint<1> genpstage_MEMWB_genctrl_finish;
	ap_uint<1> gen152_pipex_succreq;
	ap_uint<1> gen153_pipex_succbuf;
	ap_uint<1> gen154_pipex_succreq;
	ap_uint<32> gen155_pipex_succbuf;
	ap_uint<1> gen156_pipex_succreq;
	ap_uint<32> gen157_pipex_succbuf [32];
	ap_uint<1> gen158_pipex_var;
	ap_uint<33> gen159_pipex_var;
	ap_uint<1> gen160_pipex_var;
	ap_uint<1> gen161_pipex_var;
	ap_uint<1> gen162_pipex_var;
	ap_uint<1> gen163_pipex_var;
	ap_uint<1> gen164_pipex_var;
	ap_uint<1> gen165_pipex_var;
	ap_uint<1> gen166_pipex_var;
	ap_uint<1> gen167_pipex_var;
	ap_uint<32> gen168_pipex_var;
	ap_uint<1> gen169_pipex_var;
	ap_uint<32> gen170_pipex_var;
	ap_uint<12> gen171_pipex_var;
	ap_uint<1> gen172_pipex_var;
	ap_uint<32> gen173_pipex_var;
	ap_uint<13> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<32> gen176_pipex_var;
	ap_uint<32> gen177_pipex_var;
	ap_uint<21> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<32> gen180_pipex_var;
	ap_uint<1> gen181_pipex_var;
	ap_uint<1> gen182_pipex_var;
	ap_uint<1> gen183_pipex_var;
	ap_uint<1> gen184_pipex_var;
	ap_uint<32> gen185_pipex_var;
	ap_uint<1> gen186_pipex_var;
	ap_uint<1> gen187_pipex_var;
	ap_uint<32> gen188_pipex_var;
	ap_uint<1> gen189_pipex_var;
	ap_uint<1> gen190_pipex_var;
	ap_uint<1> gen191_pipex_var;
	ap_uint<1> gen192_pipex_var;
	ap_uint<1> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<32> gen195_pipex_var;
	ap_uint<32> gen196_pipex_var;
	ap_uint<32> gen197_pipex_var;
	ap_uint<1> gen198_pipex_var;
	ap_uint<1> gen199_pipex_var;
	ap_uint<1> gen200_pipex_var;
	ap_uint<1> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<32> gen203_pipex_var [32];
	ap_uint<32> gen204_pipex_var [32];
	ap_uint<1> gen205_pipex_var;
	ap_uint<1> gen206_pipex_var;
	ap_uint<1> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<1> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<1> gen211_pipex_var;
	ap_uint<1> gen212_pipex_var;
	ap_uint<1> gen213_pipex_var;
	ap_uint<1> gen214_pipex_var;
	ap_uint<5> gen215_pipex_var;
	ap_uint<1> gen216_pipex_var;
	ap_uint<1> gen217_pipex_var;
	ap_uint<1> gen218_pipex_var;
	ap_uint<5> gen219_pipex_var;
	ap_uint<1> gen220_pipex_var;
	ap_uint<1> gen221_pipex_var;
	ap_uint<1> gen222_pipex_var;
	ap_uint<33> gen223_pipex_var;
	ap_uint<33> gen224_pipex_var;
	ap_uint<1> gen225_pipex_var;
	ap_uint<1> gen226_pipex_var;
	ap_uint<33> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<33> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<1> gen235_pipex_var;
	ap_uint<1> gen236_pipex_var;
	ap_uint<34> gen237_pipex_var;
	ap_uint<34> gen238_pipex_var;
	ap_uint<33> gen239_pipex_var;
	ap_uint<33> gen240_pipex_var;
	ap_uint<33> gen241_pipex_var;
	ap_uint<64> gen242_pipex_var;
	ap_uint<64> gen243_pipex_var;
	ap_uint<32> gen244_pipex_var;
	ap_uint<1> gen245_pipex_var;
	ap_uint<64> gen246_pipex_var;
	ap_uint<64> gen247_pipex_var;
	ap_uint<33> gen248_pipex_var;
	ap_uint<33> gen249_pipex_var;
	ap_uint<33> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<1> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<1> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<33> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<1> gen266_pipex_var;
	ap_uint<1> gen267_pipex_var;
	ap_uint<1> gen268_pipex_var;
	ap_uint<1> gen269_pipex_var;
	ap_uint<1> gen270_pipex_var;
	ap_uint<1> gen271_pipex_var;
	ap_uint<1> gen272_pipex_var;
	ap_uint<1> gen273_pipex_var;
	ap_uint<1> gen274_pipex_var;
	ap_uint<1> gen275_pipex_var;
	ap_uint<1> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<1> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<1> gen280_pipex_var;
	ap_uint<1> gen281_pipex_var;
	ap_uint<1> gen282_pipex_var;
	ap_uint<1> gen283_pipex_var;
	ap_uint<1> gen284_pipex_var;
	ap_uint<1> gen285_pipex_var;
	ap_uint<1> gen286_pipex_var;
	ap_uint<1> gen287_pipex_var;
	ap_uint<1> gen288_pipex_var;
	ap_uint<1> gen289_pipex_var;
	ap_uint<8> gen290_pipex_var;
	ap_uint<1> gen291_pipex_var;
	ap_uint<32> gen292_pipex_var;
	ap_uint<1> gen293_pipex_var;
	ap_uint<32> gen294_pipex_var;
	ap_uint<1> gen295_pipex_var;
	ap_uint<1> gen296_pipex_var;
	ap_uint<1> gen297_pipex_var;
	ap_uint<16> gen298_pipex_var;
	ap_uint<1> gen299_pipex_var;
	ap_uint<32> gen300_pipex_var;
	ap_uint<1> gen301_pipex_var;
	ap_uint<32> gen302_pipex_var;
	ap_uint<1> gen303_pipex_var;
	ap_uint<1> gen304_pipex_var;
	ap_uint<1> gen305_pipex_var;
	ap_uint<32> genpstage_IFETCH_curinstr_addr;
	ap_uint<32> genpstage_IFETCH_nextinstr_addr;
	riscv_3stage_busreq_mem_struct genpstage_IFETCH_instr_busreq;
	ap_uint<1> genpstage_IFETCH_instr_req_done;
	ap_uint<32> genpstage_EXEC_instr_code;
	ap_uint<7> genpstage_EXEC_opcode;
	ap_uint<1> genpstage_EXEC_alu_unsigned;
	ap_uint<5> genpstage_EXEC_rs1_addr;
	ap_uint<5> genpstage_EXEC_rs2_addr;
	ap_uint<5> genpstage_EXEC_rd_addr;
	ap_uint<3> genpstage_EXEC_funct3;
	ap_uint<7> genpstage_EXEC_funct7;
	ap_uint<5> genpstage_EXEC_shamt;
	ap_uint<4> genpstage_EXEC_pred;
	ap_uint<4> genpstage_EXEC_succ;
	ap_uint<12> genpstage_EXEC_csrnum;
	ap_uint<5> genpstage_EXEC_zimm;
	ap_uint<32> genpstage_EXEC_immediate_I;
	ap_uint<32> genpstage_EXEC_immediate_S;
	ap_uint<32> genpstage_EXEC_immediate_B;
	ap_uint<32> genpstage_EXEC_immediate_U;
	ap_uint<32> genpstage_EXEC_immediate_J;
	ap_uint<2> genpstage_EXEC_op1_source;
	ap_uint<1> genpstage_EXEC_rd_req;
	ap_uint<3> genpstage_EXEC_rd_source;
	ap_uint<32> genpstage_EXEC_immediate;
	ap_uint<2> genpstage_EXEC_op2_source;
	ap_uint<1> genpstage_EXEC_alu_req;
	ap_uint<4> genpstage_EXEC_alu_opcode;
	ap_uint<1> genpstage_EXEC_jump_req;
	ap_uint<1> genpstage_EXEC_jump_src;
	ap_uint<1> genpstage_EXEC_rs1_req;
	ap_uint<1> genpstage_EXEC_rs2_req;
	ap_uint<1> genpstage_EXEC_jump_req_cond;
	ap_uint<1> genpstage_EXEC_mem_req;
	ap_uint<1> genpstage_EXEC_mem_cmd;
	ap_uint<1> genpstage_EXEC_fencereq;
	ap_uint<1> genpstage_EXEC_ebreakreq;
	ap_uint<1> genpstage_EXEC_ecallreq;
	ap_uint<1> genpstage_EXEC_csrreq;
	ap_uint<4> genpstage_EXEC_mem_be;
	ap_uint<1> genpstage_EXEC_load_signext;
	ap_uint<1> genpstage_EXEC_mret_req;
	ap_uint<32> genpstage_EXEC_rs1_rdata;
	ap_uint<32> genpstage_EXEC_rs2_rdata;
	ap_uint<32> genpstage_EXEC_csr_rdata;
	ap_uint<32> genpstage_EXEC_alu_op1;
	ap_uint<32> genpstage_EXEC_alu_op2;
	ap_uint<33> genpstage_EXEC_alu_op1_wide;
	ap_uint<33> genpstage_EXEC_alu_op2_wide;
	ap_uint<8> genpstage_EXEC_irq_mcause;
	ap_uint<1> genpstage_EXEC_irq_recv;
	ap_uint<33> genpstage_EXEC_alu_result_wide;
	ap_uint<32> genpstage_EXEC_alu_result;
	ap_uint<1> genpstage_EXEC_alu_CF;
	ap_uint<1> genpstage_EXEC_alu_SF;
	ap_uint<1> genpstage_EXEC_alu_ZF;
	ap_uint<1> genpstage_EXEC_alu_OF;
	ap_uint<1> genpstage_EXEC_alu_overflow;
	ap_uint<32> genpstage_EXEC_rd_wdata;
	ap_uint<1> genpstage_EXEC_rd_rdy;
	ap_uint<32> genpstage_EXEC_curinstraddr_imm;
	ap_uint<32> genpstage_EXEC_jump_vector;
	ap_uint<32> genpstage_EXEC_mem_addr;
	ap_uint<32> genpstage_EXEC_mem_wdata;
	ap_uint<32> genpstage_EXEC_curinstr_addr;
	ap_uint<32> genpstage_EXEC_nextinstr_addr;
	riscv_3stage_busreq_mem_struct genpstage_MEMWB_data_busreq;
	ap_uint<1> genpstage_MEMWB_data_req_done;
	ap_uint<32> genpstage_MEMWB_mem_rdata;
	ap_uint<1> genpstage_MEMWB_rd_rdy;
	ap_uint<32> genpstage_MEMWB_rd_wdata;
	ap_uint<1> genpstage_MEMWB_rd_req;
	ap_uint<5> genpstage_MEMWB_rd_addr;
	ap_uint<1> genpstage_MEMWB_jump_req;
	ap_uint<32> genpstage_MEMWB_jump_vector;
	ap_uint<1> genpstage_MEMWB_mem_req;
	ap_uint<32> genpstage_MEMWB_mem_addr;
	ap_uint<4> genpstage_MEMWB_mem_be;
	ap_uint<32> genpstage_MEMWB_mem_wdata;
	ap_uint<1> genpstage_MEMWB_mem_cmd;
	ap_uint<1> genpstage_MEMWB_load_signext;
	ap_uint<3> genpstage_MEMWB_rd_source;
	ap_uint<32> gen306_pipex_mcopipe_rdata;
	genpmodule_riscv_3stage_genmcopipe_data_mem_genstruct_fifo_wdata gen307_pipex_req_struct;
	ap_uint<32> gen308_pipex_mcopipe_rdata;
	ap_uint<32> gen309_pipex_mcopipe_rdata;
	genpmodule_riscv_3stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen310_pipex_req_struct;
	ap_uint<1> gen166_cyclix_var;
	ap_uint<1> gen167_cyclix_var;
	ap_uint<1> gen168_cyclix_var;
	ap_uint<1> gen169_cyclix_var;
	ap_uint<1> gen170_cyclix_var;
	ap_uint<1> gen171_cyclix_var;
	ap_uint<1> gen172_cyclix_var;
	ap_uint<1> gen173_cyclix_var;
	ap_uint<1> gen174_cyclix_var;
	ap_uint<1> gen175_cyclix_var;
	ap_uint<1> gen176_cyclix_var;
	ap_uint<1> gen177_cyclix_var;
	ap_uint<1> gen178_cyclix_var;
	ap_uint<1> gen179_cyclix_var;
	ap_uint<1> gen180_cyclix_var;
	ap_uint<1> gen181_cyclix_var;
	ap_uint<1> gen182_cyclix_var;
	ap_uint<1> gen183_cyclix_var;
	ap_uint<1> gen184_cyclix_var;
	ap_uint<1> gen185_cyclix_var;
	ap_uint<1> gen186_cyclix_var;
	ap_uint<1> gen187_cyclix_var;
	ap_uint<1> gen188_cyclix_var;
	ap_uint<1> gen189_cyclix_var;
	ap_uint<1> gen190_cyclix_var;
	ap_uint<1> gen191_cyclix_var;
	ap_uint<1> gen192_cyclix_var;
	ap_uint<1> gen193_cyclix_var;
	ap_uint<1> gen194_cyclix_var;
	ap_uint<1> gen195_cyclix_var;
	ap_uint<1> gen196_cyclix_var;
	ap_uint<1> gen197_cyclix_var;
	ap_uint<1> gen198_cyclix_var;
	ap_uint<1> gen199_cyclix_var;
	ap_uint<1> gen200_cyclix_var;
	ap_uint<1> gen201_cyclix_var;
	ap_uint<1> gen202_cyclix_var;
	ap_uint<1> gen203_cyclix_var;
	ap_uint<1> gen204_cyclix_var;
	ap_uint<1> gen205_cyclix_var;
	ap_uint<1> gen206_cyclix_var;
	ap_uint<1> gen207_cyclix_var;
	ap_uint<1> gen208_cyclix_var;
	ap_uint<1> gen209_cyclix_var;
	ap_uint<1> gen210_cyclix_var;
	ap_uint<1> gen211_cyclix_var;
	ap_uint<1> gen212_cyclix_var;
	ap_uint<1> gen213_cyclix_var;
	ap_uint<1> gen214_cyclix_var;
	ap_uint<1> gen215_cyclix_var;
	ap_uint<1> gen216_cyclix_var;
	ap_uint<1> gen217_cyclix_var;
	ap_uint<1> gen218_cyclix_var;
	ap_uint<1> gen219_cyclix_var;
	ap_uint<1> gen220_cyclix_var;
	ap_uint<1> gen221_cyclix_var;
	ap_uint<1> gen222_cyclix_var;
	ap_uint<1> gen223_cyclix_var;
	ap_uint<1> gen224_cyclix_var;
	ap_uint<1> gen225_cyclix_var;
	ap_uint<1> gen226_cyclix_var;
	ap_uint<1> gen227_cyclix_var;
	ap_uint<1> gen228_cyclix_var;
	ap_uint<1> gen229_cyclix_var;
	ap_uint<1> gen230_cyclix_var;
	ap_uint<1> gen231_cyclix_var;
	ap_uint<1> gen232_cyclix_var;
	ap_uint<1> gen233_cyclix_var;
	ap_uint<1> gen234_cyclix_var;
	ap_uint<1> gen235_cyclix_var;
	ap_uint<1> gen236_cyclix_var;
	ap_uint<1> gen237_cyclix_var;
	ap_uint<1> gen238_cyclix_var;
	ap_uint<1> gen239_cyclix_var;
	ap_uint<1> gen240_cyclix_var;
	ap_uint<1> gen241_cyclix_var;
	ap_uint<1> gen242_cyclix_var;
	ap_uint<1> gen243_cyclix_var;
	ap_uint<1> gen244_cyclix_var;
	ap_uint<1> gen245_cyclix_var;
	ap_uint<1> gen246_cyclix_var;
	ap_uint<1> gen247_cyclix_var;
	ap_uint<1> gen248_cyclix_var;
	ap_uint<1> gen249_cyclix_var;
	ap_uint<1> gen250_cyclix_var;
	ap_uint<1> gen251_cyclix_var;
	ap_uint<1> gen252_cyclix_var;
	ap_uint<1> gen253_cyclix_var;
	ap_uint<1> gen254_cyclix_var;
	ap_uint<1> gen255_cyclix_var;
	ap_uint<1> gen256_cyclix_var;
	ap_uint<1> gen257_cyclix_var;
	ap_uint<1> gen258_cyclix_var;
	ap_uint<1> gen259_cyclix_var;
	ap_uint<1> gen260_cyclix_var;
	ap_uint<1> gen261_cyclix_var;
	ap_uint<1> gen262_cyclix_var;
	ap_uint<1> gen263_cyclix_var;
	ap_uint<1> gen264_cyclix_var;
	ap_uint<1> gen265_cyclix_var;
	ap_uint<1> gen266_cyclix_var;
	ap_uint<1> gen267_cyclix_var;
	ap_uint<1> gen268_cyclix_var;
	ap_uint<1> gen269_cyclix_var;
	ap_uint<1> gen270_cyclix_var;
	ap_uint<1> gen271_cyclix_var;
	ap_uint<1> gen272_cyclix_var;
	ap_uint<1> gen273_cyclix_var;
	ap_uint<1> gen274_cyclix_var;
	ap_uint<1> gen275_cyclix_var;
	ap_uint<1> gen276_cyclix_var;
	ap_uint<1> gen277_cyclix_var;
	ap_uint<1> gen278_cyclix_var;
	ap_uint<1> gen279_cyclix_var;
	ap_uint<1> gen280_cyclix_var;
	ap_uint<1> gen281_cyclix_var;
	ap_uint<1> gen282_cyclix_var;
	ap_uint<1> gen283_cyclix_var;
	ap_uint<1> gen284_cyclix_var;
	ap_uint<1> gen285_cyclix_var;
	ap_uint<1> gen286_cyclix_var;
	ap_uint<1> gen287_cyclix_var;
	ap_uint<1> gen288_cyclix_var;
	ap_uint<1> gen289_cyclix_var;
	ap_uint<1> gen290_cyclix_var;
	ap_uint<1> gen291_cyclix_var;
	ap_uint<1> gen292_cyclix_var;
	ap_uint<1> gen293_cyclix_var;
	ap_uint<1> gen294_cyclix_var;
	ap_uint<1> gen295_cyclix_var;
	ap_uint<1> gen296_cyclix_var;
	ap_uint<1> gen297_cyclix_var;
	ap_uint<1> gen298_cyclix_var;
	ap_uint<1> gen299_cyclix_var;
	ap_uint<1> gen300_cyclix_var;
	ap_uint<1> gen301_cyclix_var;
	ap_uint<1> gen302_cyclix_var;
	ap_uint<1> gen303_cyclix_var;
	ap_uint<1> gen304_cyclix_var;
	ap_uint<1> gen305_cyclix_var;
	ap_uint<1> gen306_cyclix_var;
	ap_uint<1> gen307_cyclix_var;
	ap_uint<1> gen308_cyclix_var;
	ap_uint<1> gen309_cyclix_var;
	ap_uint<1> gen310_cyclix_var;
	ap_uint<1> gen311_cyclix_var;
	ap_uint<1> gen312_cyclix_var;
	ap_uint<1> gen313_cyclix_var;
	ap_uint<1> gen314_cyclix_var;
	ap_uint<1> gen315_cyclix_var;
	ap_uint<1> gen316_cyclix_var;
	ap_uint<1> gen317_cyclix_var;
	ap_uint<1> gen318_cyclix_var;
	ap_uint<1> gen319_cyclix_var;
	ap_uint<1> gen320_cyclix_var;
	ap_uint<1> gen321_cyclix_var;
	ap_uint<1> gen322_cyclix_var;
	ap_uint<1> gen323_cyclix_var;
	ap_uint<1> gen324_cyclix_var;
	ap_uint<1> gen325_cyclix_var;
	ap_uint<1> gen326_cyclix_var;
	ap_uint<1> gen327_cyclix_var;
	ap_uint<1> gen328_cyclix_var;
	ap_uint<1> gen329_cyclix_var;
	ap_uint<1> gen330_cyclix_var;
	ap_uint<1> gen331_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = ap_uint<32>(512);
		genpsticky_glbl_regfile[1] = ap_uint<32>(0);
		genpsticky_glbl_regfile[2] = ap_uint<32>(0);
		genpsticky_glbl_regfile[3] = ap_uint<32>(0);
		genpsticky_glbl_regfile[4] = ap_uint<32>(0);
		genpsticky_glbl_regfile[5] = ap_uint<32>(0);
		genpsticky_glbl_regfile[6] = ap_uint<32>(0);
		genpsticky_glbl_regfile[7] = ap_uint<32>(0);
		genpsticky_glbl_regfile[8] = ap_uint<32>(0);
		genpsticky_glbl_regfile[9] = ap_uint<32>(0);
		genpsticky_glbl_regfile[10] = ap_uint<32>(0);
		genpsticky_glbl_regfile[11] = ap_uint<32>(0);
		genpsticky_glbl_regfile[12] = ap_uint<32>(0);
		genpsticky_glbl_regfile[13] = ap_uint<32>(0);
		genpsticky_glbl_regfile[14] = ap_uint<32>(0);
		genpsticky_glbl_regfile[15] = ap_uint<32>(0);
		genpsticky_glbl_regfile[16] = ap_uint<32>(0);
		genpsticky_glbl_regfile[17] = ap_uint<32>(0);
		genpsticky_glbl_regfile[18] = ap_uint<32>(0);
		genpsticky_glbl_regfile[19] = ap_uint<32>(0);
		genpsticky_glbl_regfile[20] = ap_uint<32>(0);
		genpsticky_glbl_regfile[21] = ap_uint<32>(0);
		genpsticky_glbl_regfile[22] = ap_uint<32>(0);
		genpsticky_glbl_regfile[23] = ap_uint<32>(0);
		genpsticky_glbl_regfile[24] = ap_uint<32>(0);
		genpsticky_glbl_regfile[25] = ap_uint<32>(0);
		genpsticky_glbl_regfile[26] = ap_uint<32>(0);
		genpsticky_glbl_regfile[27] = ap_uint<32>(0);
		genpsticky_glbl_regfile[28] = ap_uint<32>(0);
		genpsticky_glbl_regfile[29] = ap_uint<32>(0);
		genpsticky_glbl_regfile[30] = ap_uint<32>(0);
		genpsticky_glbl_regfile[31] = ap_uint<32>(0);
		genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
		genpsticky_glbl_jump_vector_cmd = ap_uint<32>(0);
		genpsticky_glbl_CSR_MCAUSE = ap_uint<32>(0);
		genpsticky_glbl_MIRQEN = ap_uint<32>(1);
		genpsticky_glbl_MRETADDR = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
		genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_instr_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_full_flag = ap_uint<32>(0);
		genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_data_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_rd_ptr = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
		genpstage_MEMWB_TRX_BUF = ap_uint<32>(0);
		genpstage_MEMWB_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_MEMWB_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_MEMWB_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_MEMWB_genctrl_stalled_glbl = ap_uint<32>(0);

	} else {
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genpsticky_glbl_pc_buf = genpsticky_glbl_pc;
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[1];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[2];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[3];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[4];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[5];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[6];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[7];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[8];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[9];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[10];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[11];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[12];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[13];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[14];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[15];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[16];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[17];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[18];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[19];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[20];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[21];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[22];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[23];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[24];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[25];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[26];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[27];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[28];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[29];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[30];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[31];
		genpsticky_glbl_jump_req_cmd_buf = genpsticky_glbl_jump_req_cmd;
		genpsticky_glbl_jump_vector_cmd_buf = genpsticky_glbl_jump_vector_cmd;
		genpsticky_glbl_CSR_MCAUSE_buf = genpsticky_glbl_CSR_MCAUSE;
		genpsticky_glbl_MIRQEN_buf = genpsticky_glbl_MIRQEN;
		genpsticky_glbl_MRETADDR_buf = genpsticky_glbl_MRETADDR;
		genpstage_MEMWB_genctrl_succ = ap_uint<32>(0);
		genpstage_MEMWB_genctrl_working = ap_uint<32>(0);
		gen166_cyclix_var = genpstage_MEMWB_genctrl_stalled_glbl;
		if (gen166_cyclix_var) {
			genpstage_MEMWB_genctrl_new = ap_uint<32>(0);
			genpstage_MEMWB_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_MEMWB_genctrl_active = ap_uint<32>(1);
		}
		gen167_cyclix_var = ap_uint<1>(0);
		gen167_cyclix_var = (gen167_cyclix_var || gen166_cyclix_var);
		gen167_cyclix_var = !gen167_cyclix_var;
		if (gen167_cyclix_var) {
			genpstage_MEMWB_genctrl_active = genpstage_MEMWB_TRX_BUF_COUNTER_NEMPTY;
			genpstage_MEMWB_genctrl_new = genpstage_MEMWB_genctrl_active;
		}
		genpstage_MEMWB_genctrl_occupied = genpstage_MEMWB_genctrl_active;
		genpstage_MEMWB_genctrl_finish = ap_uint<32>(0);
		genpstage_MEMWB_genpctrl_flushreq = ap_uint<32>(0);
		gen168_cyclix_var = genpstage_MEMWB_genctrl_occupied;
		if (gen168_cyclix_var) {
			gen169_cyclix_var = genpstage_MEMWB_genctrl_new;
			if (gen169_cyclix_var) {
				genpstage_MEMWB_TRX_BUF = ap_uint<32>(0);
			}
			genpstage_MEMWB_rd_req = genpstage_MEMWB_TRX_BUF[0].rd_req;
			genpstage_MEMWB_rd_addr = genpstage_MEMWB_TRX_BUF[0].rd_addr;
			genpstage_MEMWB_jump_req = genpstage_MEMWB_TRX_BUF[0].jump_req;
			genpstage_MEMWB_jump_vector = genpstage_MEMWB_TRX_BUF[0].jump_vector;
			genpstage_MEMWB_mem_req = genpstage_MEMWB_TRX_BUF[0].mem_req;
			genpstage_MEMWB_mem_addr = genpstage_MEMWB_TRX_BUF[0].mem_addr;
			genpstage_MEMWB_mem_be = genpstage_MEMWB_TRX_BUF[0].mem_be;
			genpstage_MEMWB_mem_wdata = genpstage_MEMWB_TRX_BUF[0].mem_wdata;
			genpstage_MEMWB_mem_cmd = genpstage_MEMWB_TRX_BUF[0].mem_cmd;
			genpstage_MEMWB_load_signext = genpstage_MEMWB_TRX_BUF[0].load_signext;
			genpstage_MEMWB_rd_source = genpstage_MEMWB_TRX_BUF[0].rd_source;
			genpstage_MEMWB_rd_wdata = genpstage_MEMWB_TRX_BUF[0].rd_wdata;
			genpstage_MEMWB_data_req_done = genpstage_MEMWB_TRX_BUF[0].data_req_done;
			gen170_cyclix_var = genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
			if (gen170_cyclix_var) {
				gen171_cyclix_var = (genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.if_id == ap_uint<1>(0));
				gen172_cyclix_var = gen171_cyclix_var;
				if (gen172_cyclix_var) {
					gen173_cyclix_var = (genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.tid == genmcopipe_data_mem_rd_ptr);
					gen174_cyclix_var = gen173_cyclix_var;
					if (gen174_cyclix_var) {
						gen175_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen306_pipex_mcopipe_rdata);
						gen176_cyclix_var = gen175_cyclix_var;
						if (gen176_cyclix_var) {
							genpstage_MEMWB_TRX_BUF = ap_uint<32>(0);
							genpstage_MEMWB_TRX_BUF = ap_uint<32>(1);
							genpstage_MEMWB_TRX_BUF = gen306_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen177_cyclix_var = genpstage_MEMWB_genpctrl_flushreq;
			if (gen177_cyclix_var) {
				genpstage_MEMWB_genctrl_active = ap_uint<32>(0);
			}
		}
		gen153_pipex_succbuf = genpsticky_glbl_jump_req_cmd;
		gen155_pipex_succbuf = genpsticky_glbl_jump_vector_cmd;
		gen157_pipex_succbuf = genpsticky_glbl_regfile[1];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[2];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[3];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[4];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[5];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[6];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[7];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[8];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[9];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[10];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[11];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[12];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[13];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[14];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[15];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[16];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[17];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[18];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[19];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[20];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[21];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[22];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[23];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[24];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[25];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[26];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[27];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[28];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[29];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[30];
		gen157_pipex_succbuf = genpsticky_glbl_regfile[31];
		gen152_pipex_succreq = ap_uint<32>(1);
		gen153_pipex_succbuf = genpstage_MEMWB_jump_req;
		gen154_pipex_succreq = ap_uint<32>(1);
		gen155_pipex_succbuf = genpstage_MEMWB_jump_vector;
		gen274_pipex_var = genpstage_MEMWB_jump_req;
		gen178_cyclix_var = gen274_pipex_var;
		if (gen178_cyclix_var) {
			genpstage_MEMWB_genpctrl_flushreq = (genpstage_MEMWB_genpctrl_flushreq | genpstage_MEMWB_genctrl_active);
		}
		gen275_pipex_var = genpstage_MEMWB_mem_req;
		gen179_cyclix_var = gen275_pipex_var;
		if (gen179_cyclix_var) {
			gen276_pipex_var = ~genpstage_MEMWB_data_req_done;
			gen277_pipex_var = gen276_pipex_var;
			gen180_cyclix_var = gen277_pipex_var;
			if (gen180_cyclix_var) {
				genpstage_MEMWB_data_busreq = genpstage_MEMWB_mem_addr;
				genpstage_MEMWB_data_busreq = genpstage_MEMWB_mem_be;
				genpstage_MEMWB_data_busreq = genpstage_MEMWB_mem_wdata;
				gen181_cyclix_var = genpstage_MEMWB_genctrl_active;
				if (gen181_cyclix_var) {
					gen182_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen183_cyclix_var = gen182_cyclix_var;
					if (gen183_cyclix_var) {
						gen307_pipex_req_struct = genpstage_MEMWB_mem_cmd;
						gen307_pipex_req_struct = genpstage_MEMWB_data_busreq;
						gen184_cyclix_var = genmcopipe_data_mem_req.write_nb(gen307_pipex_req_struct);
						gen185_cyclix_var = gen184_cyclix_var;
						if (gen185_cyclix_var) {
							gen278_pipex_var = ap_uint<32>(1);
							gen186_cyclix_var = !genpstage_MEMWB_mem_cmd;
							genpstage_MEMWB_TRX_BUF = gen186_cyclix_var;
							genpstage_MEMWB_TRX_BUF = genmcopipe_data_mem_wr_ptr;
							genpstage_MEMWB_TRX_BUF = ap_uint<1>(0);
							gen187_cyclix_var = genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
							if (gen187_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_MEMWB_data_req_done = gen278_pipex_var;
				gen188_cyclix_var = genpstage_MEMWB_genctrl_active;
				if (gen188_cyclix_var) {
					genpstage_MEMWB_TRX_BUF = gen278_pipex_var;
				}
			}
			gen279_pipex_var = ~genpstage_MEMWB_data_req_done;
			gen280_pipex_var = gen279_pipex_var;
			gen189_cyclix_var = gen280_pipex_var;
			if (gen189_cyclix_var) {
				gen190_cyclix_var = genpstage_MEMWB_genctrl_active;
				if (gen190_cyclix_var) {
					genpstage_MEMWB_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_MEMWB_genctrl_active = ap_uint<32>(0);
			}
		}
		gen281_pipex_var = genpstage_MEMWB_mem_req;
		gen191_cyclix_var = gen281_pipex_var;
		if (gen191_cyclix_var) {
			gen282_pipex_var = ~genpstage_MEMWB_mem_cmd;
			gen283_pipex_var = gen282_pipex_var;
			gen192_cyclix_var = gen283_pipex_var;
			if (gen192_cyclix_var) {
				gen193_cyclix_var = genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				if (gen193_cyclix_var) {
					genpstage_MEMWB_mem_rdata = genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.rdata;
				}
				gen284_pipex_var = genpstage_MEMWB_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				gen285_pipex_var = gen284_pipex_var;
				gen194_cyclix_var = gen285_pipex_var;
				if (gen194_cyclix_var) {
					genpstage_MEMWB_rd_rdy = ap_uint<32>(1);
				}
				gen286_pipex_var = ap_uint<1>(0);
				gen286_pipex_var = (gen286_pipex_var || gen285_pipex_var);
				gen286_pipex_var = !gen286_pipex_var;
				gen195_cyclix_var = gen286_pipex_var;
				if (gen195_cyclix_var) {
					gen196_cyclix_var = genpstage_MEMWB_genctrl_active;
					if (gen196_cyclix_var) {
						genpstage_MEMWB_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_MEMWB_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		gen287_pipex_var = (genpstage_MEMWB_mem_be == ap_uint<32>(1));
		gen288_pipex_var = gen287_pipex_var;
		gen197_cyclix_var = gen288_pipex_var;
		if (gen197_cyclix_var) {
			gen289_pipex_var = genpstage_MEMWB_load_signext;
			gen198_cyclix_var = gen289_pipex_var;
			if (gen198_cyclix_var) {
				gen290_pipex_var = genpstage_MEMWB_mem_rdata[7:0];
				gen291_pipex_var = gen290_pipex_var[7];
				gen292_pipex_var = gen291_pipex_var.concat((ap_uint<31>)gen291_pipex_var.concat((ap_uint<30>)gen291_pipex_var.concat((ap_uint<29>)gen291_pipex_var.concat((ap_uint<28>)gen291_pipex_var.concat((ap_uint<27>)gen291_pipex_var.concat((ap_uint<26>)gen291_pipex_var.concat((ap_uint<25>)gen291_pipex_var.concat((ap_uint<24>)gen291_pipex_var.concat((ap_uint<23>)gen291_pipex_var.concat((ap_uint<22>)gen291_pipex_var.concat((ap_uint<21>)gen291_pipex_var.concat((ap_uint<20>)gen291_pipex_var.concat((ap_uint<19>)gen291_pipex_var.concat((ap_uint<18>)gen291_pipex_var.concat((ap_uint<17>)gen291_pipex_var.concat((ap_uint<16>)gen291_pipex_var.concat((ap_uint<15>)gen291_pipex_var.concat((ap_uint<14>)gen291_pipex_var.concat((ap_uint<13>)gen291_pipex_var.concat((ap_uint<12>)gen291_pipex_var.concat((ap_uint<11>)gen291_pipex_var.concat((ap_uint<10>)gen291_pipex_var.concat((ap_uint<9>)gen291_pipex_var.concat((ap_uint<8>)genpstage_MEMWB_mem_rdata[7:0]))))))))))))))))))))))));
				genpstage_MEMWB_mem_rdata = gen292_pipex_var;
			}
			gen293_pipex_var = ap_uint<1>(0);
			gen293_pipex_var = (gen293_pipex_var || gen289_pipex_var);
			gen293_pipex_var = !gen293_pipex_var;
			gen199_cyclix_var = gen293_pipex_var;
			if (gen199_cyclix_var) {
				gen294_pipex_var = ap_uint<24>(0).concat((ap_uint<8>)genpstage_MEMWB_mem_rdata[7:0]);
				genpstage_MEMWB_mem_rdata = gen294_pipex_var;
			}
		}
		gen295_pipex_var = (genpstage_MEMWB_mem_be == ap_uint<32>(3));
		gen296_pipex_var = gen295_pipex_var;
		gen200_cyclix_var = gen296_pipex_var;
		if (gen200_cyclix_var) {
			gen297_pipex_var = genpstage_MEMWB_load_signext;
			gen201_cyclix_var = gen297_pipex_var;
			if (gen201_cyclix_var) {
				gen298_pipex_var = genpstage_MEMWB_mem_rdata[15:0];
				gen299_pipex_var = gen298_pipex_var[15];
				gen300_pipex_var = gen299_pipex_var.concat((ap_uint<31>)gen299_pipex_var.concat((ap_uint<30>)gen299_pipex_var.concat((ap_uint<29>)gen299_pipex_var.concat((ap_uint<28>)gen299_pipex_var.concat((ap_uint<27>)gen299_pipex_var.concat((ap_uint<26>)gen299_pipex_var.concat((ap_uint<25>)gen299_pipex_var.concat((ap_uint<24>)gen299_pipex_var.concat((ap_uint<23>)gen299_pipex_var.concat((ap_uint<22>)gen299_pipex_var.concat((ap_uint<21>)gen299_pipex_var.concat((ap_uint<20>)gen299_pipex_var.concat((ap_uint<19>)gen299_pipex_var.concat((ap_uint<18>)gen299_pipex_var.concat((ap_uint<17>)gen299_pipex_var.concat((ap_uint<16>)genpstage_MEMWB_mem_rdata[15:0]))))))))))))))));
				genpstage_MEMWB_mem_rdata = gen300_pipex_var;
			}
			gen301_pipex_var = ap_uint<1>(0);
			gen301_pipex_var = (gen301_pipex_var || gen297_pipex_var);
			gen301_pipex_var = !gen301_pipex_var;
			gen202_cyclix_var = gen301_pipex_var;
			if (gen202_cyclix_var) {
				gen302_pipex_var = ap_uint<16>(0).concat((ap_uint<16>)genpstage_MEMWB_mem_rdata[15:0]);
				genpstage_MEMWB_mem_rdata = gen302_pipex_var;
			}
		}
		gen303_pipex_var = (genpstage_MEMWB_rd_source == ap_uint<32>(5));
		gen304_pipex_var = gen303_pipex_var;
		gen203_cyclix_var = gen304_pipex_var;
		if (gen203_cyclix_var) {
			genpstage_MEMWB_rd_wdata = genpstage_MEMWB_mem_rdata;
		}
		gen305_pipex_var = genpstage_MEMWB_rd_req;
		gen204_cyclix_var = gen305_pipex_var;
		if (gen204_cyclix_var) {
			gen156_pipex_succreq = ap_uint<32>(1);
			gen157_pipex_succbuf = genpstage_MEMWB_rd_wdata;
		}
		gen205_cyclix_var = genpstage_MEMWB_genctrl_stalled_glbl;
		if (gen205_cyclix_var) {
			genpstage_MEMWB_genctrl_finish = ap_uint<32>(0);
			genpstage_MEMWB_genctrl_succ = ap_uint<32>(0);
		}
		gen206_cyclix_var = ap_uint<1>(0);
		gen206_cyclix_var = (gen206_cyclix_var || gen205_cyclix_var);
		gen206_cyclix_var = !gen206_cyclix_var;
		if (gen206_cyclix_var) {
			genpstage_MEMWB_genctrl_finish = genpstage_MEMWB_genctrl_occupied;
			genpstage_MEMWB_genctrl_succ = genpstage_MEMWB_genctrl_active;
		}
		gen207_cyclix_var = genpstage_MEMWB_genctrl_succ;
		if (gen207_cyclix_var) {
			gen208_cyclix_var = gen152_pipex_succreq;
			if (gen208_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen153_pipex_succbuf;
			}
			gen209_cyclix_var = gen154_pipex_succreq;
			if (gen209_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = gen155_pipex_succbuf;
			}
			gen210_cyclix_var = gen156_pipex_succreq;
			if (gen210_cyclix_var) {
				genpsticky_glbl_regfile = gen157_pipex_succbuf[1];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[2];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[3];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[4];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[5];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[6];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[7];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[8];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[9];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[10];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[11];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[12];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[13];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[14];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[15];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[16];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[17];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[18];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[19];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[20];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[21];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[22];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[23];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[24];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[25];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[26];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[27];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[28];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[29];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[30];
				genpsticky_glbl_regfile = gen157_pipex_succbuf[31];
			}
		}
		gen211_cyclix_var = genpstage_MEMWB_genctrl_finish;
		if (gen211_cyclix_var) {
			gen212_cyclix_var = genpstage_MEMWB_genctrl_succ;
			if (gen212_cyclix_var) {
			}
			genpstage_MEMWB_genctrl_active = ap_uint<32>(0);
			genpstage_MEMWB_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_MEMWB_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_MEMWB_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_MEMWB_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_MEMWB_TRX_BUF_COUNTER = (genpstage_MEMWB_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen213_cyclix_var = ~genpstage_MEMWB_TRX_BUF_COUNTER_FULL;
		genpstage_MEMWB_genctrl_rdy = gen213_cyclix_var;
		genpstage_MEMWB_genctrl_working = (genpstage_MEMWB_genctrl_succ | genpstage_MEMWB_genctrl_stalled_glbl);
		genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genctrl_working = ap_uint<32>(0);
		gen214_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen214_cyclix_var) {
			genpstage_EXEC_genctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
		}
		gen215_cyclix_var = ap_uint<1>(0);
		gen215_cyclix_var = (gen215_cyclix_var || gen214_cyclix_var);
		gen215_cyclix_var = !gen215_cyclix_var;
		if (gen215_cyclix_var) {
			genpstage_EXEC_genctrl_active = genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
			genpstage_EXEC_genctrl_new = genpstage_EXEC_genctrl_active;
		}
		genpstage_EXEC_genctrl_occupied = genpstage_EXEC_genctrl_active;
		genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = (genpstage_EXEC_genpctrl_flushreq | genpstage_MEMWB_genpctrl_flushreq);
		gen216_cyclix_var = genpstage_EXEC_genctrl_occupied;
		if (gen216_cyclix_var) {
			gen217_cyclix_var = genpstage_EXEC_genctrl_new;
			if (gen217_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
			genpstage_EXEC_curinstr_addr = genpstage_EXEC_TRX_BUF[0].curinstr_addr;
			genpstage_EXEC_nextinstr_addr = genpstage_EXEC_TRX_BUF[0].nextinstr_addr;
			genpstage_EXEC_irq_recv = genpstage_EXEC_TRX_BUF[0].irq_recv;
			genpstage_EXEC_irq_mcause = genpstage_EXEC_TRX_BUF[0].irq_mcause;
			gen218_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen218_cyclix_var) {
				gen219_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen220_cyclix_var = gen219_cyclix_var;
				if (gen220_cyclix_var) {
					gen221_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen222_cyclix_var = gen221_cyclix_var;
					if (gen222_cyclix_var) {
						gen223_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen308_pipex_mcopipe_rdata);
						gen224_cyclix_var = gen223_cyclix_var;
						if (gen224_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen308_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen225_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen225_cyclix_var) {
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen226_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		if (gen226_cyclix_var) {
			genpstage_EXEC_instr_code = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
		}
		gen165_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		gen166_pipex_var = ~gen165_pipex_var;
		gen167_pipex_var = gen166_pipex_var;
		gen227_cyclix_var = gen167_pipex_var;
		if (gen227_cyclix_var) {
			gen228_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen228_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		genpstage_EXEC_opcode = genpstage_EXEC_instr_code[6:0];
		genpstage_EXEC_alu_unsigned = ap_uint<32>(0);
		genpstage_EXEC_rs1_addr = genpstage_EXEC_instr_code[19:15];
		genpstage_EXEC_rs2_addr = genpstage_EXEC_instr_code[24:20];
		genpstage_EXEC_rd_addr = genpstage_EXEC_instr_code[11:7];
		genpstage_EXEC_funct3 = genpstage_EXEC_instr_code[14:12];
		genpstage_EXEC_funct7 = genpstage_EXEC_instr_code[31:25];
		genpstage_EXEC_shamt = genpstage_EXEC_instr_code[24:20];
		genpstage_EXEC_pred = genpstage_EXEC_instr_code[27:24];
		genpstage_EXEC_succ = genpstage_EXEC_instr_code[23:20];
		genpstage_EXEC_csrnum = genpstage_EXEC_instr_code[31:20];
		genpstage_EXEC_zimm = genpstage_EXEC_instr_code[19:15];
		gen168_pipex_var = genpstage_EXEC_instr_code[31:20];
		gen169_pipex_var = gen168_pipex_var[31];
		gen170_pipex_var = gen169_pipex_var.concat((ap_uint<31>)gen169_pipex_var.concat((ap_uint<30>)gen169_pipex_var.concat((ap_uint<29>)gen169_pipex_var.concat((ap_uint<28>)gen169_pipex_var.concat((ap_uint<27>)gen169_pipex_var.concat((ap_uint<26>)gen169_pipex_var.concat((ap_uint<25>)gen169_pipex_var.concat((ap_uint<24>)gen169_pipex_var.concat((ap_uint<23>)gen169_pipex_var.concat((ap_uint<22>)gen169_pipex_var.concat((ap_uint<21>)gen169_pipex_var.concat((ap_uint<20>)gen169_pipex_var.concat((ap_uint<19>)gen169_pipex_var.concat((ap_uint<18>)gen169_pipex_var.concat((ap_uint<17>)gen169_pipex_var.concat((ap_uint<16>)gen169_pipex_var.concat((ap_uint<15>)gen169_pipex_var.concat((ap_uint<14>)gen169_pipex_var.concat((ap_uint<13>)gen169_pipex_var.concat((ap_uint<12>)genpstage_EXEC_instr_code[31:20]))))))))))))))))))));
		genpstage_EXEC_immediate_I = gen170_pipex_var;
		gen171_pipex_var = genpstage_EXEC_instr_code[31:25].concat((ap_uint<5>)genpstage_EXEC_instr_code[11:7]);
		gen172_pipex_var = gen171_pipex_var[11];
		gen173_pipex_var = gen172_pipex_var.concat((ap_uint<31>)gen172_pipex_var.concat((ap_uint<30>)gen172_pipex_var.concat((ap_uint<29>)gen172_pipex_var.concat((ap_uint<28>)gen172_pipex_var.concat((ap_uint<27>)gen172_pipex_var.concat((ap_uint<26>)gen172_pipex_var.concat((ap_uint<25>)gen172_pipex_var.concat((ap_uint<24>)gen172_pipex_var.concat((ap_uint<23>)gen172_pipex_var.concat((ap_uint<22>)gen172_pipex_var.concat((ap_uint<21>)gen172_pipex_var.concat((ap_uint<20>)gen172_pipex_var.concat((ap_uint<19>)gen172_pipex_var.concat((ap_uint<18>)gen172_pipex_var.concat((ap_uint<17>)gen172_pipex_var.concat((ap_uint<16>)gen172_pipex_var.concat((ap_uint<15>)gen172_pipex_var.concat((ap_uint<14>)gen172_pipex_var.concat((ap_uint<13>)gen172_pipex_var.concat((ap_uint<12>)gen171_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_S = gen173_pipex_var;
		gen174_pipex_var = genpstage_EXEC_instr_code[31].concat((ap_uint<12>)genpstage_EXEC_instr_code[7].concat((ap_uint<11>)genpstage_EXEC_instr_code[30:25].concat((ap_uint<5>)genpstage_EXEC_instr_code[11:8].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen175_pipex_var = gen174_pipex_var[12];
		gen176_pipex_var = gen175_pipex_var.concat((ap_uint<31>)gen175_pipex_var.concat((ap_uint<30>)gen175_pipex_var.concat((ap_uint<29>)gen175_pipex_var.concat((ap_uint<28>)gen175_pipex_var.concat((ap_uint<27>)gen175_pipex_var.concat((ap_uint<26>)gen175_pipex_var.concat((ap_uint<25>)gen175_pipex_var.concat((ap_uint<24>)gen175_pipex_var.concat((ap_uint<23>)gen175_pipex_var.concat((ap_uint<22>)gen175_pipex_var.concat((ap_uint<21>)gen175_pipex_var.concat((ap_uint<20>)gen175_pipex_var.concat((ap_uint<19>)gen175_pipex_var.concat((ap_uint<18>)gen175_pipex_var.concat((ap_uint<17>)gen175_pipex_var.concat((ap_uint<16>)gen175_pipex_var.concat((ap_uint<15>)gen175_pipex_var.concat((ap_uint<14>)gen175_pipex_var.concat((ap_uint<13>)gen174_pipex_var)))))))))))))))))));
		genpstage_EXEC_immediate_B = gen176_pipex_var;
		gen177_pipex_var = genpstage_EXEC_instr_code[31:12].concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_immediate_U = gen177_pipex_var;
		gen178_pipex_var = genpstage_EXEC_instr_code[31].concat((ap_uint<20>)genpstage_EXEC_instr_code[19:12].concat((ap_uint<12>)genpstage_EXEC_instr_code[20].concat((ap_uint<11>)genpstage_EXEC_instr_code[30:21].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen179_pipex_var = gen178_pipex_var[20];
		gen180_pipex_var = gen179_pipex_var.concat((ap_uint<31>)gen179_pipex_var.concat((ap_uint<30>)gen179_pipex_var.concat((ap_uint<29>)gen179_pipex_var.concat((ap_uint<28>)gen179_pipex_var.concat((ap_uint<27>)gen179_pipex_var.concat((ap_uint<26>)gen179_pipex_var.concat((ap_uint<25>)gen179_pipex_var.concat((ap_uint<24>)gen179_pipex_var.concat((ap_uint<23>)gen179_pipex_var.concat((ap_uint<22>)gen179_pipex_var.concat((ap_uint<21>)gen178_pipex_var)))))))))));
		genpstage_EXEC_immediate_J = gen180_pipex_var;
		switch (genpstage_EXEC_opcode) {
			case 55:
				genpstage_EXEC_op1_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 23:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 111:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_J;
				break;
			case 103:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 99:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_B;
				gen181_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(6));
				gen182_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(7));
				gen183_pipex_var = (gen181_pipex_var | gen182_pipex_var);
				gen184_pipex_var = gen183_pipex_var;
				gen229_cyclix_var = gen184_pipex_var;
				if (gen229_cyclix_var) {
					genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(5);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 35:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_S;
				break;
			case 19:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen185_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_instr_code[24:20]);
						genpstage_EXEC_immediate = gen185_pipex_var;
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen186_pipex_var = genpstage_EXEC_instr_code[30];
						gen230_cyclix_var = gen186_pipex_var;
						if (gen230_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen187_pipex_var = ap_uint<1>(0);
						gen187_pipex_var = (gen187_pipex_var || gen186_pipex_var);
						gen187_pipex_var = !gen187_pipex_var;
						gen231_cyclix_var = gen187_pipex_var;
						if (gen231_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen188_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_instr_code[24:20]);
						genpstage_EXEC_immediate = gen188_pipex_var;
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen189_pipex_var = genpstage_EXEC_instr_code[30];
						gen232_cyclix_var = gen189_pipex_var;
						if (gen232_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						}
						gen190_pipex_var = ap_uint<1>(0);
						gen190_pipex_var = (gen190_pipex_var || gen189_pipex_var);
						gen190_pipex_var = !gen190_pipex_var;
						gen233_cyclix_var = gen190_pipex_var;
						if (gen233_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen191_pipex_var = genpstage_EXEC_instr_code[30];
						gen234_cyclix_var = gen191_pipex_var;
						if (gen234_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen192_pipex_var = ap_uint<1>(0);
						gen192_pipex_var = (gen192_pipex_var || gen191_pipex_var);
						gen192_pipex_var = !gen192_pipex_var;
						gen235_cyclix_var = gen192_pipex_var;
						if (gen235_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 15:
				genpstage_EXEC_fencereq = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen193_pipex_var = genpstage_EXEC_instr_code[20];
						gen236_cyclix_var = gen193_pipex_var;
						if (gen236_cyclix_var) {
							genpstage_EXEC_ebreakreq = ap_uint<32>(1);
						}
						gen194_pipex_var = ap_uint<1>(0);
						gen194_pipex_var = (gen194_pipex_var || gen193_pipex_var);
						gen194_pipex_var = !gen194_pipex_var;
						gen237_cyclix_var = gen194_pipex_var;
						if (gen237_cyclix_var) {
							genpstage_EXEC_ecallreq = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen195_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen195_pipex_var;
						break;
					case 6:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen196_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen196_pipex_var;
						break;
					case 7:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen197_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen197_pipex_var;
						break;
				}
				break;
		}
		gen198_pipex_var = genpstage_EXEC_mem_req;
		gen238_cyclix_var = gen198_pipex_var;
		if (gen238_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					genpstage_EXEC_load_signext = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					genpstage_EXEC_load_signext = ap_uint<32>(1);
					break;
				case 2:
					genpstage_EXEC_mem_be = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
			}
		}
		gen199_pipex_var = (genpstage_EXEC_instr_code == ap_uint<32>(807403635));
		gen200_pipex_var = gen199_pipex_var;
		gen239_cyclix_var = gen200_pipex_var;
		if (gen239_cyclix_var) {
			genpstage_EXEC_mret_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
			genpstage_EXEC_jump_src = ap_uint<32>(0);
			genpstage_EXEC_immediate = genpsticky_glbl_MRETADDR;
		}
		gen201_pipex_var = (genpstage_EXEC_rd_addr == ap_uint<32>(0));
		gen202_pipex_var = gen201_pipex_var;
		gen240_cyclix_var = gen202_pipex_var;
		if (gen240_cyclix_var) {
			genpstage_EXEC_rd_req = ap_uint<32>(0);
		}
		gen203_pipex_var = genpsticky_glbl_regfile_buf[1];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[2];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[3];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[4];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[5];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[6];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[7];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[8];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[9];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[10];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[11];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[12];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[13];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[14];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[15];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[16];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[17];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[18];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[19];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[20];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[21];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[22];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[23];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[24];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[25];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[26];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[27];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[28];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[29];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[30];
		gen203_pipex_var = genpsticky_glbl_regfile_buf[31];
		genpstage_EXEC_rs1_rdata = gen203_pipex_var[genpstage_EXEC_rs1_addr];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[1];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[2];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[3];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[4];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[5];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[6];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[7];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[8];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[9];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[10];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[11];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[12];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[13];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[14];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[15];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[16];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[17];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[18];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[19];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[20];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[21];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[22];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[23];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[24];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[25];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[26];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[27];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[28];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[29];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[30];
		gen204_pipex_var = genpsticky_glbl_regfile_buf[31];
		genpstage_EXEC_rs2_rdata = gen204_pipex_var[genpstage_EXEC_rs2_addr];
		gen205_pipex_var = (genpstage_EXEC_rs1_addr == ap_uint<32>(0));
		gen206_pipex_var = gen205_pipex_var;
		gen241_cyclix_var = gen206_pipex_var;
		if (gen241_cyclix_var) {
			genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
		}
		gen207_pipex_var = (genpstage_EXEC_rs2_addr == ap_uint<32>(0));
		gen208_pipex_var = gen207_pipex_var;
		gen242_cyclix_var = gen208_pipex_var;
		if (gen242_cyclix_var) {
			genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
		}
		gen209_pipex_var = genpstage_EXEC_csrreq;
		gen243_cyclix_var = gen209_pipex_var;
		if (gen243_cyclix_var) {
			genpstage_EXEC_csr_rdata = genpsticky_glbl_CSR_MCAUSE;
		}
		gen210_pipex_var = genpstage_MEMWB_genctrl_working;
		gen211_pipex_var = genpstage_MEMWB_rd_req;
		gen212_pipex_var = (gen210_pipex_var & gen211_pipex_var);
		gen213_pipex_var = gen212_pipex_var;
		gen244_cyclix_var = gen213_pipex_var;
		if (gen244_cyclix_var) {
			gen214_pipex_var = genpstage_EXEC_rs1_req;
			gen245_cyclix_var = gen214_pipex_var;
			if (gen245_cyclix_var) {
				gen215_pipex_var = genpstage_MEMWB_rd_addr;
				gen216_pipex_var = (gen215_pipex_var == genpstage_EXEC_rs1_addr);
				gen217_pipex_var = gen216_pipex_var;
				gen246_cyclix_var = gen217_pipex_var;
				if (gen246_cyclix_var) {
					gen247_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen247_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
			gen218_pipex_var = genpstage_EXEC_rs2_req;
			gen248_cyclix_var = gen218_pipex_var;
			if (gen248_cyclix_var) {
				gen219_pipex_var = genpstage_MEMWB_rd_addr;
				gen220_pipex_var = (gen219_pipex_var == genpstage_EXEC_rs2_addr);
				gen221_pipex_var = gen220_pipex_var;
				gen249_cyclix_var = gen221_pipex_var;
				if (gen249_cyclix_var) {
					gen250_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen250_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		genpstage_EXEC_alu_op1 = genpstage_EXEC_rs1_rdata;
		switch (genpstage_EXEC_op1_source) {
			case 1:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_curinstr_addr;
				break;
		}
		genpstage_EXEC_alu_op2 = genpstage_EXEC_rs2_rdata;
		switch (genpstage_EXEC_op2_source) {
			case 1:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_csr_rdata;
				break;
		}
		gen222_pipex_var = genpstage_EXEC_alu_unsigned;
		gen251_cyclix_var = gen222_pipex_var;
		if (gen251_cyclix_var) {
			gen223_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen223_pipex_var;
			gen224_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen224_pipex_var;
		}
		gen225_pipex_var = ap_uint<1>(0);
		gen225_pipex_var = (gen225_pipex_var || gen222_pipex_var);
		gen225_pipex_var = !gen225_pipex_var;
		gen252_cyclix_var = gen225_pipex_var;
		if (gen252_cyclix_var) {
			gen226_pipex_var = genpstage_EXEC_alu_op1[31];
			gen227_pipex_var = gen226_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen227_pipex_var;
			gen228_pipex_var = genpstage_EXEC_alu_op2[31];
			gen229_pipex_var = gen228_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen229_pipex_var;
		}
		gen230_pipex_var = genpsticky_glbl_MIRQEN;
		gen253_cyclix_var = gen230_pipex_var;
		if (gen253_cyclix_var) {
			gen231_pipex_var = ~genpstage_EXEC_irq_recv;
			gen232_pipex_var = gen231_pipex_var;
			gen254_cyclix_var = gen232_pipex_var;
			if (gen254_cyclix_var) {
				gen255_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen255_cyclix_var) {
					gen256_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_irq_mcause);
					gen233_pipex_var = gen256_cyclix_var;
				}
				genpstage_EXEC_irq_recv = gen233_pipex_var;
				gen257_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen257_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen233_pipex_var;
				}
				genpstage_EXEC_irq_mcause = genpstage_EXEC_irq_mcause;
				gen258_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen258_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_irq_mcause;
				}
			}
			gen234_pipex_var = genpstage_EXEC_irq_recv;
			gen259_cyclix_var = gen234_pipex_var;
			if (gen259_cyclix_var) {
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
				genpstage_EXEC_jump_src = ap_uint<32>(0);
				genpstage_EXEC_rs1_req = ap_uint<32>(0);
				genpstage_EXEC_rs2_req = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(0);
				genpstage_EXEC_immediate = ap_uint<32>(128);
				genpstage_EXEC_fencereq = ap_uint<32>(0);
				genpstage_EXEC_ecallreq = ap_uint<32>(0);
				genpstage_EXEC_ebreakreq = ap_uint<32>(0);
				genpstage_EXEC_csrreq = ap_uint<32>(0);
				genpstage_EXEC_alu_req = ap_uint<32>(0);
				genpstage_EXEC_mem_req = ap_uint<32>(0);
				gen260_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen260_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(0);
				}
				gen261_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen261_cyclix_var) {
					genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_irq_mcause;
				}
				gen262_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen262_cyclix_var) {
					genpsticky_glbl_MRETADDR = genpstage_EXEC_curinstr_addr;
				}
			}
		}
		gen235_pipex_var = genpstage_EXEC_mret_req;
		gen263_cyclix_var = gen235_pipex_var;
		if (gen263_cyclix_var) {
			gen264_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen264_cyclix_var) {
				genpsticky_glbl_MIRQEN = ap_uint<32>(1);
			}
		}
		genpstage_EXEC_alu_result_wide = genpstage_EXEC_alu_op1_wide;
		gen236_pipex_var = genpstage_EXEC_alu_req;
		gen265_cyclix_var = gen236_pipex_var;
		if (gen265_cyclix_var) {
			switch (genpstage_EXEC_alu_opcode) {
				case 0:
					gen237_pipex_var = (genpstage_EXEC_alu_op1_wide + genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen237_pipex_var;
					break;
				case 1:
					gen238_pipex_var = (genpstage_EXEC_alu_op1_wide - genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen238_pipex_var;
					break;
				case 2:
					gen239_pipex_var = (genpstage_EXEC_alu_op1_wide & genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen239_pipex_var;
					break;
				case 3:
					gen240_pipex_var = (genpstage_EXEC_alu_op1_wide | genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen240_pipex_var;
					break;
				case 4:
					gen241_pipex_var = (genpstage_EXEC_alu_op1_wide << genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen241_pipex_var;
					break;
				case 5:
					gen242_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1_wide[31:0]);
					gen243_pipex_var = (gen242_pipex_var >> genpstage_EXEC_alu_op2_wide[4:0]);
					genpstage_EXEC_alu_result_wide = gen243_pipex_var;
					break;
				case 6:
					gen244_pipex_var = genpstage_EXEC_alu_op1_wide[31:0];
					gen245_pipex_var = gen244_pipex_var[31];
					gen246_pipex_var = gen245_pipex_var.concat((ap_uint<63>)gen245_pipex_var.concat((ap_uint<62>)gen245_pipex_var.concat((ap_uint<61>)gen245_pipex_var.concat((ap_uint<60>)gen245_pipex_var.concat((ap_uint<59>)gen245_pipex_var.concat((ap_uint<58>)gen245_pipex_var.concat((ap_uint<57>)gen245_pipex_var.concat((ap_uint<56>)gen245_pipex_var.concat((ap_uint<55>)gen245_pipex_var.concat((ap_uint<54>)gen245_pipex_var.concat((ap_uint<53>)gen245_pipex_var.concat((ap_uint<52>)gen245_pipex_var.concat((ap_uint<51>)gen245_pipex_var.concat((ap_uint<50>)gen245_pipex_var.concat((ap_uint<49>)gen245_pipex_var.concat((ap_uint<48>)gen245_pipex_var.concat((ap_uint<47>)gen245_pipex_var.concat((ap_uint<46>)gen245_pipex_var.concat((ap_uint<45>)gen245_pipex_var.concat((ap_uint<44>)gen245_pipex_var.concat((ap_uint<43>)gen245_pipex_var.concat((ap_uint<42>)gen245_pipex_var.concat((ap_uint<41>)gen245_pipex_var.concat((ap_uint<40>)gen245_pipex_var.concat((ap_uint<39>)gen245_pipex_var.concat((ap_uint<38>)gen245_pipex_var.concat((ap_uint<37>)gen245_pipex_var.concat((ap_uint<36>)gen245_pipex_var.concat((ap_uint<35>)gen245_pipex_var.concat((ap_uint<34>)gen245_pipex_var.concat((ap_uint<33>)gen245_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1_wide[31:0]))))))))))))))))))))))))))))))));
					gen247_pipex_var = (gen246_pipex_var >> genpstage_EXEC_alu_op2_wide[4:0]);
					genpstage_EXEC_alu_result_wide = gen247_pipex_var;
					break;
				case 7:
					gen248_pipex_var = (genpstage_EXEC_alu_op1_wide ^ genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen248_pipex_var;
					break;
				case 8:
					gen249_pipex_var = ~genpstage_EXEC_alu_op2_wide;
					gen250_pipex_var = (genpstage_EXEC_alu_op1_wide & gen249_pipex_var);
					genpstage_EXEC_alu_result_wide = gen250_pipex_var;
					break;
			}
			genpstage_EXEC_alu_result = genpstage_EXEC_alu_result_wide[31:0];
			genpstage_EXEC_alu_CF = genpstage_EXEC_alu_result_wide[32];
			genpstage_EXEC_alu_SF = genpstage_EXEC_alu_result_wide[31];
			gen251_pipex_var = |genpstage_EXEC_alu_result;
			gen252_pipex_var = ~gen251_pipex_var;
			genpstage_EXEC_alu_ZF = gen252_pipex_var;
			gen253_pipex_var = ~genpstage_EXEC_alu_op1[31];
			gen254_pipex_var = ~genpstage_EXEC_alu_op2[31];
			gen255_pipex_var = (gen253_pipex_var & gen254_pipex_var);
			gen256_pipex_var = (gen255_pipex_var & genpstage_EXEC_alu_result[31]);
			gen257_pipex_var = ~genpstage_EXEC_alu_result[31];
			gen258_pipex_var = (genpstage_EXEC_alu_op1[31] & genpstage_EXEC_alu_op2[31]);
			gen259_pipex_var = (gen258_pipex_var & gen257_pipex_var);
			gen260_pipex_var = (gen256_pipex_var | gen259_pipex_var);
			genpstage_EXEC_alu_OF = gen260_pipex_var;
			gen261_pipex_var = genpstage_EXEC_alu_unsigned;
			gen266_cyclix_var = gen261_pipex_var;
			if (gen266_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_CF;
			}
			gen262_pipex_var = ap_uint<1>(0);
			gen262_pipex_var = (gen262_pipex_var || gen261_pipex_var);
			gen262_pipex_var = !gen262_pipex_var;
			gen267_cyclix_var = gen262_pipex_var;
			if (gen267_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_OF;
			}
		}
		switch (genpstage_EXEC_rd_source) {
			case 0:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_immediate;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_result;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_CF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_OF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_nextinstr_addr;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_csr_rdata;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
		}
		gen263_pipex_var = (genpstage_EXEC_curinstr_addr + genpstage_EXEC_immediate);
		genpstage_EXEC_curinstraddr_imm = gen263_pipex_var;
		switch (genpstage_EXEC_jump_src) {
			case 0:
				genpstage_EXEC_jump_vector = genpstage_EXEC_immediate;
				break;
			case 1:
				genpstage_EXEC_jump_vector = genpstage_EXEC_alu_result;
				break;
		}
		gen264_pipex_var = genpstage_EXEC_jump_req_cond;
		gen268_cyclix_var = gen264_pipex_var;
		if (gen268_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					gen265_pipex_var = genpstage_EXEC_alu_ZF;
					gen269_cyclix_var = gen265_pipex_var;
					if (gen269_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 1:
					gen266_pipex_var = ~genpstage_EXEC_alu_ZF;
					gen267_pipex_var = gen266_pipex_var;
					gen270_cyclix_var = gen267_pipex_var;
					if (gen270_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 4:
					gen268_pipex_var = genpstage_EXEC_alu_CF;
					gen271_cyclix_var = gen268_pipex_var;
					if (gen271_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 5:
					gen269_pipex_var = ~genpstage_EXEC_alu_CF;
					gen270_pipex_var = gen269_pipex_var;
					gen272_cyclix_var = gen270_pipex_var;
					if (gen272_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 6:
					gen271_pipex_var = genpstage_EXEC_alu_CF;
					gen273_cyclix_var = gen271_pipex_var;
					if (gen273_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 7:
					gen272_pipex_var = ~genpstage_EXEC_alu_CF;
					gen273_pipex_var = gen272_pipex_var;
					gen274_cyclix_var = gen273_pipex_var;
					if (gen274_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_mem_addr = genpstage_EXEC_alu_result;
		genpstage_EXEC_mem_wdata = genpstage_EXEC_rs2_rdata;
		gen275_cyclix_var = ~genpstage_MEMWB_genctrl_rdy;
		gen276_cyclix_var = gen275_cyclix_var;
		if (gen276_cyclix_var) {
			gen277_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen277_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		gen278_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen278_cyclix_var) {
			genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		}
		gen279_cyclix_var = ap_uint<1>(0);
		gen279_cyclix_var = (gen279_cyclix_var || gen278_cyclix_var);
		gen279_cyclix_var = !gen279_cyclix_var;
		if (gen279_cyclix_var) {
			genpstage_EXEC_genctrl_finish = genpstage_EXEC_genctrl_occupied;
			genpstage_EXEC_genctrl_succ = genpstage_EXEC_genctrl_active;
		}
		gen280_cyclix_var = genpstage_EXEC_genctrl_finish;
		if (gen280_cyclix_var) {
			gen281_cyclix_var = genpstage_EXEC_genctrl_succ;
			if (gen281_cyclix_var) {
				gen282_cyclix_var = genpstage_MEMWB_genctrl_rdy;
				if (gen282_cyclix_var) {
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_rd_wdata;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_rd_req;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_rd_addr;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_jump_req;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_jump_vector;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_mem_req;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_mem_addr;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_mem_be;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_mem_wdata;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_mem_cmd;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_load_signext;
					genpstage_MEMWB_TRX_BUF = genpstage_EXEC_rd_source;
					genpstage_MEMWB_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(1);
					genpstage_MEMWB_TRX_BUF_COUNTER_FULL = ap_uint<32>(1);
					genpstage_MEMWB_TRX_BUF_COUNTER = (genpstage_MEMWB_TRX_BUF_COUNTER + ap_uint<32>(1));
				}
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen283_cyclix_var = ~genpstage_EXEC_TRX_BUF_COUNTER_FULL;
		genpstage_EXEC_genctrl_rdy = gen283_cyclix_var;
		genpstage_EXEC_genctrl_working = (genpstage_EXEC_genctrl_succ | genpstage_EXEC_genctrl_stalled_glbl);
		genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_working = ap_uint<32>(0);
		gen284_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen284_cyclix_var) {
			genpstage_IFETCH_genctrl_new = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
		}
		gen285_cyclix_var = ap_uint<1>(0);
		gen285_cyclix_var = (gen285_cyclix_var || gen284_cyclix_var);
		gen285_cyclix_var = !gen285_cyclix_var;
		if (gen285_cyclix_var) {
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
			genpstage_IFETCH_genctrl_new = genpstage_IFETCH_genctrl_active;
		}
		genpstage_IFETCH_genctrl_occupied = genpstage_IFETCH_genctrl_active;
		genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = (genpstage_IFETCH_genpctrl_flushreq | genpstage_EXEC_genpctrl_flushreq);
		gen286_cyclix_var = genpstage_IFETCH_genctrl_occupied;
		if (gen286_cyclix_var) {
			gen287_cyclix_var = genpstage_IFETCH_genctrl_new;
			if (gen287_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
			}
			genpstage_IFETCH_instr_req_done = genpstage_IFETCH_TRX_BUF[0].instr_req_done;
			gen288_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen288_cyclix_var) {
				gen289_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen290_cyclix_var = gen289_cyclix_var;
				if (gen290_cyclix_var) {
					gen291_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen292_cyclix_var = gen291_cyclix_var;
					if (gen292_cyclix_var) {
						gen293_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen309_pipex_mcopipe_rdata);
						gen294_cyclix_var = gen293_cyclix_var;
						if (gen294_cyclix_var) {
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(1);
							genpstage_IFETCH_TRX_BUF = gen309_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen295_cyclix_var = genpstage_IFETCH_genpctrl_flushreq;
			if (gen295_cyclix_var) {
			}
		}
		gen149_pipex_succbuf = genpsticky_glbl_jump_req_cmd;
		gen151_pipex_succbuf = genpsticky_glbl_pc;
		genpstage_IFETCH_curinstr_addr = genpsticky_glbl_pc;
		gen158_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen296_cyclix_var = gen158_pipex_var;
		if (gen296_cyclix_var) {
			genpstage_IFETCH_curinstr_addr = genpsticky_glbl_jump_vector_cmd;
		}
		gen148_pipex_succreq = ap_uint<32>(1);
		gen149_pipex_succbuf = ap_uint<32>(0);
		gen159_pipex_var = (genpstage_IFETCH_curinstr_addr + ap_uint<32>(4));
		genpstage_IFETCH_nextinstr_addr = gen159_pipex_var;
		gen150_pipex_succreq = ap_uint<32>(1);
		gen151_pipex_succbuf = genpstage_IFETCH_nextinstr_addr;
		genpstage_IFETCH_instr_busreq = genpstage_IFETCH_curinstr_addr;
		genpstage_IFETCH_instr_busreq = ap_uint<32>(15);
		genpstage_IFETCH_instr_busreq = ap_uint<32>(0);
		gen160_pipex_var = ~genpstage_IFETCH_instr_req_done;
		gen161_pipex_var = gen160_pipex_var;
		gen297_cyclix_var = gen161_pipex_var;
		if (gen297_cyclix_var) {
			gen298_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen298_cyclix_var) {
				gen299_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen300_cyclix_var = gen299_cyclix_var;
				if (gen300_cyclix_var) {
					gen310_pipex_req_struct = ap_uint<1>(0);
					gen310_pipex_req_struct = genpstage_IFETCH_instr_busreq;
					gen301_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen310_pipex_req_struct);
					gen302_cyclix_var = gen301_cyclix_var;
					if (gen302_cyclix_var) {
						gen162_pipex_var = ap_uint<32>(1);
						gen303_cyclix_var = !ap_uint<1>(0);
						genpstage_IFETCH_TRX_BUF = gen303_cyclix_var;
						genpstage_IFETCH_TRX_BUF = genmcopipe_instr_mem_wr_ptr;
						genpstage_IFETCH_TRX_BUF = ap_uint<1>(0);
						gen304_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
						if (gen304_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_IFETCH_instr_req_done = gen162_pipex_var;
			gen305_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen305_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = gen162_pipex_var;
			}
		}
		gen163_pipex_var = ~genpstage_IFETCH_instr_req_done;
		gen164_pipex_var = gen163_pipex_var;
		gen306_cyclix_var = gen164_pipex_var;
		if (gen306_cyclix_var) {
			gen307_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen307_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		gen308_cyclix_var = ~genpstage_EXEC_genctrl_rdy;
		gen309_cyclix_var = gen308_cyclix_var;
		if (gen309_cyclix_var) {
			gen310_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen310_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		gen311_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen311_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		}
		gen312_cyclix_var = ap_uint<1>(0);
		gen312_cyclix_var = (gen312_cyclix_var || gen311_cyclix_var);
		gen312_cyclix_var = !gen312_cyclix_var;
		if (gen312_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = genpstage_IFETCH_genctrl_occupied;
			genpstage_IFETCH_genctrl_succ = genpstage_IFETCH_genctrl_active;
		}
		gen313_cyclix_var = genpstage_IFETCH_genctrl_succ;
		if (gen313_cyclix_var) {
			gen314_cyclix_var = gen148_pipex_succreq;
			if (gen314_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen149_pipex_succbuf;
			}
			gen315_cyclix_var = gen150_pipex_succreq;
			if (gen315_cyclix_var) {
				genpsticky_glbl_pc = gen151_pipex_succbuf;
			}
		}
		gen316_cyclix_var = genpstage_IFETCH_genctrl_finish;
		if (gen316_cyclix_var) {
			gen317_cyclix_var = genpstage_IFETCH_genctrl_succ;
			if (gen317_cyclix_var) {
				gen318_cyclix_var = genpstage_EXEC_genctrl_rdy;
				if (gen318_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_IFETCH_curinstr_addr;
					genpstage_EXEC_TRX_BUF = genpstage_IFETCH_nextinstr_addr;
					genpstage_EXEC_TRX_BUF = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem;
					genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER + ap_uint<32>(1));
				}
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER = (genpstage_IFETCH_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen319_cyclix_var = ~genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
		genpstage_IFETCH_genctrl_rdy = gen319_cyclix_var;
		genpstage_IFETCH_genctrl_working = (genpstage_IFETCH_genctrl_succ | genpstage_IFETCH_genctrl_stalled_glbl);
		gen320_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen320_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen321_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen322_cyclix_var = gen321_cyclix_var;
			if (gen322_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen323_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen323_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen324_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen325_cyclix_var = gen324_cyclix_var;
			if (gen325_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen326_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen326_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen327_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen328_cyclix_var = gen327_cyclix_var;
			if (gen328_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen329_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen329_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen330_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen331_cyclix_var = gen330_cyclix_var;
			if (gen331_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
	}
}
