// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2021-06-10
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include <ap_int.h>
#include <hls_stream.h>
#include "riscv_2stage.hpp"

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_instr_mem_struct;

typedef struct {
	ap_uint<1> instr_req_done;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_IFETCH_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_data_mem_struct;

typedef struct {
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	ap_uint<1> irq_recv;
	ap_uint<8> irq_mcause;
	ap_uint<1> data_req_done;
	genmcopipe_handle_data_mem_struct genmcopipe_handle_data_mem;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_EXEC_TRX_BUF_STRUCT;

ap_uint<32> genpsticky_glbl_pc;
ap_uint<32> genpsticky_glbl_regfile [32];
ap_uint<1> genpsticky_glbl_jump_req_cmd;
ap_uint<32> genpsticky_glbl_jump_vector_cmd;
ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
ap_uint<1> genpsticky_glbl_MIRQEN;
ap_uint<32> genpsticky_glbl_MRETADDR;
ap_uint<1> genmcopipe_instr_mem_wr_done;
ap_uint<1> genmcopipe_instr_mem_rd_done;
ap_uint<1> genmcopipe_instr_mem_full_flag;
ap_uint<1> genmcopipe_instr_mem_empty_flag;
ap_uint<1> genmcopipe_instr_mem_wr_ptr;
ap_uint<1> genmcopipe_instr_mem_rd_ptr;
ap_uint<1> genmcopipe_data_mem_wr_done;
ap_uint<1> genmcopipe_data_mem_rd_done;
ap_uint<1> genmcopipe_data_mem_full_flag;
ap_uint<1> genmcopipe_data_mem_empty_flag;
ap_uint<1> genmcopipe_data_mem_wr_ptr;
ap_uint<1> genmcopipe_data_mem_rd_ptr;
genpstage_IFETCH_TRX_BUF_STRUCT genpstage_IFETCH_TRX_BUF [0:0];
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_IFETCH_genctrl_stalled_glbl;
genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_BUF [0:0];
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_EXEC_genctrl_stalled_glbl;

void riscv_2stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req) {


	ap_uint<32> genpsticky_glbl_pc_buf;
	ap_uint<32> genpsticky_glbl_regfile_buf [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd_buf;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd_buf;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE_buf;
	ap_uint<1> genpsticky_glbl_MIRQEN_buf;
	ap_uint<32> genpsticky_glbl_MRETADDR_buf;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<1> genpstage_IFETCH_genpctrl_flushreq;
	ap_uint<1> genpstage_IFETCH_genctrl_active;
	ap_uint<1> genpstage_IFETCH_genctrl_working;
	ap_uint<1> genpstage_IFETCH_genctrl_succ;
	ap_uint<1> genpstage_IFETCH_genctrl_occupied;
	ap_uint<1> genpstage_IFETCH_genctrl_rdy;
	ap_uint<1> genpstage_IFETCH_genctrl_new;
	ap_uint<1> genpstage_IFETCH_genctrl_finish;
	ap_uint<1> gen136_pipex_succreq;
	ap_uint<1> gen137_pipex_succbuf;
	ap_uint<1> gen138_pipex_succreq;
	ap_uint<32> gen139_pipex_succbuf;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	ap_uint<1> genpstage_EXEC_genctrl_active;
	ap_uint<1> genpstage_EXEC_genctrl_working;
	ap_uint<1> genpstage_EXEC_genctrl_succ;
	ap_uint<1> genpstage_EXEC_genctrl_occupied;
	ap_uint<1> genpstage_EXEC_genctrl_rdy;
	ap_uint<1> genpstage_EXEC_genctrl_new;
	ap_uint<1> genpstage_EXEC_genctrl_finish;
	ap_uint<1> gen140_pipex_succreq;
	ap_uint<1> gen141_pipex_succbuf;
	ap_uint<1> gen142_pipex_succreq;
	ap_uint<32> gen143_pipex_succbuf;
	ap_uint<1> gen144_pipex_succreq;
	ap_uint<32> gen145_pipex_succbuf [32];
	ap_uint<1> gen146_pipex_var;
	ap_uint<33> gen147_pipex_var;
	ap_uint<1> gen148_pipex_var;
	ap_uint<1> gen149_pipex_var;
	ap_uint<1> gen150_pipex_var;
	ap_uint<1> gen151_pipex_var;
	ap_uint<1> gen152_pipex_var;
	ap_uint<1> gen153_pipex_var;
	ap_uint<1> gen154_pipex_var;
	ap_uint<1> gen155_pipex_var;
	ap_uint<32> gen156_pipex_var;
	ap_uint<1> gen157_pipex_var;
	ap_uint<32> gen158_pipex_var;
	ap_uint<12> gen159_pipex_var;
	ap_uint<1> gen160_pipex_var;
	ap_uint<32> gen161_pipex_var;
	ap_uint<13> gen162_pipex_var;
	ap_uint<1> gen163_pipex_var;
	ap_uint<32> gen164_pipex_var;
	ap_uint<32> gen165_pipex_var;
	ap_uint<21> gen166_pipex_var;
	ap_uint<1> gen167_pipex_var;
	ap_uint<32> gen168_pipex_var;
	ap_uint<1> gen169_pipex_var;
	ap_uint<1> gen170_pipex_var;
	ap_uint<1> gen171_pipex_var;
	ap_uint<1> gen172_pipex_var;
	ap_uint<32> gen173_pipex_var;
	ap_uint<1> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<32> gen176_pipex_var;
	ap_uint<1> gen177_pipex_var;
	ap_uint<1> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<1> gen180_pipex_var;
	ap_uint<1> gen181_pipex_var;
	ap_uint<1> gen182_pipex_var;
	ap_uint<32> gen183_pipex_var;
	ap_uint<32> gen184_pipex_var;
	ap_uint<32> gen185_pipex_var;
	ap_uint<1> gen186_pipex_var;
	ap_uint<1> gen187_pipex_var;
	ap_uint<1> gen188_pipex_var;
	ap_uint<1> gen189_pipex_var;
	ap_uint<1> gen190_pipex_var;
	ap_uint<32> gen191_pipex_var [32];
	ap_uint<32> gen192_pipex_var [32];
	ap_uint<1> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<1> gen195_pipex_var;
	ap_uint<1> gen196_pipex_var;
	ap_uint<1> gen197_pipex_var;
	ap_uint<1> gen198_pipex_var;
	ap_uint<33> gen199_pipex_var;
	ap_uint<33> gen200_pipex_var;
	ap_uint<1> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<33> gen203_pipex_var;
	ap_uint<1> gen204_pipex_var;
	ap_uint<33> gen205_pipex_var;
	ap_uint<1> gen206_pipex_var;
	ap_uint<1> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<1> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<1> gen211_pipex_var;
	ap_uint<1> gen212_pipex_var;
	ap_uint<34> gen213_pipex_var;
	ap_uint<34> gen214_pipex_var;
	ap_uint<33> gen215_pipex_var;
	ap_uint<33> gen216_pipex_var;
	ap_uint<33> gen217_pipex_var;
	ap_uint<64> gen218_pipex_var;
	ap_uint<64> gen219_pipex_var;
	ap_uint<32> gen220_pipex_var;
	ap_uint<1> gen221_pipex_var;
	ap_uint<64> gen222_pipex_var;
	ap_uint<64> gen223_pipex_var;
	ap_uint<33> gen224_pipex_var;
	ap_uint<33> gen225_pipex_var;
	ap_uint<33> gen226_pipex_var;
	ap_uint<1> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<1> gen235_pipex_var;
	ap_uint<1> gen236_pipex_var;
	ap_uint<1> gen237_pipex_var;
	ap_uint<1> gen238_pipex_var;
	ap_uint<33> gen239_pipex_var;
	ap_uint<1> gen240_pipex_var;
	ap_uint<1> gen241_pipex_var;
	ap_uint<1> gen242_pipex_var;
	ap_uint<1> gen243_pipex_var;
	ap_uint<1> gen244_pipex_var;
	ap_uint<1> gen245_pipex_var;
	ap_uint<1> gen246_pipex_var;
	ap_uint<1> gen247_pipex_var;
	ap_uint<1> gen248_pipex_var;
	ap_uint<1> gen249_pipex_var;
	ap_uint<1> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<1> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<1> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<1> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<8> gen266_pipex_var;
	ap_uint<1> gen267_pipex_var;
	ap_uint<32> gen268_pipex_var;
	ap_uint<1> gen269_pipex_var;
	ap_uint<32> gen270_pipex_var;
	ap_uint<1> gen271_pipex_var;
	ap_uint<1> gen272_pipex_var;
	ap_uint<1> gen273_pipex_var;
	ap_uint<16> gen274_pipex_var;
	ap_uint<1> gen275_pipex_var;
	ap_uint<32> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<32> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<1> gen280_pipex_var;
	ap_uint<1> gen281_pipex_var;
	ap_uint<32> genpstage_IFETCH_curinstr_addr;
	ap_uint<32> genpstage_IFETCH_nextinstr_addr;
	riscv_2stage_busreq_mem_struct genpstage_IFETCH_instr_busreq;
	ap_uint<1> genpstage_IFETCH_instr_req_done;
	ap_uint<32> genpstage_EXEC_instr_code;
	ap_uint<7> genpstage_EXEC_opcode;
	ap_uint<1> genpstage_EXEC_alu_unsigned;
	ap_uint<5> genpstage_EXEC_rs1_addr;
	ap_uint<5> genpstage_EXEC_rs2_addr;
	ap_uint<5> genpstage_EXEC_rd_addr;
	ap_uint<3> genpstage_EXEC_funct3;
	ap_uint<7> genpstage_EXEC_funct7;
	ap_uint<5> genpstage_EXEC_shamt;
	ap_uint<4> genpstage_EXEC_pred;
	ap_uint<4> genpstage_EXEC_succ;
	ap_uint<12> genpstage_EXEC_csrnum;
	ap_uint<5> genpstage_EXEC_zimm;
	ap_uint<32> genpstage_EXEC_immediate_I;
	ap_uint<32> genpstage_EXEC_immediate_S;
	ap_uint<32> genpstage_EXEC_immediate_B;
	ap_uint<32> genpstage_EXEC_immediate_U;
	ap_uint<32> genpstage_EXEC_immediate_J;
	ap_uint<2> genpstage_EXEC_op1_source;
	ap_uint<1> genpstage_EXEC_rd_req;
	ap_uint<3> genpstage_EXEC_rd_source;
	ap_uint<32> genpstage_EXEC_immediate;
	ap_uint<2> genpstage_EXEC_op2_source;
	ap_uint<1> genpstage_EXEC_alu_req;
	ap_uint<4> genpstage_EXEC_alu_opcode;
	ap_uint<1> genpstage_EXEC_jump_req;
	ap_uint<1> genpstage_EXEC_jump_src;
	ap_uint<1> genpstage_EXEC_rs1_req;
	ap_uint<1> genpstage_EXEC_rs2_req;
	ap_uint<1> genpstage_EXEC_jump_req_cond;
	ap_uint<1> genpstage_EXEC_mem_req;
	ap_uint<1> genpstage_EXEC_mem_cmd;
	ap_uint<1> genpstage_EXEC_fencereq;
	ap_uint<1> genpstage_EXEC_ebreakreq;
	ap_uint<1> genpstage_EXEC_ecallreq;
	ap_uint<1> genpstage_EXEC_csrreq;
	ap_uint<4> genpstage_EXEC_mem_be;
	ap_uint<1> genpstage_EXEC_load_signext;
	ap_uint<1> genpstage_EXEC_mret_req;
	ap_uint<32> genpstage_EXEC_rs1_rdata;
	ap_uint<32> genpstage_EXEC_rs2_rdata;
	ap_uint<32> genpstage_EXEC_csr_rdata;
	ap_uint<32> genpstage_EXEC_alu_op1;
	ap_uint<32> genpstage_EXEC_alu_op2;
	ap_uint<33> genpstage_EXEC_alu_op1_wide;
	ap_uint<33> genpstage_EXEC_alu_op2_wide;
	ap_uint<8> genpstage_EXEC_irq_mcause;
	ap_uint<1> genpstage_EXEC_irq_recv;
	ap_uint<33> genpstage_EXEC_alu_result_wide;
	ap_uint<32> genpstage_EXEC_alu_result;
	ap_uint<1> genpstage_EXEC_alu_CF;
	ap_uint<1> genpstage_EXEC_alu_SF;
	ap_uint<1> genpstage_EXEC_alu_ZF;
	ap_uint<1> genpstage_EXEC_alu_OF;
	ap_uint<1> genpstage_EXEC_alu_overflow;
	ap_uint<32> genpstage_EXEC_rd_wdata;
	ap_uint<1> genpstage_EXEC_rd_rdy;
	ap_uint<32> genpstage_EXEC_curinstraddr_imm;
	ap_uint<32> genpstage_EXEC_jump_vector;
	ap_uint<32> genpstage_EXEC_mem_addr;
	ap_uint<32> genpstage_EXEC_mem_wdata;
	riscv_2stage_busreq_mem_struct genpstage_EXEC_data_busreq;
	ap_uint<1> genpstage_EXEC_data_req_done;
	ap_uint<32> genpstage_EXEC_mem_rdata;
	ap_uint<32> genpstage_EXEC_curinstr_addr;
	ap_uint<32> genpstage_EXEC_nextinstr_addr;
	ap_uint<32> gen282_pipex_mcopipe_rdata;
	ap_uint<32> gen283_pipex_mcopipe_rdata;
	genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata gen284_pipex_req_struct;
	ap_uint<32> gen285_pipex_mcopipe_rdata;
	genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen286_pipex_req_struct;
	ap_uint<1> gen145_cyclix_var;
	ap_uint<1> gen146_cyclix_var;
	ap_uint<1> gen147_cyclix_var;
	ap_uint<1> gen148_cyclix_var;
	ap_uint<1> gen149_cyclix_var;
	ap_uint<1> gen150_cyclix_var;
	ap_uint<1> gen151_cyclix_var;
	ap_uint<1> gen152_cyclix_var;
	ap_uint<1> gen153_cyclix_var;
	ap_uint<1> gen154_cyclix_var;
	ap_uint<1> gen155_cyclix_var;
	ap_uint<1> gen156_cyclix_var;
	ap_uint<1> gen157_cyclix_var;
	ap_uint<1> gen158_cyclix_var;
	ap_uint<1> gen159_cyclix_var;
	ap_uint<1> gen160_cyclix_var;
	ap_uint<1> gen161_cyclix_var;
	ap_uint<1> gen162_cyclix_var;
	ap_uint<1> gen163_cyclix_var;
	ap_uint<1> gen164_cyclix_var;
	ap_uint<1> gen165_cyclix_var;
	ap_uint<1> gen166_cyclix_var;
	ap_uint<1> gen167_cyclix_var;
	ap_uint<1> gen168_cyclix_var;
	ap_uint<1> gen169_cyclix_var;
	ap_uint<1> gen170_cyclix_var;
	ap_uint<1> gen171_cyclix_var;
	ap_uint<1> gen172_cyclix_var;
	ap_uint<1> gen173_cyclix_var;
	ap_uint<1> gen174_cyclix_var;
	ap_uint<1> gen175_cyclix_var;
	ap_uint<1> gen176_cyclix_var;
	ap_uint<1> gen177_cyclix_var;
	ap_uint<1> gen178_cyclix_var;
	ap_uint<1> gen179_cyclix_var;
	ap_uint<1> gen180_cyclix_var;
	ap_uint<1> gen181_cyclix_var;
	ap_uint<1> gen182_cyclix_var;
	ap_uint<1> gen183_cyclix_var;
	ap_uint<1> gen184_cyclix_var;
	ap_uint<1> gen185_cyclix_var;
	ap_uint<1> gen186_cyclix_var;
	ap_uint<1> gen187_cyclix_var;
	ap_uint<1> gen188_cyclix_var;
	ap_uint<1> gen189_cyclix_var;
	ap_uint<1> gen190_cyclix_var;
	ap_uint<1> gen191_cyclix_var;
	ap_uint<1> gen192_cyclix_var;
	ap_uint<1> gen193_cyclix_var;
	ap_uint<1> gen194_cyclix_var;
	ap_uint<1> gen195_cyclix_var;
	ap_uint<1> gen196_cyclix_var;
	ap_uint<1> gen197_cyclix_var;
	ap_uint<1> gen198_cyclix_var;
	ap_uint<1> gen199_cyclix_var;
	ap_uint<1> gen200_cyclix_var;
	ap_uint<1> gen201_cyclix_var;
	ap_uint<1> gen202_cyclix_var;
	ap_uint<1> gen203_cyclix_var;
	ap_uint<1> gen204_cyclix_var;
	ap_uint<1> gen205_cyclix_var;
	ap_uint<1> gen206_cyclix_var;
	ap_uint<1> gen207_cyclix_var;
	ap_uint<1> gen208_cyclix_var;
	ap_uint<1> gen209_cyclix_var;
	ap_uint<1> gen210_cyclix_var;
	ap_uint<1> gen211_cyclix_var;
	ap_uint<1> gen212_cyclix_var;
	ap_uint<1> gen213_cyclix_var;
	ap_uint<1> gen214_cyclix_var;
	ap_uint<1> gen215_cyclix_var;
	ap_uint<1> gen216_cyclix_var;
	ap_uint<1> gen217_cyclix_var;
	ap_uint<1> gen218_cyclix_var;
	ap_uint<1> gen219_cyclix_var;
	ap_uint<1> gen220_cyclix_var;
	ap_uint<1> gen221_cyclix_var;
	ap_uint<1> gen222_cyclix_var;
	ap_uint<1> gen223_cyclix_var;
	ap_uint<1> gen224_cyclix_var;
	ap_uint<1> gen225_cyclix_var;
	ap_uint<1> gen226_cyclix_var;
	ap_uint<1> gen227_cyclix_var;
	ap_uint<1> gen228_cyclix_var;
	ap_uint<1> gen229_cyclix_var;
	ap_uint<1> gen230_cyclix_var;
	ap_uint<1> gen231_cyclix_var;
	ap_uint<1> gen232_cyclix_var;
	ap_uint<1> gen233_cyclix_var;
	ap_uint<1> gen234_cyclix_var;
	ap_uint<1> gen235_cyclix_var;
	ap_uint<1> gen236_cyclix_var;
	ap_uint<1> gen237_cyclix_var;
	ap_uint<1> gen238_cyclix_var;
	ap_uint<1> gen239_cyclix_var;
	ap_uint<1> gen240_cyclix_var;
	ap_uint<1> gen241_cyclix_var;
	ap_uint<1> gen242_cyclix_var;
	ap_uint<1> gen243_cyclix_var;
	ap_uint<1> gen244_cyclix_var;
	ap_uint<1> gen245_cyclix_var;
	ap_uint<1> gen246_cyclix_var;
	ap_uint<1> gen247_cyclix_var;
	ap_uint<1> gen248_cyclix_var;
	ap_uint<1> gen249_cyclix_var;
	ap_uint<1> gen250_cyclix_var;
	ap_uint<1> gen251_cyclix_var;
	ap_uint<1> gen252_cyclix_var;
	ap_uint<1> gen253_cyclix_var;
	ap_uint<1> gen254_cyclix_var;
	ap_uint<1> gen255_cyclix_var;
	ap_uint<1> gen256_cyclix_var;
	ap_uint<1> gen257_cyclix_var;
	ap_uint<1> gen258_cyclix_var;
	ap_uint<1> gen259_cyclix_var;
	ap_uint<1> gen260_cyclix_var;
	ap_uint<1> gen261_cyclix_var;
	ap_uint<1> gen262_cyclix_var;
	ap_uint<1> gen263_cyclix_var;
	ap_uint<1> gen264_cyclix_var;
	ap_uint<1> gen265_cyclix_var;
	ap_uint<1> gen266_cyclix_var;
	ap_uint<1> gen267_cyclix_var;
	ap_uint<1> gen268_cyclix_var;
	ap_uint<1> gen269_cyclix_var;
	ap_uint<1> gen270_cyclix_var;
	ap_uint<1> gen271_cyclix_var;
	ap_uint<1> gen272_cyclix_var;
	ap_uint<1> gen273_cyclix_var;
	ap_uint<1> gen274_cyclix_var;
	ap_uint<1> gen275_cyclix_var;
	ap_uint<1> gen276_cyclix_var;
	ap_uint<1> gen277_cyclix_var;
	ap_uint<1> gen278_cyclix_var;
	ap_uint<1> gen279_cyclix_var;
	ap_uint<1> gen280_cyclix_var;
	ap_uint<1> gen281_cyclix_var;
	ap_uint<1> gen282_cyclix_var;
	ap_uint<1> gen283_cyclix_var;
	ap_uint<1> gen284_cyclix_var;
	ap_uint<1> gen285_cyclix_var;
	ap_uint<1> gen286_cyclix_var;
	ap_uint<1> gen287_cyclix_var;
	ap_uint<1> gen288_cyclix_var;
	ap_uint<1> gen289_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = ap_uint<32>(512);
		genpsticky_glbl_regfile[1] = ap_uint<32>(0);
		genpsticky_glbl_regfile[2] = ap_uint<32>(0);
		genpsticky_glbl_regfile[3] = ap_uint<32>(0);
		genpsticky_glbl_regfile[4] = ap_uint<32>(0);
		genpsticky_glbl_regfile[5] = ap_uint<32>(0);
		genpsticky_glbl_regfile[6] = ap_uint<32>(0);
		genpsticky_glbl_regfile[7] = ap_uint<32>(0);
		genpsticky_glbl_regfile[8] = ap_uint<32>(0);
		genpsticky_glbl_regfile[9] = ap_uint<32>(0);
		genpsticky_glbl_regfile[10] = ap_uint<32>(0);
		genpsticky_glbl_regfile[11] = ap_uint<32>(0);
		genpsticky_glbl_regfile[12] = ap_uint<32>(0);
		genpsticky_glbl_regfile[13] = ap_uint<32>(0);
		genpsticky_glbl_regfile[14] = ap_uint<32>(0);
		genpsticky_glbl_regfile[15] = ap_uint<32>(0);
		genpsticky_glbl_regfile[16] = ap_uint<32>(0);
		genpsticky_glbl_regfile[17] = ap_uint<32>(0);
		genpsticky_glbl_regfile[18] = ap_uint<32>(0);
		genpsticky_glbl_regfile[19] = ap_uint<32>(0);
		genpsticky_glbl_regfile[20] = ap_uint<32>(0);
		genpsticky_glbl_regfile[21] = ap_uint<32>(0);
		genpsticky_glbl_regfile[22] = ap_uint<32>(0);
		genpsticky_glbl_regfile[23] = ap_uint<32>(0);
		genpsticky_glbl_regfile[24] = ap_uint<32>(0);
		genpsticky_glbl_regfile[25] = ap_uint<32>(0);
		genpsticky_glbl_regfile[26] = ap_uint<32>(0);
		genpsticky_glbl_regfile[27] = ap_uint<32>(0);
		genpsticky_glbl_regfile[28] = ap_uint<32>(0);
		genpsticky_glbl_regfile[29] = ap_uint<32>(0);
		genpsticky_glbl_regfile[30] = ap_uint<32>(0);
		genpsticky_glbl_regfile[31] = ap_uint<32>(0);
		genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
		genpsticky_glbl_jump_vector_cmd = ap_uint<32>(0);
		genpsticky_glbl_CSR_MCAUSE = ap_uint<32>(0);
		genpsticky_glbl_MIRQEN = ap_uint<32>(1);
		genpsticky_glbl_MRETADDR = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
		genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_instr_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_full_flag = ap_uint<32>(0);
		genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_data_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_rd_ptr = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);

	} else {
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genpsticky_glbl_pc_buf = genpsticky_glbl_pc;
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[1];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[2];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[3];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[4];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[5];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[6];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[7];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[8];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[9];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[10];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[11];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[12];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[13];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[14];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[15];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[16];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[17];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[18];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[19];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[20];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[21];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[22];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[23];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[24];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[25];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[26];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[27];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[28];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[29];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[30];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[31];
		genpsticky_glbl_jump_req_cmd_buf = genpsticky_glbl_jump_req_cmd;
		genpsticky_glbl_jump_vector_cmd_buf = genpsticky_glbl_jump_vector_cmd;
		genpsticky_glbl_CSR_MCAUSE_buf = genpsticky_glbl_CSR_MCAUSE;
		genpsticky_glbl_MIRQEN_buf = genpsticky_glbl_MIRQEN;
		genpsticky_glbl_MRETADDR_buf = genpsticky_glbl_MRETADDR;
		genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genctrl_working = ap_uint<32>(0);
		gen145_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen145_cyclix_var) {
			genpstage_EXEC_genctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
		}
		gen146_cyclix_var = ap_uint<1>(0);
		gen146_cyclix_var = (gen146_cyclix_var || gen145_cyclix_var);
		gen146_cyclix_var = !gen146_cyclix_var;
		if (gen146_cyclix_var) {
			genpstage_EXEC_genctrl_active = genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
			genpstage_EXEC_genctrl_new = genpstage_EXEC_genctrl_active;
		}
		genpstage_EXEC_genctrl_occupied = genpstage_EXEC_genctrl_active;
		genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		gen147_cyclix_var = genpstage_EXEC_genctrl_occupied;
		if (gen147_cyclix_var) {
			gen148_cyclix_var = genpstage_EXEC_genctrl_new;
			if (gen148_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
			genpstage_EXEC_curinstr_addr = genpstage_EXEC_TRX_BUF[0].curinstr_addr;
			genpstage_EXEC_nextinstr_addr = genpstage_EXEC_TRX_BUF[0].nextinstr_addr;
			genpstage_EXEC_irq_recv = genpstage_EXEC_TRX_BUF[0].irq_recv;
			genpstage_EXEC_irq_mcause = genpstage_EXEC_TRX_BUF[0].irq_mcause;
			genpstage_EXEC_data_req_done = genpstage_EXEC_TRX_BUF[0].data_req_done;
			gen149_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
			if (gen149_cyclix_var) {
				gen150_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.if_id == ap_uint<1>(0));
				gen151_cyclix_var = gen150_cyclix_var;
				if (gen151_cyclix_var) {
					gen152_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.tid == genmcopipe_data_mem_rd_ptr);
					gen153_cyclix_var = gen152_cyclix_var;
					if (gen153_cyclix_var) {
						gen154_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen282_pipex_mcopipe_rdata);
						gen155_cyclix_var = gen154_cyclix_var;
						if (gen155_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen282_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen156_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen156_cyclix_var) {
				gen157_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen158_cyclix_var = gen157_cyclix_var;
				if (gen158_cyclix_var) {
					gen159_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen160_cyclix_var = gen159_cyclix_var;
					if (gen160_cyclix_var) {
						gen161_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen283_pipex_mcopipe_rdata);
						gen162_cyclix_var = gen161_cyclix_var;
						if (gen162_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen283_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen163_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen163_cyclix_var) {
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen141_pipex_succbuf = genpsticky_glbl_jump_req_cmd;
		gen143_pipex_succbuf = genpsticky_glbl_jump_vector_cmd;
		gen145_pipex_succbuf = genpsticky_glbl_regfile[1];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[2];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[3];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[4];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[5];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[6];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[7];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[8];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[9];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[10];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[11];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[12];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[13];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[14];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[15];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[16];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[17];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[18];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[19];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[20];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[21];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[22];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[23];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[24];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[25];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[26];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[27];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[28];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[29];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[30];
		gen145_pipex_succbuf = genpsticky_glbl_regfile[31];
		gen164_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		if (gen164_cyclix_var) {
			genpstage_EXEC_instr_code = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
		}
		gen153_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		gen154_pipex_var = ~gen153_pipex_var;
		gen155_pipex_var = gen154_pipex_var;
		gen165_cyclix_var = gen155_pipex_var;
		if (gen165_cyclix_var) {
			gen166_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen166_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		genpstage_EXEC_opcode = genpstage_EXEC_instr_code[6:0];
		genpstage_EXEC_alu_unsigned = ap_uint<32>(0);
		genpstage_EXEC_rs1_addr = genpstage_EXEC_instr_code[19:15];
		genpstage_EXEC_rs2_addr = genpstage_EXEC_instr_code[24:20];
		genpstage_EXEC_rd_addr = genpstage_EXEC_instr_code[11:7];
		genpstage_EXEC_funct3 = genpstage_EXEC_instr_code[14:12];
		genpstage_EXEC_funct7 = genpstage_EXEC_instr_code[31:25];
		genpstage_EXEC_shamt = genpstage_EXEC_instr_code[24:20];
		genpstage_EXEC_pred = genpstage_EXEC_instr_code[27:24];
		genpstage_EXEC_succ = genpstage_EXEC_instr_code[23:20];
		genpstage_EXEC_csrnum = genpstage_EXEC_instr_code[31:20];
		genpstage_EXEC_zimm = genpstage_EXEC_instr_code[19:15];
		gen156_pipex_var = genpstage_EXEC_instr_code[31:20];
		gen157_pipex_var = gen156_pipex_var[31];
		gen158_pipex_var = gen157_pipex_var.concat((ap_uint<31>)gen157_pipex_var.concat((ap_uint<30>)gen157_pipex_var.concat((ap_uint<29>)gen157_pipex_var.concat((ap_uint<28>)gen157_pipex_var.concat((ap_uint<27>)gen157_pipex_var.concat((ap_uint<26>)gen157_pipex_var.concat((ap_uint<25>)gen157_pipex_var.concat((ap_uint<24>)gen157_pipex_var.concat((ap_uint<23>)gen157_pipex_var.concat((ap_uint<22>)gen157_pipex_var.concat((ap_uint<21>)gen157_pipex_var.concat((ap_uint<20>)gen157_pipex_var.concat((ap_uint<19>)gen157_pipex_var.concat((ap_uint<18>)gen157_pipex_var.concat((ap_uint<17>)gen157_pipex_var.concat((ap_uint<16>)gen157_pipex_var.concat((ap_uint<15>)gen157_pipex_var.concat((ap_uint<14>)gen157_pipex_var.concat((ap_uint<13>)gen157_pipex_var.concat((ap_uint<12>)genpstage_EXEC_instr_code[31:20]))))))))))))))))))));
		genpstage_EXEC_immediate_I = gen158_pipex_var;
		gen159_pipex_var = genpstage_EXEC_instr_code[31:25].concat((ap_uint<5>)genpstage_EXEC_instr_code[11:7]);
		gen160_pipex_var = gen159_pipex_var[11];
		gen161_pipex_var = gen160_pipex_var.concat((ap_uint<31>)gen160_pipex_var.concat((ap_uint<30>)gen160_pipex_var.concat((ap_uint<29>)gen160_pipex_var.concat((ap_uint<28>)gen160_pipex_var.concat((ap_uint<27>)gen160_pipex_var.concat((ap_uint<26>)gen160_pipex_var.concat((ap_uint<25>)gen160_pipex_var.concat((ap_uint<24>)gen160_pipex_var.concat((ap_uint<23>)gen160_pipex_var.concat((ap_uint<22>)gen160_pipex_var.concat((ap_uint<21>)gen160_pipex_var.concat((ap_uint<20>)gen160_pipex_var.concat((ap_uint<19>)gen160_pipex_var.concat((ap_uint<18>)gen160_pipex_var.concat((ap_uint<17>)gen160_pipex_var.concat((ap_uint<16>)gen160_pipex_var.concat((ap_uint<15>)gen160_pipex_var.concat((ap_uint<14>)gen160_pipex_var.concat((ap_uint<13>)gen160_pipex_var.concat((ap_uint<12>)gen159_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_S = gen161_pipex_var;
		gen162_pipex_var = genpstage_EXEC_instr_code[31].concat((ap_uint<12>)genpstage_EXEC_instr_code[7].concat((ap_uint<11>)genpstage_EXEC_instr_code[30:25].concat((ap_uint<5>)genpstage_EXEC_instr_code[11:8].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen163_pipex_var = gen162_pipex_var[12];
		gen164_pipex_var = gen163_pipex_var.concat((ap_uint<31>)gen163_pipex_var.concat((ap_uint<30>)gen163_pipex_var.concat((ap_uint<29>)gen163_pipex_var.concat((ap_uint<28>)gen163_pipex_var.concat((ap_uint<27>)gen163_pipex_var.concat((ap_uint<26>)gen163_pipex_var.concat((ap_uint<25>)gen163_pipex_var.concat((ap_uint<24>)gen163_pipex_var.concat((ap_uint<23>)gen163_pipex_var.concat((ap_uint<22>)gen163_pipex_var.concat((ap_uint<21>)gen163_pipex_var.concat((ap_uint<20>)gen163_pipex_var.concat((ap_uint<19>)gen163_pipex_var.concat((ap_uint<18>)gen163_pipex_var.concat((ap_uint<17>)gen163_pipex_var.concat((ap_uint<16>)gen163_pipex_var.concat((ap_uint<15>)gen163_pipex_var.concat((ap_uint<14>)gen163_pipex_var.concat((ap_uint<13>)gen162_pipex_var)))))))))))))))))));
		genpstage_EXEC_immediate_B = gen164_pipex_var;
		gen165_pipex_var = genpstage_EXEC_instr_code[31:12].concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_immediate_U = gen165_pipex_var;
		gen166_pipex_var = genpstage_EXEC_instr_code[31].concat((ap_uint<20>)genpstage_EXEC_instr_code[19:12].concat((ap_uint<12>)genpstage_EXEC_instr_code[20].concat((ap_uint<11>)genpstage_EXEC_instr_code[30:21].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen167_pipex_var = gen166_pipex_var[20];
		gen168_pipex_var = gen167_pipex_var.concat((ap_uint<31>)gen167_pipex_var.concat((ap_uint<30>)gen167_pipex_var.concat((ap_uint<29>)gen167_pipex_var.concat((ap_uint<28>)gen167_pipex_var.concat((ap_uint<27>)gen167_pipex_var.concat((ap_uint<26>)gen167_pipex_var.concat((ap_uint<25>)gen167_pipex_var.concat((ap_uint<24>)gen167_pipex_var.concat((ap_uint<23>)gen167_pipex_var.concat((ap_uint<22>)gen167_pipex_var.concat((ap_uint<21>)gen166_pipex_var)))))))))));
		genpstage_EXEC_immediate_J = gen168_pipex_var;
		switch (genpstage_EXEC_opcode) {
			case 55:
				genpstage_EXEC_op1_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 23:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 111:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_J;
				break;
			case 103:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 99:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_B;
				gen169_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(6));
				gen170_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(7));
				gen171_pipex_var = (gen169_pipex_var | gen170_pipex_var);
				gen172_pipex_var = gen171_pipex_var;
				gen167_cyclix_var = gen172_pipex_var;
				if (gen167_cyclix_var) {
					genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(5);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 35:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_S;
				break;
			case 19:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen173_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_instr_code[24:20]);
						genpstage_EXEC_immediate = gen173_pipex_var;
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen174_pipex_var = genpstage_EXEC_instr_code[30];
						gen168_cyclix_var = gen174_pipex_var;
						if (gen168_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen175_pipex_var = ap_uint<1>(0);
						gen175_pipex_var = (gen175_pipex_var || gen174_pipex_var);
						gen175_pipex_var = !gen175_pipex_var;
						gen169_cyclix_var = gen175_pipex_var;
						if (gen169_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen176_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_instr_code[24:20]);
						genpstage_EXEC_immediate = gen176_pipex_var;
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen177_pipex_var = genpstage_EXEC_instr_code[30];
						gen170_cyclix_var = gen177_pipex_var;
						if (gen170_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						}
						gen178_pipex_var = ap_uint<1>(0);
						gen178_pipex_var = (gen178_pipex_var || gen177_pipex_var);
						gen178_pipex_var = !gen178_pipex_var;
						gen171_cyclix_var = gen178_pipex_var;
						if (gen171_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen179_pipex_var = genpstage_EXEC_instr_code[30];
						gen172_cyclix_var = gen179_pipex_var;
						if (gen172_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen180_pipex_var = ap_uint<1>(0);
						gen180_pipex_var = (gen180_pipex_var || gen179_pipex_var);
						gen180_pipex_var = !gen180_pipex_var;
						gen173_cyclix_var = gen180_pipex_var;
						if (gen173_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 15:
				genpstage_EXEC_fencereq = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen181_pipex_var = genpstage_EXEC_instr_code[20];
						gen174_cyclix_var = gen181_pipex_var;
						if (gen174_cyclix_var) {
							genpstage_EXEC_ebreakreq = ap_uint<32>(1);
						}
						gen182_pipex_var = ap_uint<1>(0);
						gen182_pipex_var = (gen182_pipex_var || gen181_pipex_var);
						gen182_pipex_var = !gen182_pipex_var;
						gen175_cyclix_var = gen182_pipex_var;
						if (gen175_cyclix_var) {
							genpstage_EXEC_ecallreq = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen183_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen183_pipex_var;
						break;
					case 6:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen184_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen184_pipex_var;
						break;
					case 7:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen185_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen185_pipex_var;
						break;
				}
				break;
		}
		gen186_pipex_var = genpstage_EXEC_mem_req;
		gen176_cyclix_var = gen186_pipex_var;
		if (gen176_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					genpstage_EXEC_load_signext = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					genpstage_EXEC_load_signext = ap_uint<32>(1);
					break;
				case 2:
					genpstage_EXEC_mem_be = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
			}
		}
		gen187_pipex_var = (genpstage_EXEC_instr_code == ap_uint<32>(807403635));
		gen188_pipex_var = gen187_pipex_var;
		gen177_cyclix_var = gen188_pipex_var;
		if (gen177_cyclix_var) {
			genpstage_EXEC_mret_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
			genpstage_EXEC_jump_src = ap_uint<32>(0);
			genpstage_EXEC_immediate = genpsticky_glbl_MRETADDR;
		}
		gen189_pipex_var = (genpstage_EXEC_rd_addr == ap_uint<32>(0));
		gen190_pipex_var = gen189_pipex_var;
		gen178_cyclix_var = gen190_pipex_var;
		if (gen178_cyclix_var) {
			genpstage_EXEC_rd_req = ap_uint<32>(0);
		}
		gen191_pipex_var = genpsticky_glbl_regfile_buf[1];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[2];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[3];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[4];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[5];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[6];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[7];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[8];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[9];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[10];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[11];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[12];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[13];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[14];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[15];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[16];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[17];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[18];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[19];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[20];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[21];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[22];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[23];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[24];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[25];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[26];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[27];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[28];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[29];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[30];
		gen191_pipex_var = genpsticky_glbl_regfile_buf[31];
		genpstage_EXEC_rs1_rdata = gen191_pipex_var[genpstage_EXEC_rs1_addr];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[1];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[2];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[3];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[4];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[5];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[6];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[7];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[8];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[9];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[10];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[11];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[12];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[13];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[14];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[15];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[16];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[17];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[18];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[19];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[20];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[21];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[22];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[23];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[24];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[25];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[26];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[27];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[28];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[29];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[30];
		gen192_pipex_var = genpsticky_glbl_regfile_buf[31];
		genpstage_EXEC_rs2_rdata = gen192_pipex_var[genpstage_EXEC_rs2_addr];
		gen193_pipex_var = (genpstage_EXEC_rs1_addr == ap_uint<32>(0));
		gen194_pipex_var = gen193_pipex_var;
		gen179_cyclix_var = gen194_pipex_var;
		if (gen179_cyclix_var) {
			genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
		}
		gen195_pipex_var = (genpstage_EXEC_rs2_addr == ap_uint<32>(0));
		gen196_pipex_var = gen195_pipex_var;
		gen180_cyclix_var = gen196_pipex_var;
		if (gen180_cyclix_var) {
			genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
		}
		gen197_pipex_var = genpstage_EXEC_csrreq;
		gen181_cyclix_var = gen197_pipex_var;
		if (gen181_cyclix_var) {
			genpstage_EXEC_csr_rdata = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_alu_op1 = genpstage_EXEC_rs1_rdata;
		switch (genpstage_EXEC_op1_source) {
			case 1:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_curinstr_addr;
				break;
		}
		genpstage_EXEC_alu_op2 = genpstage_EXEC_rs2_rdata;
		switch (genpstage_EXEC_op2_source) {
			case 1:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_csr_rdata;
				break;
		}
		gen198_pipex_var = genpstage_EXEC_alu_unsigned;
		gen182_cyclix_var = gen198_pipex_var;
		if (gen182_cyclix_var) {
			gen199_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen199_pipex_var;
			gen200_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen200_pipex_var;
		}
		gen201_pipex_var = ap_uint<1>(0);
		gen201_pipex_var = (gen201_pipex_var || gen198_pipex_var);
		gen201_pipex_var = !gen201_pipex_var;
		gen183_cyclix_var = gen201_pipex_var;
		if (gen183_cyclix_var) {
			gen202_pipex_var = genpstage_EXEC_alu_op1[31];
			gen203_pipex_var = gen202_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen203_pipex_var;
			gen204_pipex_var = genpstage_EXEC_alu_op2[31];
			gen205_pipex_var = gen204_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen205_pipex_var;
		}
		gen206_pipex_var = genpsticky_glbl_MIRQEN;
		gen184_cyclix_var = gen206_pipex_var;
		if (gen184_cyclix_var) {
			gen207_pipex_var = ~genpstage_EXEC_irq_recv;
			gen208_pipex_var = gen207_pipex_var;
			gen185_cyclix_var = gen208_pipex_var;
			if (gen185_cyclix_var) {
				gen186_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen186_cyclix_var) {
					gen187_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_irq_mcause);
					gen209_pipex_var = gen187_cyclix_var;
				}
				genpstage_EXEC_irq_recv = gen209_pipex_var;
				gen188_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen188_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen209_pipex_var;
				}
				genpstage_EXEC_irq_mcause = genpstage_EXEC_irq_mcause;
				gen189_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen189_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_irq_mcause;
				}
			}
			gen210_pipex_var = genpstage_EXEC_irq_recv;
			gen190_cyclix_var = gen210_pipex_var;
			if (gen190_cyclix_var) {
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
				genpstage_EXEC_jump_src = ap_uint<32>(0);
				genpstage_EXEC_rs1_req = ap_uint<32>(0);
				genpstage_EXEC_rs2_req = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(0);
				genpstage_EXEC_immediate = ap_uint<32>(128);
				genpstage_EXEC_fencereq = ap_uint<32>(0);
				genpstage_EXEC_ecallreq = ap_uint<32>(0);
				genpstage_EXEC_ebreakreq = ap_uint<32>(0);
				genpstage_EXEC_csrreq = ap_uint<32>(0);
				genpstage_EXEC_alu_req = ap_uint<32>(0);
				genpstage_EXEC_mem_req = ap_uint<32>(0);
				gen191_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen191_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(0);
				}
				gen192_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen192_cyclix_var) {
					genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_irq_mcause;
				}
				gen193_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen193_cyclix_var) {
					genpsticky_glbl_MRETADDR = genpstage_EXEC_curinstr_addr;
				}
			}
		}
		gen211_pipex_var = genpstage_EXEC_mret_req;
		gen194_cyclix_var = gen211_pipex_var;
		if (gen194_cyclix_var) {
			gen195_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen195_cyclix_var) {
				genpsticky_glbl_MIRQEN = ap_uint<32>(1);
			}
		}
		genpstage_EXEC_alu_result_wide = genpstage_EXEC_alu_op1_wide;
		gen212_pipex_var = genpstage_EXEC_alu_req;
		gen196_cyclix_var = gen212_pipex_var;
		if (gen196_cyclix_var) {
			switch (genpstage_EXEC_alu_opcode) {
				case 0:
					gen213_pipex_var = (genpstage_EXEC_alu_op1_wide + genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen213_pipex_var;
					break;
				case 1:
					gen214_pipex_var = (genpstage_EXEC_alu_op1_wide - genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen214_pipex_var;
					break;
				case 2:
					gen215_pipex_var = (genpstage_EXEC_alu_op1_wide & genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen215_pipex_var;
					break;
				case 3:
					gen216_pipex_var = (genpstage_EXEC_alu_op1_wide | genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen216_pipex_var;
					break;
				case 4:
					gen217_pipex_var = (genpstage_EXEC_alu_op1_wide << genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen217_pipex_var;
					break;
				case 5:
					gen218_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1_wide[31:0]);
					gen219_pipex_var = (gen218_pipex_var >> genpstage_EXEC_alu_op2_wide[4:0]);
					genpstage_EXEC_alu_result_wide = gen219_pipex_var;
					break;
				case 6:
					gen220_pipex_var = genpstage_EXEC_alu_op1_wide[31:0];
					gen221_pipex_var = gen220_pipex_var[31];
					gen222_pipex_var = gen221_pipex_var.concat((ap_uint<63>)gen221_pipex_var.concat((ap_uint<62>)gen221_pipex_var.concat((ap_uint<61>)gen221_pipex_var.concat((ap_uint<60>)gen221_pipex_var.concat((ap_uint<59>)gen221_pipex_var.concat((ap_uint<58>)gen221_pipex_var.concat((ap_uint<57>)gen221_pipex_var.concat((ap_uint<56>)gen221_pipex_var.concat((ap_uint<55>)gen221_pipex_var.concat((ap_uint<54>)gen221_pipex_var.concat((ap_uint<53>)gen221_pipex_var.concat((ap_uint<52>)gen221_pipex_var.concat((ap_uint<51>)gen221_pipex_var.concat((ap_uint<50>)gen221_pipex_var.concat((ap_uint<49>)gen221_pipex_var.concat((ap_uint<48>)gen221_pipex_var.concat((ap_uint<47>)gen221_pipex_var.concat((ap_uint<46>)gen221_pipex_var.concat((ap_uint<45>)gen221_pipex_var.concat((ap_uint<44>)gen221_pipex_var.concat((ap_uint<43>)gen221_pipex_var.concat((ap_uint<42>)gen221_pipex_var.concat((ap_uint<41>)gen221_pipex_var.concat((ap_uint<40>)gen221_pipex_var.concat((ap_uint<39>)gen221_pipex_var.concat((ap_uint<38>)gen221_pipex_var.concat((ap_uint<37>)gen221_pipex_var.concat((ap_uint<36>)gen221_pipex_var.concat((ap_uint<35>)gen221_pipex_var.concat((ap_uint<34>)gen221_pipex_var.concat((ap_uint<33>)gen221_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1_wide[31:0]))))))))))))))))))))))))))))))));
					gen223_pipex_var = (gen222_pipex_var >> genpstage_EXEC_alu_op2_wide[4:0]);
					genpstage_EXEC_alu_result_wide = gen223_pipex_var;
					break;
				case 7:
					gen224_pipex_var = (genpstage_EXEC_alu_op1_wide ^ genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen224_pipex_var;
					break;
				case 8:
					gen225_pipex_var = ~genpstage_EXEC_alu_op2_wide;
					gen226_pipex_var = (genpstage_EXEC_alu_op1_wide & gen225_pipex_var);
					genpstage_EXEC_alu_result_wide = gen226_pipex_var;
					break;
			}
			genpstage_EXEC_alu_result = genpstage_EXEC_alu_result_wide[31:0];
			genpstage_EXEC_alu_CF = genpstage_EXEC_alu_result_wide[32];
			genpstage_EXEC_alu_SF = genpstage_EXEC_alu_result_wide[31];
			gen227_pipex_var = |genpstage_EXEC_alu_result;
			gen228_pipex_var = ~gen227_pipex_var;
			genpstage_EXEC_alu_ZF = gen228_pipex_var;
			gen229_pipex_var = ~genpstage_EXEC_alu_op1[31];
			gen230_pipex_var = ~genpstage_EXEC_alu_op2[31];
			gen231_pipex_var = (gen229_pipex_var & gen230_pipex_var);
			gen232_pipex_var = (gen231_pipex_var & genpstage_EXEC_alu_result[31]);
			gen233_pipex_var = ~genpstage_EXEC_alu_result[31];
			gen234_pipex_var = (genpstage_EXEC_alu_op1[31] & genpstage_EXEC_alu_op2[31]);
			gen235_pipex_var = (gen234_pipex_var & gen233_pipex_var);
			gen236_pipex_var = (gen232_pipex_var | gen235_pipex_var);
			genpstage_EXEC_alu_OF = gen236_pipex_var;
			gen237_pipex_var = genpstage_EXEC_alu_unsigned;
			gen197_cyclix_var = gen237_pipex_var;
			if (gen197_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_CF;
			}
			gen238_pipex_var = ap_uint<1>(0);
			gen238_pipex_var = (gen238_pipex_var || gen237_pipex_var);
			gen238_pipex_var = !gen238_pipex_var;
			gen198_cyclix_var = gen238_pipex_var;
			if (gen198_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_OF;
			}
		}
		switch (genpstage_EXEC_rd_source) {
			case 0:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_immediate;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_result;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_CF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_OF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_nextinstr_addr;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_csr_rdata;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
		}
		gen239_pipex_var = (genpstage_EXEC_curinstr_addr + genpstage_EXEC_immediate);
		genpstage_EXEC_curinstraddr_imm = gen239_pipex_var;
		switch (genpstage_EXEC_jump_src) {
			case 0:
				genpstage_EXEC_jump_vector = genpstage_EXEC_immediate;
				break;
			case 1:
				genpstage_EXEC_jump_vector = genpstage_EXEC_alu_result;
				break;
		}
		gen240_pipex_var = genpstage_EXEC_jump_req_cond;
		gen199_cyclix_var = gen240_pipex_var;
		if (gen199_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					gen241_pipex_var = genpstage_EXEC_alu_ZF;
					gen200_cyclix_var = gen241_pipex_var;
					if (gen200_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 1:
					gen242_pipex_var = ~genpstage_EXEC_alu_ZF;
					gen243_pipex_var = gen242_pipex_var;
					gen201_cyclix_var = gen243_pipex_var;
					if (gen201_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 4:
					gen244_pipex_var = genpstage_EXEC_alu_CF;
					gen202_cyclix_var = gen244_pipex_var;
					if (gen202_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 5:
					gen245_pipex_var = ~genpstage_EXEC_alu_CF;
					gen246_pipex_var = gen245_pipex_var;
					gen203_cyclix_var = gen246_pipex_var;
					if (gen203_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 6:
					gen247_pipex_var = genpstage_EXEC_alu_CF;
					gen204_cyclix_var = gen247_pipex_var;
					if (gen204_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 7:
					gen248_pipex_var = ~genpstage_EXEC_alu_CF;
					gen249_pipex_var = gen248_pipex_var;
					gen205_cyclix_var = gen249_pipex_var;
					if (gen205_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_mem_addr = genpstage_EXEC_alu_result;
		genpstage_EXEC_mem_wdata = genpstage_EXEC_rs2_rdata;
		gen140_pipex_succreq = ap_uint<32>(1);
		gen141_pipex_succbuf = genpstage_EXEC_jump_req;
		gen142_pipex_succreq = ap_uint<32>(1);
		gen143_pipex_succbuf = genpstage_EXEC_jump_vector;
		gen250_pipex_var = genpstage_EXEC_jump_req;
		gen206_cyclix_var = gen250_pipex_var;
		if (gen206_cyclix_var) {
			genpstage_EXEC_genpctrl_flushreq = (genpstage_EXEC_genpctrl_flushreq | genpstage_EXEC_genctrl_active);
		}
		gen251_pipex_var = genpstage_EXEC_mem_req;
		gen207_cyclix_var = gen251_pipex_var;
		if (gen207_cyclix_var) {
			gen252_pipex_var = ~genpstage_EXEC_data_req_done;
			gen253_pipex_var = gen252_pipex_var;
			gen208_cyclix_var = gen253_pipex_var;
			if (gen208_cyclix_var) {
				genpstage_EXEC_data_busreq = genpstage_EXEC_mem_addr;
				genpstage_EXEC_data_busreq = genpstage_EXEC_mem_be;
				genpstage_EXEC_data_busreq = genpstage_EXEC_mem_wdata;
				gen209_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen209_cyclix_var) {
					gen210_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen211_cyclix_var = gen210_cyclix_var;
					if (gen211_cyclix_var) {
						gen284_pipex_req_struct = genpstage_EXEC_mem_cmd;
						gen284_pipex_req_struct = genpstage_EXEC_data_busreq;
						gen212_cyclix_var = genmcopipe_data_mem_req.write_nb(gen284_pipex_req_struct);
						gen213_cyclix_var = gen212_cyclix_var;
						if (gen213_cyclix_var) {
							gen254_pipex_var = ap_uint<32>(1);
							gen214_cyclix_var = !genpstage_EXEC_mem_cmd;
							genpstage_EXEC_TRX_BUF = gen214_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen215_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
							if (gen215_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_data_req_done = gen254_pipex_var;
				gen216_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen216_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen254_pipex_var;
				}
			}
			gen255_pipex_var = ~genpstage_EXEC_data_req_done;
			gen256_pipex_var = gen255_pipex_var;
			gen217_cyclix_var = gen256_pipex_var;
			if (gen217_cyclix_var) {
				gen218_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen218_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen257_pipex_var = genpstage_EXEC_mem_req;
		gen219_cyclix_var = gen257_pipex_var;
		if (gen219_cyclix_var) {
			gen258_pipex_var = ~genpstage_EXEC_mem_cmd;
			gen259_pipex_var = gen258_pipex_var;
			gen220_cyclix_var = gen259_pipex_var;
			if (gen220_cyclix_var) {
				gen221_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				if (gen221_cyclix_var) {
					genpstage_EXEC_mem_rdata = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdata;
				}
				gen260_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				gen261_pipex_var = gen260_pipex_var;
				gen222_cyclix_var = gen261_pipex_var;
				if (gen222_cyclix_var) {
					genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				}
				gen262_pipex_var = ap_uint<1>(0);
				gen262_pipex_var = (gen262_pipex_var || gen261_pipex_var);
				gen262_pipex_var = !gen262_pipex_var;
				gen223_cyclix_var = gen262_pipex_var;
				if (gen223_cyclix_var) {
					gen224_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen224_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		gen263_pipex_var = (genpstage_EXEC_mem_be == ap_uint<32>(1));
		gen264_pipex_var = gen263_pipex_var;
		gen225_cyclix_var = gen264_pipex_var;
		if (gen225_cyclix_var) {
			gen265_pipex_var = genpstage_EXEC_load_signext;
			gen226_cyclix_var = gen265_pipex_var;
			if (gen226_cyclix_var) {
				gen266_pipex_var = genpstage_EXEC_mem_rdata[7:0];
				gen267_pipex_var = gen266_pipex_var[7];
				gen268_pipex_var = gen267_pipex_var.concat((ap_uint<31>)gen267_pipex_var.concat((ap_uint<30>)gen267_pipex_var.concat((ap_uint<29>)gen267_pipex_var.concat((ap_uint<28>)gen267_pipex_var.concat((ap_uint<27>)gen267_pipex_var.concat((ap_uint<26>)gen267_pipex_var.concat((ap_uint<25>)gen267_pipex_var.concat((ap_uint<24>)gen267_pipex_var.concat((ap_uint<23>)gen267_pipex_var.concat((ap_uint<22>)gen267_pipex_var.concat((ap_uint<21>)gen267_pipex_var.concat((ap_uint<20>)gen267_pipex_var.concat((ap_uint<19>)gen267_pipex_var.concat((ap_uint<18>)gen267_pipex_var.concat((ap_uint<17>)gen267_pipex_var.concat((ap_uint<16>)gen267_pipex_var.concat((ap_uint<15>)gen267_pipex_var.concat((ap_uint<14>)gen267_pipex_var.concat((ap_uint<13>)gen267_pipex_var.concat((ap_uint<12>)gen267_pipex_var.concat((ap_uint<11>)gen267_pipex_var.concat((ap_uint<10>)gen267_pipex_var.concat((ap_uint<9>)gen267_pipex_var.concat((ap_uint<8>)genpstage_EXEC_mem_rdata[7:0]))))))))))))))))))))))));
				genpstage_EXEC_mem_rdata = gen268_pipex_var;
			}
			gen269_pipex_var = ap_uint<1>(0);
			gen269_pipex_var = (gen269_pipex_var || gen265_pipex_var);
			gen269_pipex_var = !gen269_pipex_var;
			gen227_cyclix_var = gen269_pipex_var;
			if (gen227_cyclix_var) {
				gen270_pipex_var = ap_uint<24>(0).concat((ap_uint<8>)genpstage_EXEC_mem_rdata[7:0]);
				genpstage_EXEC_mem_rdata = gen270_pipex_var;
			}
		}
		gen271_pipex_var = (genpstage_EXEC_mem_be == ap_uint<32>(3));
		gen272_pipex_var = gen271_pipex_var;
		gen228_cyclix_var = gen272_pipex_var;
		if (gen228_cyclix_var) {
			gen273_pipex_var = genpstage_EXEC_load_signext;
			gen229_cyclix_var = gen273_pipex_var;
			if (gen229_cyclix_var) {
				gen274_pipex_var = genpstage_EXEC_mem_rdata[15:0];
				gen275_pipex_var = gen274_pipex_var[15];
				gen276_pipex_var = gen275_pipex_var.concat((ap_uint<31>)gen275_pipex_var.concat((ap_uint<30>)gen275_pipex_var.concat((ap_uint<29>)gen275_pipex_var.concat((ap_uint<28>)gen275_pipex_var.concat((ap_uint<27>)gen275_pipex_var.concat((ap_uint<26>)gen275_pipex_var.concat((ap_uint<25>)gen275_pipex_var.concat((ap_uint<24>)gen275_pipex_var.concat((ap_uint<23>)gen275_pipex_var.concat((ap_uint<22>)gen275_pipex_var.concat((ap_uint<21>)gen275_pipex_var.concat((ap_uint<20>)gen275_pipex_var.concat((ap_uint<19>)gen275_pipex_var.concat((ap_uint<18>)gen275_pipex_var.concat((ap_uint<17>)gen275_pipex_var.concat((ap_uint<16>)genpstage_EXEC_mem_rdata[15:0]))))))))))))))));
				genpstage_EXEC_mem_rdata = gen276_pipex_var;
			}
			gen277_pipex_var = ap_uint<1>(0);
			gen277_pipex_var = (gen277_pipex_var || gen273_pipex_var);
			gen277_pipex_var = !gen277_pipex_var;
			gen230_cyclix_var = gen277_pipex_var;
			if (gen230_cyclix_var) {
				gen278_pipex_var = ap_uint<16>(0).concat((ap_uint<16>)genpstage_EXEC_mem_rdata[15:0]);
				genpstage_EXEC_mem_rdata = gen278_pipex_var;
			}
		}
		gen279_pipex_var = (genpstage_EXEC_rd_source == ap_uint<32>(5));
		gen280_pipex_var = gen279_pipex_var;
		gen231_cyclix_var = gen280_pipex_var;
		if (gen231_cyclix_var) {
			genpstage_EXEC_rd_wdata = genpstage_EXEC_mem_rdata;
		}
		gen281_pipex_var = genpstage_EXEC_rd_req;
		gen232_cyclix_var = gen281_pipex_var;
		if (gen232_cyclix_var) {
			gen144_pipex_succreq = ap_uint<32>(1);
			gen145_pipex_succbuf = genpstage_EXEC_rd_wdata;
		}
		gen233_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen233_cyclix_var) {
			genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		}
		gen234_cyclix_var = ap_uint<1>(0);
		gen234_cyclix_var = (gen234_cyclix_var || gen233_cyclix_var);
		gen234_cyclix_var = !gen234_cyclix_var;
		if (gen234_cyclix_var) {
			genpstage_EXEC_genctrl_finish = genpstage_EXEC_genctrl_occupied;
			genpstage_EXEC_genctrl_succ = genpstage_EXEC_genctrl_active;
		}
		gen235_cyclix_var = genpstage_EXEC_genctrl_succ;
		if (gen235_cyclix_var) {
			gen236_cyclix_var = gen140_pipex_succreq;
			if (gen236_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen141_pipex_succbuf;
			}
			gen237_cyclix_var = gen142_pipex_succreq;
			if (gen237_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = gen143_pipex_succbuf;
			}
			gen238_cyclix_var = gen144_pipex_succreq;
			if (gen238_cyclix_var) {
				genpsticky_glbl_regfile = gen145_pipex_succbuf[1];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[2];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[3];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[4];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[5];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[6];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[7];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[8];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[9];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[10];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[11];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[12];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[13];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[14];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[15];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[16];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[17];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[18];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[19];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[20];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[21];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[22];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[23];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[24];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[25];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[26];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[27];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[28];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[29];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[30];
				genpsticky_glbl_regfile = gen145_pipex_succbuf[31];
			}
		}
		gen239_cyclix_var = genpstage_EXEC_genctrl_finish;
		if (gen239_cyclix_var) {
			gen240_cyclix_var = genpstage_EXEC_genctrl_succ;
			if (gen240_cyclix_var) {
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen241_cyclix_var = ~genpstage_EXEC_TRX_BUF_COUNTER_FULL;
		genpstage_EXEC_genctrl_rdy = gen241_cyclix_var;
		genpstage_EXEC_genctrl_working = (genpstage_EXEC_genctrl_succ | genpstage_EXEC_genctrl_stalled_glbl);
		genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_working = ap_uint<32>(0);
		gen242_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen242_cyclix_var) {
			genpstage_IFETCH_genctrl_new = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
		}
		gen243_cyclix_var = ap_uint<1>(0);
		gen243_cyclix_var = (gen243_cyclix_var || gen242_cyclix_var);
		gen243_cyclix_var = !gen243_cyclix_var;
		if (gen243_cyclix_var) {
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
			genpstage_IFETCH_genctrl_new = genpstage_IFETCH_genctrl_active;
		}
		genpstage_IFETCH_genctrl_occupied = genpstage_IFETCH_genctrl_active;
		genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = (genpstage_IFETCH_genpctrl_flushreq | genpstage_EXEC_genpctrl_flushreq);
		gen244_cyclix_var = genpstage_IFETCH_genctrl_occupied;
		if (gen244_cyclix_var) {
			gen245_cyclix_var = genpstage_IFETCH_genctrl_new;
			if (gen245_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
			}
			genpstage_IFETCH_instr_req_done = genpstage_IFETCH_TRX_BUF[0].instr_req_done;
			gen246_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen246_cyclix_var) {
				gen247_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen248_cyclix_var = gen247_cyclix_var;
				if (gen248_cyclix_var) {
					gen249_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen250_cyclix_var = gen249_cyclix_var;
					if (gen250_cyclix_var) {
						gen251_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen285_pipex_mcopipe_rdata);
						gen252_cyclix_var = gen251_cyclix_var;
						if (gen252_cyclix_var) {
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(1);
							genpstage_IFETCH_TRX_BUF = gen285_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen253_cyclix_var = genpstage_IFETCH_genpctrl_flushreq;
			if (gen253_cyclix_var) {
			}
		}
		gen137_pipex_succbuf = genpsticky_glbl_jump_req_cmd;
		gen139_pipex_succbuf = genpsticky_glbl_pc;
		genpstage_IFETCH_curinstr_addr = genpsticky_glbl_pc;
		gen146_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen254_cyclix_var = gen146_pipex_var;
		if (gen254_cyclix_var) {
			genpstage_IFETCH_curinstr_addr = genpsticky_glbl_jump_vector_cmd;
		}
		gen136_pipex_succreq = ap_uint<32>(1);
		gen137_pipex_succbuf = ap_uint<32>(0);
		gen147_pipex_var = (genpstage_IFETCH_curinstr_addr + ap_uint<32>(4));
		genpstage_IFETCH_nextinstr_addr = gen147_pipex_var;
		gen138_pipex_succreq = ap_uint<32>(1);
		gen139_pipex_succbuf = genpstage_IFETCH_nextinstr_addr;
		genpstage_IFETCH_instr_busreq = genpstage_IFETCH_curinstr_addr;
		genpstage_IFETCH_instr_busreq = ap_uint<32>(15);
		genpstage_IFETCH_instr_busreq = ap_uint<32>(0);
		gen148_pipex_var = ~genpstage_IFETCH_instr_req_done;
		gen149_pipex_var = gen148_pipex_var;
		gen255_cyclix_var = gen149_pipex_var;
		if (gen255_cyclix_var) {
			gen256_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen256_cyclix_var) {
				gen257_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen258_cyclix_var = gen257_cyclix_var;
				if (gen258_cyclix_var) {
					gen286_pipex_req_struct = ap_uint<1>(0);
					gen286_pipex_req_struct = genpstage_IFETCH_instr_busreq;
					gen259_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen286_pipex_req_struct);
					gen260_cyclix_var = gen259_cyclix_var;
					if (gen260_cyclix_var) {
						gen150_pipex_var = ap_uint<32>(1);
						gen261_cyclix_var = !ap_uint<1>(0);
						genpstage_IFETCH_TRX_BUF = gen261_cyclix_var;
						genpstage_IFETCH_TRX_BUF = genmcopipe_instr_mem_wr_ptr;
						genpstage_IFETCH_TRX_BUF = ap_uint<1>(0);
						gen262_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
						if (gen262_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_IFETCH_instr_req_done = gen150_pipex_var;
			gen263_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen263_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = gen150_pipex_var;
			}
		}
		gen151_pipex_var = ~genpstage_IFETCH_instr_req_done;
		gen152_pipex_var = gen151_pipex_var;
		gen264_cyclix_var = gen152_pipex_var;
		if (gen264_cyclix_var) {
			gen265_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen265_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		gen266_cyclix_var = ~genpstage_EXEC_genctrl_rdy;
		gen267_cyclix_var = gen266_cyclix_var;
		if (gen267_cyclix_var) {
			gen268_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen268_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		gen269_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen269_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		}
		gen270_cyclix_var = ap_uint<1>(0);
		gen270_cyclix_var = (gen270_cyclix_var || gen269_cyclix_var);
		gen270_cyclix_var = !gen270_cyclix_var;
		if (gen270_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = genpstage_IFETCH_genctrl_occupied;
			genpstage_IFETCH_genctrl_succ = genpstage_IFETCH_genctrl_active;
		}
		gen271_cyclix_var = genpstage_IFETCH_genctrl_succ;
		if (gen271_cyclix_var) {
			gen272_cyclix_var = gen136_pipex_succreq;
			if (gen272_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen137_pipex_succbuf;
			}
			gen273_cyclix_var = gen138_pipex_succreq;
			if (gen273_cyclix_var) {
				genpsticky_glbl_pc = gen139_pipex_succbuf;
			}
		}
		gen274_cyclix_var = genpstage_IFETCH_genctrl_finish;
		if (gen274_cyclix_var) {
			gen275_cyclix_var = genpstage_IFETCH_genctrl_succ;
			if (gen275_cyclix_var) {
				gen276_cyclix_var = genpstage_EXEC_genctrl_rdy;
				if (gen276_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_IFETCH_curinstr_addr;
					genpstage_EXEC_TRX_BUF = genpstage_IFETCH_nextinstr_addr;
					genpstage_EXEC_TRX_BUF = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem;
					genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER + ap_uint<32>(1));
				}
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER = (genpstage_IFETCH_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen277_cyclix_var = ~genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
		genpstage_IFETCH_genctrl_rdy = gen277_cyclix_var;
		genpstage_IFETCH_genctrl_working = (genpstage_IFETCH_genctrl_succ | genpstage_IFETCH_genctrl_stalled_glbl);
		gen278_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen278_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen279_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen280_cyclix_var = gen279_cyclix_var;
			if (gen280_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen281_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen281_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen282_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen283_cyclix_var = gen282_cyclix_var;
			if (gen283_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen284_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen284_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen285_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen286_cyclix_var = gen285_cyclix_var;
			if (gen286_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen287_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen287_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen288_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen289_cyclix_var = gen288_cyclix_var;
			if (gen289_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
	}
}
