// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2021-06-10
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include <ap_int.h>
#include <hls_stream.h>
#include "riscv_1stage.hpp"

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_instr_mem_struct;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_data_mem_struct;

typedef struct {
	ap_uint<1> instr_req_done;
	ap_uint<1> irq_recv;
	ap_uint<8> irq_mcause;
	ap_uint<1> data_req_done;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
	genmcopipe_handle_data_mem_struct genmcopipe_handle_data_mem;
} genpstage_EXEC_TRX_BUF_STRUCT;

ap_uint<32> genpsticky_glbl_pc;
ap_uint<32> genpsticky_glbl_regfile [32];
ap_uint<1> genpsticky_glbl_jump_req_cmd;
ap_uint<32> genpsticky_glbl_jump_vector_cmd;
ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
ap_uint<1> genpsticky_glbl_MIRQEN;
ap_uint<32> genpsticky_glbl_MRETADDR;
ap_uint<1> genmcopipe_instr_mem_wr_done;
ap_uint<1> genmcopipe_instr_mem_rd_done;
ap_uint<1> genmcopipe_instr_mem_full_flag;
ap_uint<1> genmcopipe_instr_mem_empty_flag;
ap_uint<1> genmcopipe_instr_mem_wr_ptr;
ap_uint<1> genmcopipe_instr_mem_rd_ptr;
ap_uint<1> genmcopipe_data_mem_wr_done;
ap_uint<1> genmcopipe_data_mem_rd_done;
ap_uint<1> genmcopipe_data_mem_full_flag;
ap_uint<1> genmcopipe_data_mem_empty_flag;
ap_uint<1> genmcopipe_data_mem_wr_ptr;
ap_uint<1> genmcopipe_data_mem_rd_ptr;
genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_BUF [0:0];
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_EXEC_genctrl_stalled_glbl;

void riscv_1stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<genpmodule_riscv_1stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_1stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req) {


	ap_uint<32> genpsticky_glbl_pc_buf;
	ap_uint<32> genpsticky_glbl_regfile_buf [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd_buf;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd_buf;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE_buf;
	ap_uint<1> genpsticky_glbl_MIRQEN_buf;
	ap_uint<32> genpsticky_glbl_MRETADDR_buf;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	ap_uint<1> genpstage_EXEC_genctrl_active;
	ap_uint<1> genpstage_EXEC_genctrl_working;
	ap_uint<1> genpstage_EXEC_genctrl_succ;
	ap_uint<1> genpstage_EXEC_genctrl_occupied;
	ap_uint<1> genpstage_EXEC_genctrl_rdy;
	ap_uint<1> genpstage_EXEC_genctrl_new;
	ap_uint<1> genpstage_EXEC_genctrl_finish;
	ap_uint<1> gen136_pipex_succreq;
	ap_uint<1> gen137_pipex_succbuf;
	ap_uint<1> gen138_pipex_succreq;
	ap_uint<32> gen139_pipex_succbuf;
	ap_uint<1> gen140_pipex_succreq;
	ap_uint<32> gen141_pipex_succbuf;
	ap_uint<1> gen142_pipex_succreq;
	ap_uint<32> gen143_pipex_succbuf [32];
	ap_uint<1> gen144_pipex_var;
	ap_uint<33> gen145_pipex_var;
	ap_uint<1> gen146_pipex_var;
	ap_uint<1> gen147_pipex_var;
	ap_uint<1> gen148_pipex_var;
	ap_uint<1> gen149_pipex_var;
	ap_uint<1> gen150_pipex_var;
	ap_uint<1> gen151_pipex_var;
	ap_uint<1> gen152_pipex_var;
	ap_uint<1> gen153_pipex_var;
	ap_uint<32> gen154_pipex_var;
	ap_uint<1> gen155_pipex_var;
	ap_uint<32> gen156_pipex_var;
	ap_uint<12> gen157_pipex_var;
	ap_uint<1> gen158_pipex_var;
	ap_uint<32> gen159_pipex_var;
	ap_uint<13> gen160_pipex_var;
	ap_uint<1> gen161_pipex_var;
	ap_uint<32> gen162_pipex_var;
	ap_uint<32> gen163_pipex_var;
	ap_uint<21> gen164_pipex_var;
	ap_uint<1> gen165_pipex_var;
	ap_uint<32> gen166_pipex_var;
	ap_uint<1> gen167_pipex_var;
	ap_uint<1> gen168_pipex_var;
	ap_uint<1> gen169_pipex_var;
	ap_uint<1> gen170_pipex_var;
	ap_uint<32> gen171_pipex_var;
	ap_uint<1> gen172_pipex_var;
	ap_uint<1> gen173_pipex_var;
	ap_uint<32> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<1> gen176_pipex_var;
	ap_uint<1> gen177_pipex_var;
	ap_uint<1> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<1> gen180_pipex_var;
	ap_uint<32> gen181_pipex_var;
	ap_uint<32> gen182_pipex_var;
	ap_uint<32> gen183_pipex_var;
	ap_uint<1> gen184_pipex_var;
	ap_uint<1> gen185_pipex_var;
	ap_uint<1> gen186_pipex_var;
	ap_uint<1> gen187_pipex_var;
	ap_uint<1> gen188_pipex_var;
	ap_uint<32> gen189_pipex_var [32];
	ap_uint<32> gen190_pipex_var [32];
	ap_uint<1> gen191_pipex_var;
	ap_uint<1> gen192_pipex_var;
	ap_uint<1> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<1> gen195_pipex_var;
	ap_uint<1> gen196_pipex_var;
	ap_uint<33> gen197_pipex_var;
	ap_uint<33> gen198_pipex_var;
	ap_uint<1> gen199_pipex_var;
	ap_uint<1> gen200_pipex_var;
	ap_uint<33> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<33> gen203_pipex_var;
	ap_uint<1> gen204_pipex_var;
	ap_uint<1> gen205_pipex_var;
	ap_uint<1> gen206_pipex_var;
	ap_uint<1> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<1> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<34> gen211_pipex_var;
	ap_uint<34> gen212_pipex_var;
	ap_uint<33> gen213_pipex_var;
	ap_uint<33> gen214_pipex_var;
	ap_uint<33> gen215_pipex_var;
	ap_uint<64> gen216_pipex_var;
	ap_uint<64> gen217_pipex_var;
	ap_uint<32> gen218_pipex_var;
	ap_uint<1> gen219_pipex_var;
	ap_uint<64> gen220_pipex_var;
	ap_uint<64> gen221_pipex_var;
	ap_uint<33> gen222_pipex_var;
	ap_uint<33> gen223_pipex_var;
	ap_uint<33> gen224_pipex_var;
	ap_uint<1> gen225_pipex_var;
	ap_uint<1> gen226_pipex_var;
	ap_uint<1> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<1> gen235_pipex_var;
	ap_uint<1> gen236_pipex_var;
	ap_uint<33> gen237_pipex_var;
	ap_uint<1> gen238_pipex_var;
	ap_uint<1> gen239_pipex_var;
	ap_uint<1> gen240_pipex_var;
	ap_uint<1> gen241_pipex_var;
	ap_uint<1> gen242_pipex_var;
	ap_uint<1> gen243_pipex_var;
	ap_uint<1> gen244_pipex_var;
	ap_uint<1> gen245_pipex_var;
	ap_uint<1> gen246_pipex_var;
	ap_uint<1> gen247_pipex_var;
	ap_uint<1> gen248_pipex_var;
	ap_uint<1> gen249_pipex_var;
	ap_uint<1> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<1> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<1> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<1> gen263_pipex_var;
	ap_uint<8> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<32> gen266_pipex_var;
	ap_uint<1> gen267_pipex_var;
	ap_uint<32> gen268_pipex_var;
	ap_uint<1> gen269_pipex_var;
	ap_uint<1> gen270_pipex_var;
	ap_uint<1> gen271_pipex_var;
	ap_uint<16> gen272_pipex_var;
	ap_uint<1> gen273_pipex_var;
	ap_uint<32> gen274_pipex_var;
	ap_uint<1> gen275_pipex_var;
	ap_uint<32> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<1> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<32> genpstage_EXEC_curinstr_addr;
	ap_uint<32> genpstage_EXEC_nextinstr_addr;
	riscv_1stage_busreq_mem_struct genpstage_EXEC_instr_busreq;
	ap_uint<1> genpstage_EXEC_instr_req_done;
	ap_uint<32> genpstage_EXEC_instr_code;
	ap_uint<7> genpstage_EXEC_opcode;
	ap_uint<1> genpstage_EXEC_alu_unsigned;
	ap_uint<5> genpstage_EXEC_rs1_addr;
	ap_uint<5> genpstage_EXEC_rs2_addr;
	ap_uint<5> genpstage_EXEC_rd_addr;
	ap_uint<3> genpstage_EXEC_funct3;
	ap_uint<7> genpstage_EXEC_funct7;
	ap_uint<5> genpstage_EXEC_shamt;
	ap_uint<4> genpstage_EXEC_pred;
	ap_uint<4> genpstage_EXEC_succ;
	ap_uint<12> genpstage_EXEC_csrnum;
	ap_uint<5> genpstage_EXEC_zimm;
	ap_uint<32> genpstage_EXEC_immediate_I;
	ap_uint<32> genpstage_EXEC_immediate_S;
	ap_uint<32> genpstage_EXEC_immediate_B;
	ap_uint<32> genpstage_EXEC_immediate_U;
	ap_uint<32> genpstage_EXEC_immediate_J;
	ap_uint<2> genpstage_EXEC_op1_source;
	ap_uint<1> genpstage_EXEC_rd_req;
	ap_uint<3> genpstage_EXEC_rd_source;
	ap_uint<32> genpstage_EXEC_immediate;
	ap_uint<2> genpstage_EXEC_op2_source;
	ap_uint<1> genpstage_EXEC_alu_req;
	ap_uint<4> genpstage_EXEC_alu_opcode;
	ap_uint<1> genpstage_EXEC_jump_req;
	ap_uint<1> genpstage_EXEC_jump_src;
	ap_uint<1> genpstage_EXEC_rs1_req;
	ap_uint<1> genpstage_EXEC_rs2_req;
	ap_uint<1> genpstage_EXEC_jump_req_cond;
	ap_uint<1> genpstage_EXEC_mem_req;
	ap_uint<1> genpstage_EXEC_mem_cmd;
	ap_uint<1> genpstage_EXEC_fencereq;
	ap_uint<1> genpstage_EXEC_ebreakreq;
	ap_uint<1> genpstage_EXEC_ecallreq;
	ap_uint<1> genpstage_EXEC_csrreq;
	ap_uint<4> genpstage_EXEC_mem_be;
	ap_uint<1> genpstage_EXEC_load_signext;
	ap_uint<1> genpstage_EXEC_mret_req;
	ap_uint<32> genpstage_EXEC_rs1_rdata;
	ap_uint<32> genpstage_EXEC_rs2_rdata;
	ap_uint<32> genpstage_EXEC_csr_rdata;
	ap_uint<32> genpstage_EXEC_alu_op1;
	ap_uint<32> genpstage_EXEC_alu_op2;
	ap_uint<33> genpstage_EXEC_alu_op1_wide;
	ap_uint<33> genpstage_EXEC_alu_op2_wide;
	ap_uint<8> genpstage_EXEC_irq_mcause;
	ap_uint<1> genpstage_EXEC_irq_recv;
	ap_uint<33> genpstage_EXEC_alu_result_wide;
	ap_uint<32> genpstage_EXEC_alu_result;
	ap_uint<1> genpstage_EXEC_alu_CF;
	ap_uint<1> genpstage_EXEC_alu_SF;
	ap_uint<1> genpstage_EXEC_alu_ZF;
	ap_uint<1> genpstage_EXEC_alu_OF;
	ap_uint<1> genpstage_EXEC_alu_overflow;
	ap_uint<32> genpstage_EXEC_rd_wdata;
	ap_uint<1> genpstage_EXEC_rd_rdy;
	ap_uint<32> genpstage_EXEC_curinstraddr_imm;
	ap_uint<32> genpstage_EXEC_jump_vector;
	ap_uint<32> genpstage_EXEC_mem_addr;
	ap_uint<32> genpstage_EXEC_mem_wdata;
	riscv_1stage_busreq_mem_struct genpstage_EXEC_data_busreq;
	ap_uint<1> genpstage_EXEC_data_req_done;
	ap_uint<32> genpstage_EXEC_mem_rdata;
	ap_uint<32> gen280_pipex_mcopipe_rdata;
	ap_uint<32> gen281_pipex_mcopipe_rdata;
	genpmodule_riscv_1stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen282_pipex_req_struct;
	genpmodule_riscv_1stage_genmcopipe_data_mem_genstruct_fifo_wdata gen283_pipex_req_struct;
	ap_uint<1> gen122_cyclix_var;
	ap_uint<1> gen123_cyclix_var;
	ap_uint<1> gen124_cyclix_var;
	ap_uint<1> gen125_cyclix_var;
	ap_uint<1> gen126_cyclix_var;
	ap_uint<1> gen127_cyclix_var;
	ap_uint<1> gen128_cyclix_var;
	ap_uint<1> gen129_cyclix_var;
	ap_uint<1> gen130_cyclix_var;
	ap_uint<1> gen131_cyclix_var;
	ap_uint<1> gen132_cyclix_var;
	ap_uint<1> gen133_cyclix_var;
	ap_uint<1> gen134_cyclix_var;
	ap_uint<1> gen135_cyclix_var;
	ap_uint<1> gen136_cyclix_var;
	ap_uint<1> gen137_cyclix_var;
	ap_uint<1> gen138_cyclix_var;
	ap_uint<1> gen139_cyclix_var;
	ap_uint<1> gen140_cyclix_var;
	ap_uint<1> gen141_cyclix_var;
	ap_uint<1> gen142_cyclix_var;
	ap_uint<1> gen143_cyclix_var;
	ap_uint<1> gen144_cyclix_var;
	ap_uint<1> gen145_cyclix_var;
	ap_uint<1> gen146_cyclix_var;
	ap_uint<1> gen147_cyclix_var;
	ap_uint<1> gen148_cyclix_var;
	ap_uint<1> gen149_cyclix_var;
	ap_uint<1> gen150_cyclix_var;
	ap_uint<1> gen151_cyclix_var;
	ap_uint<1> gen152_cyclix_var;
	ap_uint<1> gen153_cyclix_var;
	ap_uint<1> gen154_cyclix_var;
	ap_uint<1> gen155_cyclix_var;
	ap_uint<1> gen156_cyclix_var;
	ap_uint<1> gen157_cyclix_var;
	ap_uint<1> gen158_cyclix_var;
	ap_uint<1> gen159_cyclix_var;
	ap_uint<1> gen160_cyclix_var;
	ap_uint<1> gen161_cyclix_var;
	ap_uint<1> gen162_cyclix_var;
	ap_uint<1> gen163_cyclix_var;
	ap_uint<1> gen164_cyclix_var;
	ap_uint<1> gen165_cyclix_var;
	ap_uint<1> gen166_cyclix_var;
	ap_uint<1> gen167_cyclix_var;
	ap_uint<1> gen168_cyclix_var;
	ap_uint<1> gen169_cyclix_var;
	ap_uint<1> gen170_cyclix_var;
	ap_uint<1> gen171_cyclix_var;
	ap_uint<1> gen172_cyclix_var;
	ap_uint<1> gen173_cyclix_var;
	ap_uint<1> gen174_cyclix_var;
	ap_uint<1> gen175_cyclix_var;
	ap_uint<1> gen176_cyclix_var;
	ap_uint<1> gen177_cyclix_var;
	ap_uint<1> gen178_cyclix_var;
	ap_uint<1> gen179_cyclix_var;
	ap_uint<1> gen180_cyclix_var;
	ap_uint<1> gen181_cyclix_var;
	ap_uint<1> gen182_cyclix_var;
	ap_uint<1> gen183_cyclix_var;
	ap_uint<1> gen184_cyclix_var;
	ap_uint<1> gen185_cyclix_var;
	ap_uint<1> gen186_cyclix_var;
	ap_uint<1> gen187_cyclix_var;
	ap_uint<1> gen188_cyclix_var;
	ap_uint<1> gen189_cyclix_var;
	ap_uint<1> gen190_cyclix_var;
	ap_uint<1> gen191_cyclix_var;
	ap_uint<1> gen192_cyclix_var;
	ap_uint<1> gen193_cyclix_var;
	ap_uint<1> gen194_cyclix_var;
	ap_uint<1> gen195_cyclix_var;
	ap_uint<1> gen196_cyclix_var;
	ap_uint<1> gen197_cyclix_var;
	ap_uint<1> gen198_cyclix_var;
	ap_uint<1> gen199_cyclix_var;
	ap_uint<1> gen200_cyclix_var;
	ap_uint<1> gen201_cyclix_var;
	ap_uint<1> gen202_cyclix_var;
	ap_uint<1> gen203_cyclix_var;
	ap_uint<1> gen204_cyclix_var;
	ap_uint<1> gen205_cyclix_var;
	ap_uint<1> gen206_cyclix_var;
	ap_uint<1> gen207_cyclix_var;
	ap_uint<1> gen208_cyclix_var;
	ap_uint<1> gen209_cyclix_var;
	ap_uint<1> gen210_cyclix_var;
	ap_uint<1> gen211_cyclix_var;
	ap_uint<1> gen212_cyclix_var;
	ap_uint<1> gen213_cyclix_var;
	ap_uint<1> gen214_cyclix_var;
	ap_uint<1> gen215_cyclix_var;
	ap_uint<1> gen216_cyclix_var;
	ap_uint<1> gen217_cyclix_var;
	ap_uint<1> gen218_cyclix_var;
	ap_uint<1> gen219_cyclix_var;
	ap_uint<1> gen220_cyclix_var;
	ap_uint<1> gen221_cyclix_var;
	ap_uint<1> gen222_cyclix_var;
	ap_uint<1> gen223_cyclix_var;
	ap_uint<1> gen224_cyclix_var;
	ap_uint<1> gen225_cyclix_var;
	ap_uint<1> gen226_cyclix_var;
	ap_uint<1> gen227_cyclix_var;
	ap_uint<1> gen228_cyclix_var;
	ap_uint<1> gen229_cyclix_var;
	ap_uint<1> gen230_cyclix_var;
	ap_uint<1> gen231_cyclix_var;
	ap_uint<1> gen232_cyclix_var;
	ap_uint<1> gen233_cyclix_var;
	ap_uint<1> gen234_cyclix_var;
	ap_uint<1> gen235_cyclix_var;
	ap_uint<1> gen236_cyclix_var;
	ap_uint<1> gen237_cyclix_var;
	ap_uint<1> gen238_cyclix_var;
	ap_uint<1> gen239_cyclix_var;
	ap_uint<1> gen240_cyclix_var;
	ap_uint<1> gen241_cyclix_var;
	ap_uint<1> gen242_cyclix_var;
	ap_uint<1> gen243_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = ap_uint<32>(512);
		genpsticky_glbl_regfile[1] = ap_uint<32>(0);
		genpsticky_glbl_regfile[2] = ap_uint<32>(0);
		genpsticky_glbl_regfile[3] = ap_uint<32>(0);
		genpsticky_glbl_regfile[4] = ap_uint<32>(0);
		genpsticky_glbl_regfile[5] = ap_uint<32>(0);
		genpsticky_glbl_regfile[6] = ap_uint<32>(0);
		genpsticky_glbl_regfile[7] = ap_uint<32>(0);
		genpsticky_glbl_regfile[8] = ap_uint<32>(0);
		genpsticky_glbl_regfile[9] = ap_uint<32>(0);
		genpsticky_glbl_regfile[10] = ap_uint<32>(0);
		genpsticky_glbl_regfile[11] = ap_uint<32>(0);
		genpsticky_glbl_regfile[12] = ap_uint<32>(0);
		genpsticky_glbl_regfile[13] = ap_uint<32>(0);
		genpsticky_glbl_regfile[14] = ap_uint<32>(0);
		genpsticky_glbl_regfile[15] = ap_uint<32>(0);
		genpsticky_glbl_regfile[16] = ap_uint<32>(0);
		genpsticky_glbl_regfile[17] = ap_uint<32>(0);
		genpsticky_glbl_regfile[18] = ap_uint<32>(0);
		genpsticky_glbl_regfile[19] = ap_uint<32>(0);
		genpsticky_glbl_regfile[20] = ap_uint<32>(0);
		genpsticky_glbl_regfile[21] = ap_uint<32>(0);
		genpsticky_glbl_regfile[22] = ap_uint<32>(0);
		genpsticky_glbl_regfile[23] = ap_uint<32>(0);
		genpsticky_glbl_regfile[24] = ap_uint<32>(0);
		genpsticky_glbl_regfile[25] = ap_uint<32>(0);
		genpsticky_glbl_regfile[26] = ap_uint<32>(0);
		genpsticky_glbl_regfile[27] = ap_uint<32>(0);
		genpsticky_glbl_regfile[28] = ap_uint<32>(0);
		genpsticky_glbl_regfile[29] = ap_uint<32>(0);
		genpsticky_glbl_regfile[30] = ap_uint<32>(0);
		genpsticky_glbl_regfile[31] = ap_uint<32>(0);
		genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
		genpsticky_glbl_jump_vector_cmd = ap_uint<32>(0);
		genpsticky_glbl_CSR_MCAUSE = ap_uint<32>(0);
		genpsticky_glbl_MIRQEN = ap_uint<32>(1);
		genpsticky_glbl_MRETADDR = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
		genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_instr_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_full_flag = ap_uint<32>(0);
		genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_data_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_rd_ptr = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);

	} else {
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genpsticky_glbl_pc_buf = genpsticky_glbl_pc;
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[1];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[2];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[3];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[4];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[5];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[6];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[7];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[8];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[9];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[10];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[11];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[12];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[13];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[14];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[15];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[16];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[17];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[18];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[19];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[20];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[21];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[22];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[23];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[24];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[25];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[26];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[27];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[28];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[29];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[30];
		genpsticky_glbl_regfile_buf = genpsticky_glbl_regfile[31];
		genpsticky_glbl_jump_req_cmd_buf = genpsticky_glbl_jump_req_cmd;
		genpsticky_glbl_jump_vector_cmd_buf = genpsticky_glbl_jump_vector_cmd;
		genpsticky_glbl_CSR_MCAUSE_buf = genpsticky_glbl_CSR_MCAUSE;
		genpsticky_glbl_MIRQEN_buf = genpsticky_glbl_MIRQEN;
		genpsticky_glbl_MRETADDR_buf = genpsticky_glbl_MRETADDR;
		genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genctrl_working = ap_uint<32>(0);
		gen122_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen122_cyclix_var) {
			genpstage_EXEC_genctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
		}
		gen123_cyclix_var = ap_uint<1>(0);
		gen123_cyclix_var = (gen123_cyclix_var || gen122_cyclix_var);
		gen123_cyclix_var = !gen123_cyclix_var;
		if (gen123_cyclix_var) {
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
			genpstage_EXEC_genctrl_new = genpstage_EXEC_genctrl_active;
		}
		genpstage_EXEC_genctrl_occupied = genpstage_EXEC_genctrl_active;
		genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		gen124_cyclix_var = genpstage_EXEC_genctrl_occupied;
		if (gen124_cyclix_var) {
			gen125_cyclix_var = genpstage_EXEC_genctrl_new;
			if (gen125_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
			genpstage_EXEC_instr_req_done = genpstage_EXEC_TRX_BUF[0].instr_req_done;
			genpstage_EXEC_irq_recv = genpstage_EXEC_TRX_BUF[0].irq_recv;
			genpstage_EXEC_irq_mcause = genpstage_EXEC_TRX_BUF[0].irq_mcause;
			genpstage_EXEC_data_req_done = genpstage_EXEC_TRX_BUF[0].data_req_done;
			gen126_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen126_cyclix_var) {
				gen127_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen128_cyclix_var = gen127_cyclix_var;
				if (gen128_cyclix_var) {
					gen129_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen130_cyclix_var = gen129_cyclix_var;
					if (gen130_cyclix_var) {
						gen131_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen280_pipex_mcopipe_rdata);
						gen132_cyclix_var = gen131_cyclix_var;
						if (gen132_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen280_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen133_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
			if (gen133_cyclix_var) {
				gen134_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.if_id == ap_uint<1>(0));
				gen135_cyclix_var = gen134_cyclix_var;
				if (gen135_cyclix_var) {
					gen136_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.tid == genmcopipe_data_mem_rd_ptr);
					gen137_cyclix_var = gen136_cyclix_var;
					if (gen137_cyclix_var) {
						gen138_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen281_pipex_mcopipe_rdata);
						gen139_cyclix_var = gen138_cyclix_var;
						if (gen139_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen281_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen140_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen140_cyclix_var) {
			}
		}
		gen137_pipex_succbuf = genpsticky_glbl_jump_req_cmd;
		gen139_pipex_succbuf = genpsticky_glbl_pc;
		gen141_pipex_succbuf = genpsticky_glbl_jump_vector_cmd;
		gen143_pipex_succbuf = genpsticky_glbl_regfile[1];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[2];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[3];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[4];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[5];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[6];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[7];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[8];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[9];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[10];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[11];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[12];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[13];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[14];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[15];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[16];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[17];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[18];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[19];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[20];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[21];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[22];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[23];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[24];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[25];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[26];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[27];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[28];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[29];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[30];
		gen143_pipex_succbuf = genpsticky_glbl_regfile[31];
		genpstage_EXEC_curinstr_addr = genpsticky_glbl_pc;
		gen144_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen141_cyclix_var = gen144_pipex_var;
		if (gen141_cyclix_var) {
			genpstage_EXEC_curinstr_addr = genpsticky_glbl_jump_vector_cmd;
		}
		gen136_pipex_succreq = ap_uint<32>(1);
		gen137_pipex_succbuf = ap_uint<32>(0);
		gen145_pipex_var = (genpstage_EXEC_curinstr_addr + ap_uint<32>(4));
		genpstage_EXEC_nextinstr_addr = gen145_pipex_var;
		gen138_pipex_succreq = ap_uint<32>(1);
		gen139_pipex_succbuf = genpstage_EXEC_nextinstr_addr;
		genpstage_EXEC_instr_busreq = genpstage_EXEC_curinstr_addr;
		genpstage_EXEC_instr_busreq = ap_uint<32>(15);
		genpstage_EXEC_instr_busreq = ap_uint<32>(0);
		gen146_pipex_var = ~genpstage_EXEC_instr_req_done;
		gen147_pipex_var = gen146_pipex_var;
		gen142_cyclix_var = gen147_pipex_var;
		if (gen142_cyclix_var) {
			gen143_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen143_cyclix_var) {
				gen144_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen145_cyclix_var = gen144_cyclix_var;
				if (gen145_cyclix_var) {
					gen282_pipex_req_struct = ap_uint<1>(0);
					gen282_pipex_req_struct = genpstage_EXEC_instr_busreq;
					gen146_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen282_pipex_req_struct);
					gen147_cyclix_var = gen146_cyclix_var;
					if (gen147_cyclix_var) {
						gen148_pipex_var = ap_uint<32>(1);
						gen148_cyclix_var = !ap_uint<1>(0);
						genpstage_EXEC_TRX_BUF = gen148_cyclix_var;
						genpstage_EXEC_TRX_BUF = genmcopipe_instr_mem_wr_ptr;
						genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
						gen149_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
						if (gen149_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_EXEC_instr_req_done = gen148_pipex_var;
			gen150_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen150_cyclix_var) {
				genpstage_EXEC_TRX_BUF = gen148_pipex_var;
			}
		}
		gen149_pipex_var = ~genpstage_EXEC_instr_req_done;
		gen150_pipex_var = gen149_pipex_var;
		gen151_cyclix_var = gen150_pipex_var;
		if (gen151_cyclix_var) {
			gen152_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen152_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		gen153_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		if (gen153_cyclix_var) {
			genpstage_EXEC_instr_code = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
		}
		gen151_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		gen152_pipex_var = ~gen151_pipex_var;
		gen153_pipex_var = gen152_pipex_var;
		gen154_cyclix_var = gen153_pipex_var;
		if (gen154_cyclix_var) {
			gen155_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen155_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		genpstage_EXEC_opcode = genpstage_EXEC_instr_code[6:0];
		genpstage_EXEC_alu_unsigned = ap_uint<32>(0);
		genpstage_EXEC_rs1_addr = genpstage_EXEC_instr_code[19:15];
		genpstage_EXEC_rs2_addr = genpstage_EXEC_instr_code[24:20];
		genpstage_EXEC_rd_addr = genpstage_EXEC_instr_code[11:7];
		genpstage_EXEC_funct3 = genpstage_EXEC_instr_code[14:12];
		genpstage_EXEC_funct7 = genpstage_EXEC_instr_code[31:25];
		genpstage_EXEC_shamt = genpstage_EXEC_instr_code[24:20];
		genpstage_EXEC_pred = genpstage_EXEC_instr_code[27:24];
		genpstage_EXEC_succ = genpstage_EXEC_instr_code[23:20];
		genpstage_EXEC_csrnum = genpstage_EXEC_instr_code[31:20];
		genpstage_EXEC_zimm = genpstage_EXEC_instr_code[19:15];
		gen154_pipex_var = genpstage_EXEC_instr_code[31:20];
		gen155_pipex_var = gen154_pipex_var[31];
		gen156_pipex_var = gen155_pipex_var.concat((ap_uint<31>)gen155_pipex_var.concat((ap_uint<30>)gen155_pipex_var.concat((ap_uint<29>)gen155_pipex_var.concat((ap_uint<28>)gen155_pipex_var.concat((ap_uint<27>)gen155_pipex_var.concat((ap_uint<26>)gen155_pipex_var.concat((ap_uint<25>)gen155_pipex_var.concat((ap_uint<24>)gen155_pipex_var.concat((ap_uint<23>)gen155_pipex_var.concat((ap_uint<22>)gen155_pipex_var.concat((ap_uint<21>)gen155_pipex_var.concat((ap_uint<20>)gen155_pipex_var.concat((ap_uint<19>)gen155_pipex_var.concat((ap_uint<18>)gen155_pipex_var.concat((ap_uint<17>)gen155_pipex_var.concat((ap_uint<16>)gen155_pipex_var.concat((ap_uint<15>)gen155_pipex_var.concat((ap_uint<14>)gen155_pipex_var.concat((ap_uint<13>)gen155_pipex_var.concat((ap_uint<12>)genpstage_EXEC_instr_code[31:20]))))))))))))))))))));
		genpstage_EXEC_immediate_I = gen156_pipex_var;
		gen157_pipex_var = genpstage_EXEC_instr_code[31:25].concat((ap_uint<5>)genpstage_EXEC_instr_code[11:7]);
		gen158_pipex_var = gen157_pipex_var[11];
		gen159_pipex_var = gen158_pipex_var.concat((ap_uint<31>)gen158_pipex_var.concat((ap_uint<30>)gen158_pipex_var.concat((ap_uint<29>)gen158_pipex_var.concat((ap_uint<28>)gen158_pipex_var.concat((ap_uint<27>)gen158_pipex_var.concat((ap_uint<26>)gen158_pipex_var.concat((ap_uint<25>)gen158_pipex_var.concat((ap_uint<24>)gen158_pipex_var.concat((ap_uint<23>)gen158_pipex_var.concat((ap_uint<22>)gen158_pipex_var.concat((ap_uint<21>)gen158_pipex_var.concat((ap_uint<20>)gen158_pipex_var.concat((ap_uint<19>)gen158_pipex_var.concat((ap_uint<18>)gen158_pipex_var.concat((ap_uint<17>)gen158_pipex_var.concat((ap_uint<16>)gen158_pipex_var.concat((ap_uint<15>)gen158_pipex_var.concat((ap_uint<14>)gen158_pipex_var.concat((ap_uint<13>)gen158_pipex_var.concat((ap_uint<12>)gen157_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_S = gen159_pipex_var;
		gen160_pipex_var = genpstage_EXEC_instr_code[31].concat((ap_uint<12>)genpstage_EXEC_instr_code[7].concat((ap_uint<11>)genpstage_EXEC_instr_code[30:25].concat((ap_uint<5>)genpstage_EXEC_instr_code[11:8].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen161_pipex_var = gen160_pipex_var[12];
		gen162_pipex_var = gen161_pipex_var.concat((ap_uint<31>)gen161_pipex_var.concat((ap_uint<30>)gen161_pipex_var.concat((ap_uint<29>)gen161_pipex_var.concat((ap_uint<28>)gen161_pipex_var.concat((ap_uint<27>)gen161_pipex_var.concat((ap_uint<26>)gen161_pipex_var.concat((ap_uint<25>)gen161_pipex_var.concat((ap_uint<24>)gen161_pipex_var.concat((ap_uint<23>)gen161_pipex_var.concat((ap_uint<22>)gen161_pipex_var.concat((ap_uint<21>)gen161_pipex_var.concat((ap_uint<20>)gen161_pipex_var.concat((ap_uint<19>)gen161_pipex_var.concat((ap_uint<18>)gen161_pipex_var.concat((ap_uint<17>)gen161_pipex_var.concat((ap_uint<16>)gen161_pipex_var.concat((ap_uint<15>)gen161_pipex_var.concat((ap_uint<14>)gen161_pipex_var.concat((ap_uint<13>)gen160_pipex_var)))))))))))))))))));
		genpstage_EXEC_immediate_B = gen162_pipex_var;
		gen163_pipex_var = genpstage_EXEC_instr_code[31:12].concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_immediate_U = gen163_pipex_var;
		gen164_pipex_var = genpstage_EXEC_instr_code[31].concat((ap_uint<20>)genpstage_EXEC_instr_code[19:12].concat((ap_uint<12>)genpstage_EXEC_instr_code[20].concat((ap_uint<11>)genpstage_EXEC_instr_code[30:21].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen165_pipex_var = gen164_pipex_var[20];
		gen166_pipex_var = gen165_pipex_var.concat((ap_uint<31>)gen165_pipex_var.concat((ap_uint<30>)gen165_pipex_var.concat((ap_uint<29>)gen165_pipex_var.concat((ap_uint<28>)gen165_pipex_var.concat((ap_uint<27>)gen165_pipex_var.concat((ap_uint<26>)gen165_pipex_var.concat((ap_uint<25>)gen165_pipex_var.concat((ap_uint<24>)gen165_pipex_var.concat((ap_uint<23>)gen165_pipex_var.concat((ap_uint<22>)gen165_pipex_var.concat((ap_uint<21>)gen164_pipex_var)))))))))));
		genpstage_EXEC_immediate_J = gen166_pipex_var;
		switch (genpstage_EXEC_opcode) {
			case 55:
				genpstage_EXEC_op1_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 23:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 111:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_J;
				break;
			case 103:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 99:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_B;
				gen167_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(6));
				gen168_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(7));
				gen169_pipex_var = (gen167_pipex_var | gen168_pipex_var);
				gen170_pipex_var = gen169_pipex_var;
				gen156_cyclix_var = gen170_pipex_var;
				if (gen156_cyclix_var) {
					genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(5);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 35:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_S;
				break;
			case 19:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen171_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_instr_code[24:20]);
						genpstage_EXEC_immediate = gen171_pipex_var;
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen172_pipex_var = genpstage_EXEC_instr_code[30];
						gen157_cyclix_var = gen172_pipex_var;
						if (gen157_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen173_pipex_var = ap_uint<1>(0);
						gen173_pipex_var = (gen173_pipex_var || gen172_pipex_var);
						gen173_pipex_var = !gen173_pipex_var;
						gen158_cyclix_var = gen173_pipex_var;
						if (gen158_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen174_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_instr_code[24:20]);
						genpstage_EXEC_immediate = gen174_pipex_var;
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen175_pipex_var = genpstage_EXEC_instr_code[30];
						gen159_cyclix_var = gen175_pipex_var;
						if (gen159_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						}
						gen176_pipex_var = ap_uint<1>(0);
						gen176_pipex_var = (gen176_pipex_var || gen175_pipex_var);
						gen176_pipex_var = !gen176_pipex_var;
						gen160_cyclix_var = gen176_pipex_var;
						if (gen160_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen177_pipex_var = genpstage_EXEC_instr_code[30];
						gen161_cyclix_var = gen177_pipex_var;
						if (gen161_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen178_pipex_var = ap_uint<1>(0);
						gen178_pipex_var = (gen178_pipex_var || gen177_pipex_var);
						gen178_pipex_var = !gen178_pipex_var;
						gen162_cyclix_var = gen178_pipex_var;
						if (gen162_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 15:
				genpstage_EXEC_fencereq = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen179_pipex_var = genpstage_EXEC_instr_code[20];
						gen163_cyclix_var = gen179_pipex_var;
						if (gen163_cyclix_var) {
							genpstage_EXEC_ebreakreq = ap_uint<32>(1);
						}
						gen180_pipex_var = ap_uint<1>(0);
						gen180_pipex_var = (gen180_pipex_var || gen179_pipex_var);
						gen180_pipex_var = !gen180_pipex_var;
						gen164_cyclix_var = gen180_pipex_var;
						if (gen164_cyclix_var) {
							genpstage_EXEC_ecallreq = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen181_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen181_pipex_var;
						break;
					case 6:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen182_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen182_pipex_var;
						break;
					case 7:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen183_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen183_pipex_var;
						break;
				}
				break;
		}
		gen184_pipex_var = genpstage_EXEC_mem_req;
		gen165_cyclix_var = gen184_pipex_var;
		if (gen165_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					genpstage_EXEC_load_signext = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					genpstage_EXEC_load_signext = ap_uint<32>(1);
					break;
				case 2:
					genpstage_EXEC_mem_be = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
			}
		}
		gen185_pipex_var = (genpstage_EXEC_instr_code == ap_uint<32>(807403635));
		gen186_pipex_var = gen185_pipex_var;
		gen166_cyclix_var = gen186_pipex_var;
		if (gen166_cyclix_var) {
			genpstage_EXEC_mret_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
			genpstage_EXEC_jump_src = ap_uint<32>(0);
			genpstage_EXEC_immediate = genpsticky_glbl_MRETADDR;
		}
		gen187_pipex_var = (genpstage_EXEC_rd_addr == ap_uint<32>(0));
		gen188_pipex_var = gen187_pipex_var;
		gen167_cyclix_var = gen188_pipex_var;
		if (gen167_cyclix_var) {
			genpstage_EXEC_rd_req = ap_uint<32>(0);
		}
		gen189_pipex_var = genpsticky_glbl_regfile_buf[1];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[2];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[3];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[4];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[5];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[6];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[7];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[8];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[9];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[10];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[11];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[12];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[13];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[14];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[15];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[16];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[17];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[18];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[19];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[20];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[21];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[22];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[23];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[24];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[25];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[26];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[27];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[28];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[29];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[30];
		gen189_pipex_var = genpsticky_glbl_regfile_buf[31];
		genpstage_EXEC_rs1_rdata = gen189_pipex_var[genpstage_EXEC_rs1_addr];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[1];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[2];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[3];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[4];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[5];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[6];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[7];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[8];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[9];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[10];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[11];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[12];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[13];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[14];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[15];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[16];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[17];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[18];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[19];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[20];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[21];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[22];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[23];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[24];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[25];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[26];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[27];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[28];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[29];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[30];
		gen190_pipex_var = genpsticky_glbl_regfile_buf[31];
		genpstage_EXEC_rs2_rdata = gen190_pipex_var[genpstage_EXEC_rs2_addr];
		gen191_pipex_var = (genpstage_EXEC_rs1_addr == ap_uint<32>(0));
		gen192_pipex_var = gen191_pipex_var;
		gen168_cyclix_var = gen192_pipex_var;
		if (gen168_cyclix_var) {
			genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
		}
		gen193_pipex_var = (genpstage_EXEC_rs2_addr == ap_uint<32>(0));
		gen194_pipex_var = gen193_pipex_var;
		gen169_cyclix_var = gen194_pipex_var;
		if (gen169_cyclix_var) {
			genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
		}
		gen195_pipex_var = genpstage_EXEC_csrreq;
		gen170_cyclix_var = gen195_pipex_var;
		if (gen170_cyclix_var) {
			genpstage_EXEC_csr_rdata = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_alu_op1 = genpstage_EXEC_rs1_rdata;
		switch (genpstage_EXEC_op1_source) {
			case 1:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_curinstr_addr;
				break;
		}
		genpstage_EXEC_alu_op2 = genpstage_EXEC_rs2_rdata;
		switch (genpstage_EXEC_op2_source) {
			case 1:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_csr_rdata;
				break;
		}
		gen196_pipex_var = genpstage_EXEC_alu_unsigned;
		gen171_cyclix_var = gen196_pipex_var;
		if (gen171_cyclix_var) {
			gen197_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen197_pipex_var;
			gen198_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen198_pipex_var;
		}
		gen199_pipex_var = ap_uint<1>(0);
		gen199_pipex_var = (gen199_pipex_var || gen196_pipex_var);
		gen199_pipex_var = !gen199_pipex_var;
		gen172_cyclix_var = gen199_pipex_var;
		if (gen172_cyclix_var) {
			gen200_pipex_var = genpstage_EXEC_alu_op1[31];
			gen201_pipex_var = gen200_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen201_pipex_var;
			gen202_pipex_var = genpstage_EXEC_alu_op2[31];
			gen203_pipex_var = gen202_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen203_pipex_var;
		}
		gen204_pipex_var = genpsticky_glbl_MIRQEN;
		gen173_cyclix_var = gen204_pipex_var;
		if (gen173_cyclix_var) {
			gen205_pipex_var = ~genpstage_EXEC_irq_recv;
			gen206_pipex_var = gen205_pipex_var;
			gen174_cyclix_var = gen206_pipex_var;
			if (gen174_cyclix_var) {
				gen175_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen175_cyclix_var) {
					gen176_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_irq_mcause);
					gen207_pipex_var = gen176_cyclix_var;
				}
				genpstage_EXEC_irq_recv = gen207_pipex_var;
				gen177_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen177_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen207_pipex_var;
				}
				genpstage_EXEC_irq_mcause = genpstage_EXEC_irq_mcause;
				gen178_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen178_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_irq_mcause;
				}
			}
			gen208_pipex_var = genpstage_EXEC_irq_recv;
			gen179_cyclix_var = gen208_pipex_var;
			if (gen179_cyclix_var) {
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
				genpstage_EXEC_jump_src = ap_uint<32>(0);
				genpstage_EXEC_rs1_req = ap_uint<32>(0);
				genpstage_EXEC_rs2_req = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(0);
				genpstage_EXEC_immediate = ap_uint<32>(128);
				genpstage_EXEC_fencereq = ap_uint<32>(0);
				genpstage_EXEC_ecallreq = ap_uint<32>(0);
				genpstage_EXEC_ebreakreq = ap_uint<32>(0);
				genpstage_EXEC_csrreq = ap_uint<32>(0);
				genpstage_EXEC_alu_req = ap_uint<32>(0);
				genpstage_EXEC_mem_req = ap_uint<32>(0);
				gen180_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen180_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(0);
				}
				gen181_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen181_cyclix_var) {
					genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_irq_mcause;
				}
				gen182_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen182_cyclix_var) {
					genpsticky_glbl_MRETADDR = genpstage_EXEC_curinstr_addr;
				}
			}
		}
		gen209_pipex_var = genpstage_EXEC_mret_req;
		gen183_cyclix_var = gen209_pipex_var;
		if (gen183_cyclix_var) {
			gen184_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen184_cyclix_var) {
				genpsticky_glbl_MIRQEN = ap_uint<32>(1);
			}
		}
		genpstage_EXEC_alu_result_wide = genpstage_EXEC_alu_op1_wide;
		gen210_pipex_var = genpstage_EXEC_alu_req;
		gen185_cyclix_var = gen210_pipex_var;
		if (gen185_cyclix_var) {
			switch (genpstage_EXEC_alu_opcode) {
				case 0:
					gen211_pipex_var = (genpstage_EXEC_alu_op1_wide + genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen211_pipex_var;
					break;
				case 1:
					gen212_pipex_var = (genpstage_EXEC_alu_op1_wide - genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen212_pipex_var;
					break;
				case 2:
					gen213_pipex_var = (genpstage_EXEC_alu_op1_wide & genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen213_pipex_var;
					break;
				case 3:
					gen214_pipex_var = (genpstage_EXEC_alu_op1_wide | genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen214_pipex_var;
					break;
				case 4:
					gen215_pipex_var = (genpstage_EXEC_alu_op1_wide << genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen215_pipex_var;
					break;
				case 5:
					gen216_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1_wide[31:0]);
					gen217_pipex_var = (gen216_pipex_var >> genpstage_EXEC_alu_op2_wide[4:0]);
					genpstage_EXEC_alu_result_wide = gen217_pipex_var;
					break;
				case 6:
					gen218_pipex_var = genpstage_EXEC_alu_op1_wide[31:0];
					gen219_pipex_var = gen218_pipex_var[31];
					gen220_pipex_var = gen219_pipex_var.concat((ap_uint<63>)gen219_pipex_var.concat((ap_uint<62>)gen219_pipex_var.concat((ap_uint<61>)gen219_pipex_var.concat((ap_uint<60>)gen219_pipex_var.concat((ap_uint<59>)gen219_pipex_var.concat((ap_uint<58>)gen219_pipex_var.concat((ap_uint<57>)gen219_pipex_var.concat((ap_uint<56>)gen219_pipex_var.concat((ap_uint<55>)gen219_pipex_var.concat((ap_uint<54>)gen219_pipex_var.concat((ap_uint<53>)gen219_pipex_var.concat((ap_uint<52>)gen219_pipex_var.concat((ap_uint<51>)gen219_pipex_var.concat((ap_uint<50>)gen219_pipex_var.concat((ap_uint<49>)gen219_pipex_var.concat((ap_uint<48>)gen219_pipex_var.concat((ap_uint<47>)gen219_pipex_var.concat((ap_uint<46>)gen219_pipex_var.concat((ap_uint<45>)gen219_pipex_var.concat((ap_uint<44>)gen219_pipex_var.concat((ap_uint<43>)gen219_pipex_var.concat((ap_uint<42>)gen219_pipex_var.concat((ap_uint<41>)gen219_pipex_var.concat((ap_uint<40>)gen219_pipex_var.concat((ap_uint<39>)gen219_pipex_var.concat((ap_uint<38>)gen219_pipex_var.concat((ap_uint<37>)gen219_pipex_var.concat((ap_uint<36>)gen219_pipex_var.concat((ap_uint<35>)gen219_pipex_var.concat((ap_uint<34>)gen219_pipex_var.concat((ap_uint<33>)gen219_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1_wide[31:0]))))))))))))))))))))))))))))))));
					gen221_pipex_var = (gen220_pipex_var >> genpstage_EXEC_alu_op2_wide[4:0]);
					genpstage_EXEC_alu_result_wide = gen221_pipex_var;
					break;
				case 7:
					gen222_pipex_var = (genpstage_EXEC_alu_op1_wide ^ genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen222_pipex_var;
					break;
				case 8:
					gen223_pipex_var = ~genpstage_EXEC_alu_op2_wide;
					gen224_pipex_var = (genpstage_EXEC_alu_op1_wide & gen223_pipex_var);
					genpstage_EXEC_alu_result_wide = gen224_pipex_var;
					break;
			}
			genpstage_EXEC_alu_result = genpstage_EXEC_alu_result_wide[31:0];
			genpstage_EXEC_alu_CF = genpstage_EXEC_alu_result_wide[32];
			genpstage_EXEC_alu_SF = genpstage_EXEC_alu_result_wide[31];
			gen225_pipex_var = |genpstage_EXEC_alu_result;
			gen226_pipex_var = ~gen225_pipex_var;
			genpstage_EXEC_alu_ZF = gen226_pipex_var;
			gen227_pipex_var = ~genpstage_EXEC_alu_op1[31];
			gen228_pipex_var = ~genpstage_EXEC_alu_op2[31];
			gen229_pipex_var = (gen227_pipex_var & gen228_pipex_var);
			gen230_pipex_var = (gen229_pipex_var & genpstage_EXEC_alu_result[31]);
			gen231_pipex_var = ~genpstage_EXEC_alu_result[31];
			gen232_pipex_var = (genpstage_EXEC_alu_op1[31] & genpstage_EXEC_alu_op2[31]);
			gen233_pipex_var = (gen232_pipex_var & gen231_pipex_var);
			gen234_pipex_var = (gen230_pipex_var | gen233_pipex_var);
			genpstage_EXEC_alu_OF = gen234_pipex_var;
			gen235_pipex_var = genpstage_EXEC_alu_unsigned;
			gen186_cyclix_var = gen235_pipex_var;
			if (gen186_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_CF;
			}
			gen236_pipex_var = ap_uint<1>(0);
			gen236_pipex_var = (gen236_pipex_var || gen235_pipex_var);
			gen236_pipex_var = !gen236_pipex_var;
			gen187_cyclix_var = gen236_pipex_var;
			if (gen187_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_OF;
			}
		}
		switch (genpstage_EXEC_rd_source) {
			case 0:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_immediate;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_result;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_CF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_OF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_nextinstr_addr;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_csr_rdata;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
		}
		gen237_pipex_var = (genpstage_EXEC_curinstr_addr + genpstage_EXEC_immediate);
		genpstage_EXEC_curinstraddr_imm = gen237_pipex_var;
		switch (genpstage_EXEC_jump_src) {
			case 0:
				genpstage_EXEC_jump_vector = genpstage_EXEC_immediate;
				break;
			case 1:
				genpstage_EXEC_jump_vector = genpstage_EXEC_alu_result;
				break;
		}
		gen238_pipex_var = genpstage_EXEC_jump_req_cond;
		gen188_cyclix_var = gen238_pipex_var;
		if (gen188_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					gen239_pipex_var = genpstage_EXEC_alu_ZF;
					gen189_cyclix_var = gen239_pipex_var;
					if (gen189_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 1:
					gen240_pipex_var = ~genpstage_EXEC_alu_ZF;
					gen241_pipex_var = gen240_pipex_var;
					gen190_cyclix_var = gen241_pipex_var;
					if (gen190_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 4:
					gen242_pipex_var = genpstage_EXEC_alu_CF;
					gen191_cyclix_var = gen242_pipex_var;
					if (gen191_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 5:
					gen243_pipex_var = ~genpstage_EXEC_alu_CF;
					gen244_pipex_var = gen243_pipex_var;
					gen192_cyclix_var = gen244_pipex_var;
					if (gen192_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 6:
					gen245_pipex_var = genpstage_EXEC_alu_CF;
					gen193_cyclix_var = gen245_pipex_var;
					if (gen193_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 7:
					gen246_pipex_var = ~genpstage_EXEC_alu_CF;
					gen247_pipex_var = gen246_pipex_var;
					gen194_cyclix_var = gen247_pipex_var;
					if (gen194_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_mem_addr = genpstage_EXEC_alu_result;
		genpstage_EXEC_mem_wdata = genpstage_EXEC_rs2_rdata;
		gen136_pipex_succreq = ap_uint<32>(1);
		gen137_pipex_succbuf = genpstage_EXEC_jump_req;
		gen140_pipex_succreq = ap_uint<32>(1);
		gen141_pipex_succbuf = genpstage_EXEC_jump_vector;
		gen248_pipex_var = genpstage_EXEC_jump_req;
		gen195_cyclix_var = gen248_pipex_var;
		if (gen195_cyclix_var) {
			genpstage_EXEC_genpctrl_flushreq = (genpstage_EXEC_genpctrl_flushreq | genpstage_EXEC_genctrl_active);
		}
		gen249_pipex_var = genpstage_EXEC_mem_req;
		gen196_cyclix_var = gen249_pipex_var;
		if (gen196_cyclix_var) {
			gen250_pipex_var = ~genpstage_EXEC_data_req_done;
			gen251_pipex_var = gen250_pipex_var;
			gen197_cyclix_var = gen251_pipex_var;
			if (gen197_cyclix_var) {
				genpstage_EXEC_data_busreq = genpstage_EXEC_mem_addr;
				genpstage_EXEC_data_busreq = genpstage_EXEC_mem_be;
				genpstage_EXEC_data_busreq = genpstage_EXEC_mem_wdata;
				gen198_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen198_cyclix_var) {
					gen199_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen200_cyclix_var = gen199_cyclix_var;
					if (gen200_cyclix_var) {
						gen283_pipex_req_struct = genpstage_EXEC_mem_cmd;
						gen283_pipex_req_struct = genpstage_EXEC_data_busreq;
						gen201_cyclix_var = genmcopipe_data_mem_req.write_nb(gen283_pipex_req_struct);
						gen202_cyclix_var = gen201_cyclix_var;
						if (gen202_cyclix_var) {
							gen252_pipex_var = ap_uint<32>(1);
							gen203_cyclix_var = !genpstage_EXEC_mem_cmd;
							genpstage_EXEC_TRX_BUF = gen203_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen204_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
							if (gen204_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_data_req_done = gen252_pipex_var;
				gen205_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen205_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen252_pipex_var;
				}
			}
			gen253_pipex_var = ~genpstage_EXEC_data_req_done;
			gen254_pipex_var = gen253_pipex_var;
			gen206_cyclix_var = gen254_pipex_var;
			if (gen206_cyclix_var) {
				gen207_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen207_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen255_pipex_var = genpstage_EXEC_mem_req;
		gen208_cyclix_var = gen255_pipex_var;
		if (gen208_cyclix_var) {
			gen256_pipex_var = ~genpstage_EXEC_mem_cmd;
			gen257_pipex_var = gen256_pipex_var;
			gen209_cyclix_var = gen257_pipex_var;
			if (gen209_cyclix_var) {
				gen210_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				if (gen210_cyclix_var) {
					genpstage_EXEC_mem_rdata = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdata;
				}
				gen258_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				gen259_pipex_var = gen258_pipex_var;
				gen211_cyclix_var = gen259_pipex_var;
				if (gen211_cyclix_var) {
					genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				}
				gen260_pipex_var = ap_uint<1>(0);
				gen260_pipex_var = (gen260_pipex_var || gen259_pipex_var);
				gen260_pipex_var = !gen260_pipex_var;
				gen212_cyclix_var = gen260_pipex_var;
				if (gen212_cyclix_var) {
					gen213_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen213_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		gen261_pipex_var = (genpstage_EXEC_mem_be == ap_uint<32>(1));
		gen262_pipex_var = gen261_pipex_var;
		gen214_cyclix_var = gen262_pipex_var;
		if (gen214_cyclix_var) {
			gen263_pipex_var = genpstage_EXEC_load_signext;
			gen215_cyclix_var = gen263_pipex_var;
			if (gen215_cyclix_var) {
				gen264_pipex_var = genpstage_EXEC_mem_rdata[7:0];
				gen265_pipex_var = gen264_pipex_var[7];
				gen266_pipex_var = gen265_pipex_var.concat((ap_uint<31>)gen265_pipex_var.concat((ap_uint<30>)gen265_pipex_var.concat((ap_uint<29>)gen265_pipex_var.concat((ap_uint<28>)gen265_pipex_var.concat((ap_uint<27>)gen265_pipex_var.concat((ap_uint<26>)gen265_pipex_var.concat((ap_uint<25>)gen265_pipex_var.concat((ap_uint<24>)gen265_pipex_var.concat((ap_uint<23>)gen265_pipex_var.concat((ap_uint<22>)gen265_pipex_var.concat((ap_uint<21>)gen265_pipex_var.concat((ap_uint<20>)gen265_pipex_var.concat((ap_uint<19>)gen265_pipex_var.concat((ap_uint<18>)gen265_pipex_var.concat((ap_uint<17>)gen265_pipex_var.concat((ap_uint<16>)gen265_pipex_var.concat((ap_uint<15>)gen265_pipex_var.concat((ap_uint<14>)gen265_pipex_var.concat((ap_uint<13>)gen265_pipex_var.concat((ap_uint<12>)gen265_pipex_var.concat((ap_uint<11>)gen265_pipex_var.concat((ap_uint<10>)gen265_pipex_var.concat((ap_uint<9>)gen265_pipex_var.concat((ap_uint<8>)genpstage_EXEC_mem_rdata[7:0]))))))))))))))))))))))));
				genpstage_EXEC_mem_rdata = gen266_pipex_var;
			}
			gen267_pipex_var = ap_uint<1>(0);
			gen267_pipex_var = (gen267_pipex_var || gen263_pipex_var);
			gen267_pipex_var = !gen267_pipex_var;
			gen216_cyclix_var = gen267_pipex_var;
			if (gen216_cyclix_var) {
				gen268_pipex_var = ap_uint<24>(0).concat((ap_uint<8>)genpstage_EXEC_mem_rdata[7:0]);
				genpstage_EXEC_mem_rdata = gen268_pipex_var;
			}
		}
		gen269_pipex_var = (genpstage_EXEC_mem_be == ap_uint<32>(3));
		gen270_pipex_var = gen269_pipex_var;
		gen217_cyclix_var = gen270_pipex_var;
		if (gen217_cyclix_var) {
			gen271_pipex_var = genpstage_EXEC_load_signext;
			gen218_cyclix_var = gen271_pipex_var;
			if (gen218_cyclix_var) {
				gen272_pipex_var = genpstage_EXEC_mem_rdata[15:0];
				gen273_pipex_var = gen272_pipex_var[15];
				gen274_pipex_var = gen273_pipex_var.concat((ap_uint<31>)gen273_pipex_var.concat((ap_uint<30>)gen273_pipex_var.concat((ap_uint<29>)gen273_pipex_var.concat((ap_uint<28>)gen273_pipex_var.concat((ap_uint<27>)gen273_pipex_var.concat((ap_uint<26>)gen273_pipex_var.concat((ap_uint<25>)gen273_pipex_var.concat((ap_uint<24>)gen273_pipex_var.concat((ap_uint<23>)gen273_pipex_var.concat((ap_uint<22>)gen273_pipex_var.concat((ap_uint<21>)gen273_pipex_var.concat((ap_uint<20>)gen273_pipex_var.concat((ap_uint<19>)gen273_pipex_var.concat((ap_uint<18>)gen273_pipex_var.concat((ap_uint<17>)gen273_pipex_var.concat((ap_uint<16>)genpstage_EXEC_mem_rdata[15:0]))))))))))))))));
				genpstage_EXEC_mem_rdata = gen274_pipex_var;
			}
			gen275_pipex_var = ap_uint<1>(0);
			gen275_pipex_var = (gen275_pipex_var || gen271_pipex_var);
			gen275_pipex_var = !gen275_pipex_var;
			gen219_cyclix_var = gen275_pipex_var;
			if (gen219_cyclix_var) {
				gen276_pipex_var = ap_uint<16>(0).concat((ap_uint<16>)genpstage_EXEC_mem_rdata[15:0]);
				genpstage_EXEC_mem_rdata = gen276_pipex_var;
			}
		}
		gen277_pipex_var = (genpstage_EXEC_rd_source == ap_uint<32>(5));
		gen278_pipex_var = gen277_pipex_var;
		gen220_cyclix_var = gen278_pipex_var;
		if (gen220_cyclix_var) {
			genpstage_EXEC_rd_wdata = genpstage_EXEC_mem_rdata;
		}
		gen279_pipex_var = genpstage_EXEC_rd_req;
		gen221_cyclix_var = gen279_pipex_var;
		if (gen221_cyclix_var) {
			gen142_pipex_succreq = ap_uint<32>(1);
			gen143_pipex_succbuf = genpstage_EXEC_rd_wdata;
		}
		gen222_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen222_cyclix_var) {
			genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		}
		gen223_cyclix_var = ap_uint<1>(0);
		gen223_cyclix_var = (gen223_cyclix_var || gen222_cyclix_var);
		gen223_cyclix_var = !gen223_cyclix_var;
		if (gen223_cyclix_var) {
			genpstage_EXEC_genctrl_finish = genpstage_EXEC_genctrl_occupied;
			genpstage_EXEC_genctrl_succ = genpstage_EXEC_genctrl_active;
		}
		gen224_cyclix_var = genpstage_EXEC_genctrl_succ;
		if (gen224_cyclix_var) {
			gen225_cyclix_var = gen136_pipex_succreq;
			if (gen225_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen137_pipex_succbuf;
			}
			gen226_cyclix_var = gen138_pipex_succreq;
			if (gen226_cyclix_var) {
				genpsticky_glbl_pc = gen139_pipex_succbuf;
			}
			gen227_cyclix_var = gen140_pipex_succreq;
			if (gen227_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = gen141_pipex_succbuf;
			}
			gen228_cyclix_var = gen142_pipex_succreq;
			if (gen228_cyclix_var) {
				genpsticky_glbl_regfile = gen143_pipex_succbuf[1];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[2];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[3];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[4];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[5];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[6];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[7];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[8];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[9];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[10];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[11];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[12];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[13];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[14];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[15];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[16];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[17];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[18];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[19];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[20];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[21];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[22];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[23];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[24];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[25];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[26];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[27];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[28];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[29];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[30];
				genpsticky_glbl_regfile = gen143_pipex_succbuf[31];
			}
		}
		gen229_cyclix_var = genpstage_EXEC_genctrl_finish;
		if (gen229_cyclix_var) {
			gen230_cyclix_var = genpstage_EXEC_genctrl_succ;
			if (gen230_cyclix_var) {
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen231_cyclix_var = ~genpstage_EXEC_TRX_BUF_COUNTER_FULL;
		genpstage_EXEC_genctrl_rdy = gen231_cyclix_var;
		genpstage_EXEC_genctrl_working = (genpstage_EXEC_genctrl_succ | genpstage_EXEC_genctrl_stalled_glbl);
		gen232_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen232_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen233_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen234_cyclix_var = gen233_cyclix_var;
			if (gen234_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen235_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen235_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen236_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen237_cyclix_var = gen236_cyclix_var;
			if (gen237_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen238_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen238_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen239_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen240_cyclix_var = gen239_cyclix_var;
			if (gen240_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen241_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen241_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen242_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen243_cyclix_var = gen242_cyclix_var;
			if (gen243_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
	}
}
